### ISSUE TITLE
Version 0.12.3 AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by karthikbalu** [RasaHQ/rasa_nlu#1069]
**Rasa NLU version**: 0.12.3

**Operating system** osx

**Content of model configuration file**:
```

{
    "pipeline": [
      "nlp_spacy",
      "tokenizer_spacy",
      "intent_featurizer_spacy",
      "intent_classifier_sklearn",
      "ner_crf",
      "ner_synonyms"
    ],
    "path" : "./models/nlu",
    "project": "clofusbot",
    "fixed_model_name": "current",
    "data" : "./intents",
    "port": 5004
  }

```

**Issue**:

python -m rasa_nlu.train -c nlu_model_config.json --fixed_model_name current -d ./intents
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/karthikbalu/MYDRIVE/DEVELOPMENT/Clofus/clofus-assistant/rasa_nlu/rasa_nlu/train.py", line 174, in <module>
    num_threads=cmdline_args.num_threads)
  File "/Users/karthikbalu/MYDRIVE/DEVELOPMENT/Clofus/clofus-assistant/rasa_nlu/rasa_nlu/train.py", line 143, in do_train
    trainer = Trainer(cfg, component_builder)
  File "/Users/karthikbalu/MYDRIVE/DEVELOPMENT/Clofus/clofus-assistant/rasa_nlu/rasa_nlu/model.py", line 146, in __init__
    components.validate_requirements(cfg.component_names)
  File "/Users/karthikbalu/MYDRIVE/DEVELOPMENT/Clofus/clofus-assistant/rasa_nlu/rasa_nlu/config.py", line 146, in component_names
    return [c.get("name") for c in self.pipeline]
  File "/Users/karthikbalu/MYDRIVE/DEVELOPMENT/Clofus/clofus-assistant/rasa_nlu/rasa_nlu/config.py", line 146, in <listcomp>
    return [c.get("name") for c in self.pipeline]
AttributeError: 'str' object has no attribute 'get'

**Comment by wrathagom** [comment]
There are a lot of config changes that came with 0.12 make sure you're using the docs for help on configuring 0.12.3: https://nlu.rasa.com

For example, the config file is now specified via yaml and only expects language and pipeline keys. Everything else should be specified as command line arguments: https://nlu.rasa.com/http.html#server-parameters

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
