### ISSUE TITLE
Training NLU on remote node prevents the model from being run anywhere else

### ISSUE THREAD

**Issue by jgutta** [RasaHQ/rasa_nlu#1111]
**Rasa NLU version**: 12.3

**Operating system** (windows, osx, ...): MacOS, Linux

**Content of model configuration file**:
```yml
  language: "en"
  pipeline:
    - name: "nlp_spacy"
      model: "en"
    - name: "tokenizer_spacy"
    - name: "intent_featurizer_count_vectors"
    - name: "intent_classifier_tensorflow_embedding"
      intent_tokenization_flag: false
    - name:   "ner_crf"
      BILOU_flag": true
      features:
      - ["low", "title", "upper", "pos", "pos2", "word3", "digit"]
      - ["low", "upper", "bias", "pos", "pos2", "title", "word3", "digit"]
      - ["low", "title","upper", "pos", "pos2", "word3", "digit"]
      max_iterations: 50
      L1_c: 1
      L2_c: 1e-4
```

**Issue**: I train my nlu on a remote gpu box, and it appears that the path to the install of rasa is recorded and referenced someplace in the pickled model files. Trying to run rasa_nlu.evaluate gives the following:
```
/Users/jgutta/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-05-25 11:28:27 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
2018-05-25 11:28:28.195082: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-05-25 11:28:28 INFO     tensorflow  - Restoring parameters from models/default/model_20180523-185216/intent_classifier_tensorflow_embedding.ckpt
2018-05-25 11:28:28 INFO     rasa_nlu.training_data.loading  - Training data format of training.json is rasa_nlu
2018-05-25 11:28:30 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
(I needed to remove this part, but the data stats print correctly. The error below directly follows this print)
XXX lineno: 105, opcode: 0
Traceback (most recent call last):
  File "/Users/jgutta/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/jgutta/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jgutta/anaconda3/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 718, in <module>
    run_evaluation(cmdline_args.data, cmdline_args.model)
  File "/Users/jgutta/anaconda3/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 508, in run_evaluation
    test_data)
  File "/Users/jgutta/anaconda3/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 418, in get_entity_predictions
    res = interpreter.parse(e.text, only_output_properties=False)
  File "/Users/jgutta/anaconda3/lib/python3.6/site-packages/rasa_nlu/model.py", line 340, in parse
    component.process(message, **self.context)
  File "/Users/jgutta/anaconda3/lib/python3.6/site-packages/rasa_nlu/featurizers/count_vectors_featurizer.py", line 149, in process
    bag = self.vect.transform([self._lemmatize(message)]).toarray()
  File "/Users/jgutta/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 923, in transform
    _, X = self._count_vocab(raw_documents, fixed_vocab=True)
  File "/Users/jgutta/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 792, in _count_vocab
    for feature in analyze(doc):
  File "/Users/jgutta/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 266, in <lambda>
    tokenize(preprocess(self.decode(doc))), stop_words)
  File "/opt/mapr/tools/python/anaconda3/lib/python3.5/site-packages/rasa_nlu/featurizers/count_vectors_featurizer.py", line 105, in <lambda>
SystemError: unknown opcode
```
The last path mentioned is the path to my python install on the other machine, where as the others are on my local. This error did not occur in past versions.

Any help in getting past this error would be very appreciated.

**Comment by akelad** [comment]
Could it be that you have different python models on your local machine/gpu?

**Comment by jgutta** [comment]
I don't think so, as even with the right version the pathing would be the same, but I havent tested it. I will test that out and update on Monday with the results

**Comment by jgutta** [comment]
Update: I have trained a model on the remote machine with an updated python version and it appears as though that resolved the issue. The NLU Evaluate works, and I will return to this thread to update if this runs with core and everything.

**Comment by akelad** [comment]
Alright, I'll close this for now then. Let us know if you need anything else

**Comment by siddas27** [comment]
I am facing the same issue

**Comment by jgutta** [comment]
Sorry for the delay in updating, the versioning was the issue. Correcting that allowed the model to be run on my local machine. Specifically, I ran:
```
conda install python==3.6.5
pip install --upgrade rasa_core
pip install --upgrade rasa_nlu
pip install --upgrade tensorflow-gpu
````

in that order. That managed to resolve my issues.
