### ISSUE TITLE
Missing spacy/data/en/en_core_web_md-2.0.0/vocab/lexemes.bin

### ISSUE THREAD

**Issue by antoinecomp** [RasaHQ/rasa_nlu#1130]
**Rasa NLU version**:

rasa-core           0.9.0      
rasa-nlu            0.12.3

**Operating system** :

Linux 16.04

**Content of model configuration file**:
```yml
slots:
  location:
    type: text
  mood:
    type: text
  information:
    type: text
  adjective:
    type: text

# intention the bot is able to recognize from the sentences
intents:
 - greet
 - goodbye
 - inform

# entities he may be able to extract
entities:
 - location
 - mood
 - information
 - adjective

# actions the bot can take
actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_location
 - actions.ActionWeather
 - utter_joy
 - utter_fear
 - utter_anger
 - utter_sadness
 - utter_disgust
 - utter_shame
 - utter_guilt

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_location:
    - 'In what location?'
  utter_joy:
    - 'Am so happy for you'
  utter_fear:
    - 'you shouldn be afraid'
  utter_anger:
    - 'Calm down, everything gonna be alright'
  utter_sadness:
    - 'be a tough guy'
  utter_disgust:
    - 'I understand, this is disgusting, we should get over it'
  utter_shame:
    - 'Ridicule does not kill'
  utter_guilt:
    - 'You must not feel guilty, feel proud'
```

**Issue**:

I try to link the front end developed with Flask to its back end developed with rasa_nlu, which used to work well. Yet, when launching rasa_nlu I get this error:

```
(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ python run_app.py 
Traceback (most recent call last):
  File "run_app.py", line 6, in <module>
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/weathernlu')
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/interpreter.py", line 221, in __init__
    self._load_interpreter()
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/interpreter.py", line 237, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/model.py", line 276, in load
    skip_validation)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/model.py", line 303, in create
    model_metadata, **context)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/components.py", line 398, in load_component
    cached_component, **context)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/registry.py", line 131, in load_component_by_name
    return component_clz.load(model_dir, metadata, cached_component, **kwargs)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/utils/spacy_utils.py", line 126, in load
    nlp = spacy.load(model_name, parser=False)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/language.py", line 653, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/language.py", line 641, in <lambda>
    self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self))),
  File "vocab.pyx", line 377, in spacy.vocab.Vocab.from_disk
  File "/usr/lib/python3.5/pathlib.py", line 1151, in open
    opener=self._opener)
  File "/usr/lib/python3.5/pathlib.py", line 1005, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/data/en/en_core_web_md-2.0.0/vocab/lexemes.bin'
```

Here is the code I run to get it: 

```
from rasa_core.channels import HttpInputChannel
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_slack_connector import SlackInput

nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/weathernlu')
agent = Agent.load('./models/dialogue',interpreter = nlu_interpreter)


# With Slack
# https://api.slack.com/apps/AASPDV196/oauth?
#input_channel = SlackInput('OAuth Access Token','Bot User OAuth Access Token', 'Verification Token',True)

#agent.handle_channel(HttpInputChannel(5004,'/',input_channel))

# With inner app
agent.handle_channel(HttpInputChannel(5000,'/',input_channel))
```

And this even after reinstalling spacy and its language model for the english language.

```
(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ pip install rasa_nlu[spacy]
Requirement already satisfied: rasa_nlu[spacy] in ./MoodEnv/lib/python3.5/site-packages (0.12.3)
Requirement already satisfied: pyyaml in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (3.12)
Requirement already satisfied: matplotlib in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (1.5.3)
Requirement already satisfied: typing in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (3.5.3.0)
Requirement already satisfied: tqdm in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (4.11.2)
Requirement already satisfied: numpy>=1.13 in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (1.13.1)
Requirement already satisfied: six in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (1.10.0)
Requirement already satisfied: klein in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (17.2.0)
Requirement already satisfied: packaging in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (17.1)
Requirement already satisfied: gevent in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (1.2.1)
Requirement already satisfied: cloudpickle in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (0.5.3)
Requirement already satisfied: future in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (0.16.0)
Requirement already satisfied: jsonschema in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (2.6.0)
Requirement already satisfied: requests in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (2.14.2)
Requirement already satisfied: boto3 in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (1.4.4)
Requirement already satisfied: pathlib in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (1.0.1)
Requirement already satisfied: simplejson in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (3.11.1)
Requirement already satisfied: scipy; extra == "spacy" in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (1.1.0)
Requirement already satisfied: spacy>2.0; extra == "spacy" in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (2.0.11)
Requirement already satisfied: scikit-learn; extra == "spacy" in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (0.19.1)
Requirement already satisfied: sklearn-crfsuite; extra == "spacy" in ./MoodEnv/lib/python3.5/site-packages (from rasa_nlu[spacy]) (0.3.5)
Requirement already satisfied: pytz in ./MoodEnv/lib/python3.5/site-packages (from matplotlib->rasa_nlu[spacy]) (2018.4)
Requirement already satisfied: cycler in ./MoodEnv/lib/python3.5/site-packages (from matplotlib->rasa_nlu[spacy]) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,>=1.5.6 in ./MoodEnv/lib/python3.5/site-packages (from matplotlib->rasa_nlu[spacy]) (2.2.0)
Requirement already satisfied: python-dateutil in ./MoodEnv/lib/python3.5/site-packages (from matplotlib->rasa_nlu[spacy]) (2.7.3)
Requirement already satisfied: incremental in ./MoodEnv/lib/python3.5/site-packages (from klein->rasa_nlu[spacy]) (17.5.0)
Requirement already satisfied: werkzeug in ./MoodEnv/lib/python3.5/site-packages (from klein->rasa_nlu[spacy]) (0.14.1)
Requirement already satisfied: Twisted>=13.2 in ./MoodEnv/lib/python3.5/site-packages (from klein->rasa_nlu[spacy]) (18.4.0)
Requirement already satisfied: greenlet>=0.4.10 in ./MoodEnv/lib/python3.5/site-packages (from gevent->rasa_nlu[spacy]) (0.4.13)
Requirement already satisfied: botocore<1.6.0,>=1.5.0 in ./MoodEnv/lib/python3.5/site-packages (from boto3->rasa_nlu[spacy]) (1.5.95)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in ./MoodEnv/lib/python3.5/site-packages (from boto3->rasa_nlu[spacy]) (0.9.3)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in ./MoodEnv/lib/python3.5/site-packages (from boto3->rasa_nlu[spacy]) (0.1.13)
Requirement already satisfied: murmurhash<0.29,>=0.28 in ./MoodEnv/lib/python3.5/site-packages (from spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (0.28.0)
Requirement already satisfied: plac<1.0.0,>=0.9.6 in ./MoodEnv/lib/python3.5/site-packages (from spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (0.9.6)
Requirement already satisfied: preshed<2.0.0,>=1.0.0 in ./MoodEnv/lib/python3.5/site-packages (from spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (1.0.0)
Requirement already satisfied: cymem<1.32,>=1.30 in ./MoodEnv/lib/python3.5/site-packages (from spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (1.31.2)
Requirement already satisfied: thinc<6.11.0,>=6.10.1 in ./MoodEnv/lib/python3.5/site-packages (from spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (6.10.2)
Requirement already satisfied: regex==2017.4.5 in ./MoodEnv/lib/python3.5/site-packages (from spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (2017.4.5)
Requirement already satisfied: ujson>=1.35 in ./MoodEnv/lib/python3.5/site-packages (from spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (1.35)
Requirement already satisfied: dill<0.3,>=0.2 in ./MoodEnv/lib/python3.5/site-packages (from spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (0.2.7.1)
Requirement already satisfied: python-crfsuite>=0.8.3 in ./MoodEnv/lib/python3.5/site-packages (from sklearn-crfsuite; extra == "spacy"->rasa_nlu[spacy]) (0.9.5)
Requirement already satisfied: tabulate in ./MoodEnv/lib/python3.5/site-packages (from sklearn-crfsuite; extra == "spacy"->rasa_nlu[spacy]) (0.8.2)
Requirement already satisfied: constantly>=15.1 in ./MoodEnv/lib/python3.5/site-packages (from Twisted>=13.2->klein->rasa_nlu[spacy]) (15.1.0)
Requirement already satisfied: Automat>=0.3.0 in ./MoodEnv/lib/python3.5/site-packages (from Twisted>=13.2->klein->rasa_nlu[spacy]) (0.6.0)
Requirement already satisfied: zope.interface>=4.4.2 in ./MoodEnv/lib/python3.5/site-packages (from Twisted>=13.2->klein->rasa_nlu[spacy]) (4.5.0)
Requirement already satisfied: hyperlink>=17.1.1 in ./MoodEnv/lib/python3.5/site-packages (from Twisted>=13.2->klein->rasa_nlu[spacy]) (18.0.0)
Requirement already satisfied: docutils>=0.10 in ./MoodEnv/lib/python3.5/site-packages (from botocore<1.6.0,>=1.5.0->boto3->rasa_nlu[spacy]) (0.14)
Requirement already satisfied: msgpack-numpy==0.4.1 in ./MoodEnv/lib/python3.5/site-packages (from thinc<6.11.0,>=6.10.1->spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (0.4.1)
Requirement already satisfied: wrapt in ./MoodEnv/lib/python3.5/site-packages (from thinc<6.11.0,>=6.10.1->spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (1.10.11)
Requirement already satisfied: termcolor in ./MoodEnv/lib/python3.5/site-packages (from thinc<6.11.0,>=6.10.1->spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (1.1.0)
Requirement already satisfied: msgpack-python in ./MoodEnv/lib/python3.5/site-packages (from thinc<6.11.0,>=6.10.1->spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (0.5.6)
Requirement already satisfied: cytoolz<0.9,>=0.8 in ./MoodEnv/lib/python3.5/site-packages (from thinc<6.11.0,>=6.10.1->spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (0.8.2)
Requirement already satisfied: attrs in ./MoodEnv/lib/python3.5/site-packages (from Automat>=0.3.0->Twisted>=13.2->klein->rasa_nlu[spacy]) (18.1.0)
Requirement already satisfied: setuptools in ./MoodEnv/lib/python3.5/site-packages (from zope.interface>=4.4.2->Twisted>=13.2->klein->rasa_nlu[spacy]) (20.7.0)
Requirement already satisfied: idna>=2.5 in ./MoodEnv/lib/python3.5/site-packages (from hyperlink>=17.1.1->Twisted>=13.2->klein->rasa_nlu[spacy]) (2.6)
Requirement already satisfied: toolz>=0.8.0 in ./MoodEnv/lib/python3.5/site-packages (from cytoolz<0.9,>=0.8->thinc<6.11.0,>=6.10.1->spacy>2.0; extra == "spacy"->rasa_nlu[spacy]) (0.9.0)
en-core-web-sm 1.2.0 has requirement spacy<2.0.0,>=1.7.0, but you'll have spacy 2.0.11 which is incompatible.
tensorflow 1.8.0 has requirement numpy>=1.13.3, but you'll have numpy 1.13.1 which is incompatible.
rasa-core 0.9.0 has requirement coloredlogs~=10.0, but you'll have coloredlogs 7.3 which is incompatible.
rasa-core 0.9.0 has requirement ConfigArgParse~=0.13.0, but you'll have configargparse 0.12.0 which is incompatible.
rasa-core 0.9.0 has requirement fakeredis~=0.10.0, but you'll have fakeredis 0.8.2 which is incompatible.
rasa-core 0.9.0 has requirement fbmessenger~=5.0, but you'll have fbmessenger 4.3.1 which is incompatible.
rasa-core 0.9.0 has requirement flask~=1.0, but you'll have flask 0.12 which is incompatible.
rasa-core 0.9.0 has requirement graphviz~=0.8.0, but you'll have graphviz 0.7.1 which is incompatible.
rasa-core 0.9.0 has requirement networkx~=2.0, but you'll have networkx 1.11 which is incompatible.
rasa-core 0.9.0 has requirement requests~=2.15, but you'll have requests 2.14.2 which is incompatible.

(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ python -m spacy download en_core_web_md
Collecting https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz (120.8MB)
    100% |████████████████████████████████| 120.9MB 3.7MB/s 
Requirement already satisfied (use --upgrade to upgrade): en-core-web-md==2.0.0 from https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz in ./MoodEnv/lib/python3.5/site-packages

    Linking successful
    /home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/en_core_web_md
    -->
    /home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/spacy/data/en_core_web_md

    You can now load the model via spacy.load('en_core_web_md')

(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ python -m spacy link en_core_web_md en

    Link 'en' already exists
    To overwrite an existing link, use the --force flag.
```

**Comment by akelad** [comment]
Hm I can't see your nlu config file, but looks like you're trying to link en_core_web_md to en, which didn't work because the link already exists. Try running it again with the `--force` flag
