### ISSUE TITLE
Model delete endpoint not accepting params

### ISSUE THREAD

**Issue by DigitalDean** [RasaHQ/rasa_nlu#1137]
**Rasa NLU version**:
"version": "0.12.3"

**Operating system** (windows, osx, ...):
macOS High Sierra

**Issue**:
Basically, it looks as though the /model delete endpoint is not accepting the params? Have tried via cmd line and postman with various header/body contents.

Any ideas?

Command:
`curl -XDELETE localhost:5000/models -d '{"project": "dean_test", "model": <model_20180605-154120>}'`

Server startup:
`python -m rasa_nlu.server --path projects --config /Users/deanwithey/Code/rasa_nlu-0.12.3/configs/config_spacy.yml -v`

Results in:
`2018-06-05 16:13:05+0100 [-] Log opened.
2018-06-05 16:13:05+0100 [-] Site starting on 5000
2018-06-05 16:13:05+0100 [-] Starting factory <twisted.web.server.Site object at 0x10eb45668>
2018-06-05 16:13:06+0100 [-] 2018-06-05 16:13:06 ERROR    __main__ - Failed to unload model None for project default.
2018-06-05 16:13:06+0100 [-] Traceback (most recent call last):
2018-06-05 16:13:06+0100 [-]   File "/Users/deanwithey/Code/rasa_nlu-0.12.3/rasa_nlu/data_router.py", line 390, in unload_model
2018-06-05 16:13:06+0100 [-]     unloaded_model = self.project_store[project].unload(model)
2018-06-05 16:13:06+0100 [-]   File "/Users/deanwithey/Code/rasa_nlu-0.12.3/rasa_nlu/project.py", line 159, in unload
2018-06-05 16:13:06+0100 [-]     del self._models[model_name]
2018-06-05 16:13:06+0100 [-] KeyError: None
2018-06-05 16:13:06+0100 [-]
2018-06-05 16:13:06+0100 [-] During handling of the above exception, another exception occurred:
2018-06-05 16:13:06+0100 [-]
2018-06-05 16:13:06+0100 [-] Traceback (most recent call last):
2018-06-05 16:13:06+0100 [-]   File "/Users/deanwithey/Code/rasa_nlu-0.12.3/rasa_nlu/server.py", line 365, in unload_model
2018-06-05 16:13:06+0100 [-]     params.get('model')
2018-06-05 16:13:06+0100 [-]   File "/Users/deanwithey/Code/rasa_nlu-0.12.3/rasa_nlu/data_router.py", line 394, in unload_model
2018-06-05 16:13:06+0100 [-]     "for project {}.".format(model, project))
2018-06-05 16:13:06+0100 [-] rasa_nlu.model.InvalidProjectError: Failed to unload model None for project default.
2018-06-05 16:13:06+0100 [-] "127.0.0.1" - - [05/Jun/2018:15:13:06 +0000] "DELETE /models HTTP/1.1" 500 61 "-" "curl/7.54.0"`

**Comment by zymprogramer** [comment]
hi. Have you solve this problem? I have a same issue with you

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon.

**Comment by tmbo** [comment]
It doesn't seem like either one of your parameters gets parsed properly.

If I remember correctly, the endpoint expectes the parameters to be part of the URL not the body, so try a `DELETE localhost:5000/models?project=dean_test&model=model_20180605-154120`.

**Comment by zymprogramer** [comment]
Hi, this solve my problem. Thank you very much. You may change the doc in the website as well

**Comment by tmbo** [comment]
That is a very good point, do you mind creating a PR changing the line in the docs updating it with the command that is working for you?

**Comment by zymprogramer** [comment]
ok sure, I will do this later
