### ISSUE TITLE
Tensorflow pipeline Evaluation

### ISSUE THREAD

**Issue by CROptum** [RasaHQ/rasa_nlu#1167]
**Rasa NLU version**: latest/master

**Operating system** (windows, osx, ...): osx

**Content of model configuration file**:

**Issue**: Generated model using config for TensorFlow.  While doing 'evaluate' with data & model as input, failing with an error.  Please see below for command & error trace.
```
$ python -m rasa_nlu.evaluate --data /Developer/Work/rasa-nlu-tensor/UC48_test.yml --model /Developer/Work/rasa_nlu/projects/uc48/model_20180618-143754
/Users/cr/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/Users/cr/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/cr/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Developer/Work/rasa_nlu/rasa_nlu/evaluate.py", line 729, in <module>
    main()
  File "/Developer/Work/rasa_nlu/rasa_nlu/evaluate.py", line 723, in main
    run_evaluation(cmdline_args.data, cmdline_args.model)
  File "/Developer/Work/rasa_nlu/rasa_nlu/evaluate.py", line 508, in run_evaluation
    interpreter = Interpreter.load(model_path, component_builder)
  File "/Developer/Work/rasa_nlu/rasa_nlu/model.py", line 274, in load
    skip_validation)
  File "/Developer/Work/rasa_nlu/rasa_nlu/model.py", line 301, in create
    model_metadata, **context)
  File "/Developer/Work/rasa_nlu/rasa_nlu/components.py", line 405, in load_component
    cached_component, **context)
  File "/Developer/Work/rasa_nlu/rasa_nlu/registry.py", line 133, in load_component_by_name
    return component_clz.load(model_dir, metadata, cached_component, **kwargs)
  File "/Developer/Work/rasa_nlu/rasa_nlu/featurizers/count_vectors_featurizer.py", line 255, in load
    return utils.pycloud_unpickle(featurizer_file)
  File "/Developer/Work/rasa_nlu/rasa_nlu/utils/__init__.py", line 322, in pycloud_unpickle
    return cloudpickle.load(f, encoding="latin-1")
TypeError: an integer is required (got type str)
```

**Comment by RAJAT--PALIWAL** [comment]
Try with absolute path instead of static and use json instead of yml for test.
`python -m rasa_nlu.evaluate --data training_data_path --model model_directory_path`

**Comment by amn41** [comment]
did you train the model with the same rasa nlu and python versions as you are using to evaluate? 

you can also try running `python -m rasa_nlu.evaluate --crossvalidation -d training_data_path` which will eval with cross-validation and doesn't need a trained model (just as a sanity check)
