### ISSUE TITLE
TypeError: unhashable type: 'dict' when loading the RasaNLUInterpreter

### ISSUE THREAD

**Issue by antoinecomp** [RasaHQ/rasa_nlu#1278]
**Rasa NLU version**: 0.12.3

**Operating system** : Ubuntu 16.04

**Content of model configuration file**:

config_spacy_duckling.yml
```yml
language: "en"

pipeline:
# this is using the spacy sklearn pipeline, adding duckling
# all components will use their default values
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "ner_duckling"
```

**Issue**:

Anytime I try to launch `train_online.py` I got a `TypeError: unhashable type: 'dict'` when loading the RasaNLUInterpreter with `RasaNLUInterpreter('./models/nlu/default/moodnlu')`. I don't know if it is related with the pickle files. Here is the content of `moodnlu/`folder:

```
(MyFlaskAppEnv) mike@mike-thinks:~/Programming/Rasa/myflaskapp/models/nlu/default/moodnlu$ ls
crf_model.pkl  intent_classifier_sklearn.pkl  metadata.json  training_data.json
```

Here is the error:

```
(MyFlaskAppEnv) mike@mike-thinks:~/Programming/Rasa/myflaskapp$ python3 train_online.py 
Traceback (most recent call last):
  File "train_online.py", line 37, in <module>
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/moodnlu')
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/interpreter.py", line 219, in __init__
    self._load_interpreter()
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/interpreter.py", line 238, in _load_interpreter
    os.environ))
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/model.py", line 230, in load
    skip_valdation)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/model.py", line 253, in create
    components.validate_requirements(model_metadata.pipeline)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/components.py", line 56, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/registry.py", line 125, in get_component_class
    if component_name not in registered_components:
TypeError: unhashable type: 'dict'
```

I had this issue before but I don't remember how I dealt with it.

**Comment by akelad** [comment]
Could it be that that's an old model? Have you tried retraining it?

**Comment by antoinecomp** [comment]
True ! I didn't know it had an expiry date
