### ISSUE TITLE
error while training nlu data

### ISSUE THREAD

**Issue by Priya-ch** [RasaHQ/rasa_nlu#1288]
**Rasa NLU version**: 0.13.a2

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Content of model configuration file**:
```yml
language: "en"

pipeline: "spacy_sklearn"

```

**Issue**:

Getting AttributeError: 'module' object has no attribute 'CheckpointableBase'
while training nlu data with spacy_sklearn pipeline.

Command executed:
python -m rasa_nlu.train --config config/config_mittie_sklearn.yml --data chat.md --path models/new

Error snippet:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/system/Priya/aricentChat/rasa_nlu/rasa_nlu/train.py", line 167, in <module>
    do_train(config.load(cmdline_args.config),
  File "rasa_nlu/config.py", line 51, in load
    return RasaNLUModelConfig(file_config)
  File "rasa_nlu/config.py", line 106, in __init__
    from rasa_nlu import registry
  File "rasa_nlu/registry.py", line 23, in <module>
    from rasa_nlu.classifiers.embedding_intent_classifier import \
  File "rasa_nlu/classifiers/embedding_intent_classifier.py", line 33, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/framework_lib.py", line 104, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 32, in <module>
    from tensorflow.python.framework import function
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 36, in <module>
    from tensorflow.python.ops import resource_variable_ops
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 35, in <module>
    from tensorflow.python.ops import variables
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 40, in <module>
    class Variable(checkpointable.CheckpointableBase):
AttributeError: 'module' object has no attribute 'CheckpointableBase'

**Comment by akelad** [comment]
It looks like you're using the tensorflow embedding pipeline, but you've posted a different config? What's the actual contents of `config/config_mittie_sklearn.yml`

**Comment by Priya-ch** [comment]
Earlier I was using tensorflow but then changed it to spacy_sklearn when it was giving error. But still this error is not resolved. 

**config/config_mittie_sklearn.yml:**
language: "en"
pipeline: "spacy_sklearn"

I have uninstalled tensorflow from my system , now nlu is getting trained but on training the core it is giving same error for tensorflow.

Then again installed the tensorflow
"Successfully installed protobuf-3.6.0 tensorboard-1.8.0 tensorflow-1.8.0"

Command executed:
python -m rasa_core.train -d pss_domain.yml -s data/stories.md -o models/curret/dialogue --epochs 200

Error:
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/system/Priya/aricentChat/rasa_core/rasa_core/train.py", line 155, in <module>
    additional_arguments)
  File "/home/system/Priya/aricentChat/rasa_core/rasa_core/train.py", line 106, in train_dialogue_model
    max_history=max_history))])
  File "rasa_core/policies/keras_policy.py", line 47, in __init__
    if KerasPolicy.is_using_tensorflow() and not graph:
  File "rasa_core/policies/keras_policy.py", line 64, in is_using_tensorflow
    from keras.backend import _BACKEND
  File "/usr/local/lib/python2.7/dist-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/__init__.py", line 84, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/framework_lib.py", line 104, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 32, in <module>
    from tensorflow.python.framework import function
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 36, in <module>
    from tensorflow.python.ops import resource_variable_ops
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 35, in <module>
    from tensorflow.python.ops import variables
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 40, in <module>
    class Variable(checkpointable.CheckpointableBase):
AttributeError: 'module' object has no attribute 'CheckpointableBase'

**Comment by akelad** [comment]
I would guess somethings up with your tensorflow version then, can you try downgrading to 1.6.0 for example?

**Comment by akelad** [comment]
I'm gonna close this issue for now, if you're still having problems please open a new issue
