### ISSUE TITLE
namedtuple bug in evaluate.py

### ISSUE THREAD

**Issue by esrel** [RasaHQ/rasa_nlu#1298]
**Rasa NLU version**: 0.13.x

**Operating system** (windows, osx, ...): osx

**Content of model configuration file**: irrelevant
```yml

```

**Issue**:
Give the following error
```
2018-08-08 14:17:35 INFO     __main__  - Intent evaluation results:
Traceback (most recent call last):
  File "/anaconda3/envs/eas/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/eas/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/envs/eas/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 843, in <module>
    main()
  File "/anaconda3/envs/eas/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 837, in main
    cmdline_args.histogram)
  File "/anaconda3/envs/eas/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 630, in run_evaluation
    intent_hist_filename)
  File "/anaconda3/envs/eas/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 258, in evaluate_intents
    intent_results = remove_empty_intent_examples(intent_results)
  File "/anaconda3/envs/eas/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 176, in remove_empty_intent_examples
    r.prediction = ""
AttributeError: can't set attribute
```

substituting line 176 with the line below solves the problem
```
r = r._replace(prediction="")
```

**Comment by akelad** [comment]
Thanks for raising this issue, @JoeyFaulkner will get back to you about it soon.

**Comment by esrel** [comment]
Hi! 
I don't think It's related to the domain. In my understanding, it is the combination of two things that have changed in version 0.13.x: (1) do not predict anything if feature vector contains only zeros in tensorflow embedding classifier and (2) rasa_nlu's evaluate.py using namedtuples and replacing None predictions with empty string for intent predictions in line 176 (r.prediction = ""), which should be (r = r._replace(prediction="")) according to https://docs.python.org/3/library/collections.html#collections.namedtuple, imho. 

what I do:
1. train tensorflow embedding intent classifier (using config_embedding.yml configuration)
2. evaluate the model on data that contains examples that will yield all-zero embedding vectors, as 
The issue does not arise with models trained with different configurations.

To replicate the issue, do the following:
1. train NLU model using franken_data.json from restaurantbot example of rasa core, as:
```
python -m rasa_nlu.train -o models -d franken_data.json -c config_embedding.yml
```
2. try to evaluate that model on nlu.md data from moodbot example, as:
```
python -m rasa_nlu.evaluate -d nlu.md -m models/default/model_xxxxxxxx-xxxxxx
```
I hope I made the issue clearer.

**Comment by JoeyFaulkner** [comment]
that makes sense! would you like to submit this as a PR? please reference this issue when you do so. Thanks!
