### ISSUE TITLE
Evaluation script broken since Rasa 0.13.0

### ISSUE THREAD

**Issue by djuelg** [RasaHQ/rasa_nlu#1310]
**Rasa NLU version**: 0.13.1 (occours also on 0.13.0)

**Operating system** (windows, osx, ...): Ubuntu Gnome 16.04

**Content of model configuration file**:
```yml
pipeline:
  - name: "nlp_spacy"
  - name: "tokenizer_spacy"
  - name: "intent_entity_featurizer_regex"
  - name: "intent_featurizer_count_vectors"
  - name: "ner_crf"
  - name: "ner_synonyms"
  - name: "intent_classifier_tensorflow_embedding"
```

**Executed command**:
```bash
python3 -m rasa_nlu.evaluate \
    --config service/rasa/config/nlu_model_config.yml \
    --data service/rasa/data/nlu_data.json \
    --mode crossvalidation --debug
```

**Issue**:
Since some changes in `evaluate.py` the script is broken (`AttributeError: can't set attribute`). I think dd5a349ea408311243ad2e05e8bf1a77abbb0ac3 ist the evil one.

```
2018-08-13 08:37:44 DEBUG    rasa_nlu.training_data.training_data  - Validating training data...
2018-08-13 08:37:44 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
	- intent examples: 2113 (6 distinct intents)
	- Found intents: 'botinfo', 'greet', 'thank', 'fetch_news', 'fetch_tasks', 'search_confluence'
	- entity examples: 1993 (1 distinct entities)
	- found entities: 'technical_term'

2018-08-13 08:37:44 DEBUG    rasa_nlu.training_data.training_data  - Validating training data...
2018-08-13 08:37:44 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
	- intent examples: 238 (6 distinct intents)
	- Found intents: 'botinfo', 'greet', 'thank', 'fetch_news', 'fetch_tasks', 'search_confluence'
	- entity examples: 222 (1 distinct entities)
	- found entities: 'technical_term'

2018-08-13 08:37:44 INFO     rasa_nlu.model  - Starting to train component nlp_spacy
2018-08-13 08:38:37 INFO     rasa_nlu.model  - Finished training component.
2018-08-13 08:38:37 INFO     rasa_nlu.model  - Starting to train component tokenizer_spacy
2018-08-13 08:38:37 INFO     rasa_nlu.model  - Finished training component.
2018-08-13 08:38:37 INFO     rasa_nlu.model  - Starting to train component intent_entity_featurizer_regex
2018-08-13 08:38:37 INFO     rasa_nlu.model  - Finished training component.
2018-08-13 08:38:37 INFO     rasa_nlu.model  - Starting to train component intent_featurizer_count_vectors
2018-08-13 08:38:37 INFO     rasa_nlu.model  - Finished training component.
2018-08-13 08:38:37 INFO     rasa_nlu.model  - Starting to train component ner_crf
2018-08-13 08:38:39 INFO     rasa_nlu.model  - Finished training component.
2018-08-13 08:38:39 INFO     rasa_nlu.model  - Starting to train component ner_synonyms
2018-08-13 08:38:39 INFO     rasa_nlu.model  - Finished training component.
2018-08-13 08:38:39 INFO     rasa_nlu.model  - Starting to train component intent_classifier_tensorflow_embedding
2018-08-13 08:38:39 DEBUG    rasa_nlu.classifiers.embedding_intent_classifier  - Check if num_neg 20 is smaller than number of intents 6, else set num_neg to the number of intents - 1
2018-08-13 08:38:48 INFO     rasa_nlu.classifiers.embedding_intent_classifier  - Accuracy is updated every 10 epochs
Epochs: 100%|██████████████████████████████████████████████████████████████████████| 300/300 [01:26<00:00,  3.48it/s, loss=0.004, acc=0.999]
2018-08-13 08:40:14 INFO     rasa_nlu.classifiers.embedding_intent_classifier  - Finished training embedding policy, loss=0.004, train accuracy=0.999
2018-08-13 08:40:14 INFO     rasa_nlu.model  - Finished training component.
Traceback (most recent call last):
  File "/home/djuelg/anaconda3/envs/rasa-nlu-training-1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/djuelg/anaconda3/envs/rasa-nlu-training-1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/djuelg/anaconda3/envs/rasa-nlu-training-1/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 843, in <module>
    main()
  File "/home/djuelg/anaconda3/envs/rasa-nlu-training-1/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 820, in main
    data, int(cmdline_args.folds), nlu_config)
  File "/home/djuelg/anaconda3/envs/rasa-nlu-training-1/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 703, in run_cv_evaluation
    test_results = combine_intent_result(test_results, interpreter, test)
  File "/home/djuelg/anaconda3/envs/rasa-nlu-training-1/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 662, in combine_intent_result
    current_result = compute_intent_metrics(interpreter, data)
  File "/home/djuelg/anaconda3/envs/rasa-nlu-training-1/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 729, in compute_intent_metrics
    intent_results = remove_empty_intent_examples(intent_results)
  File "/home/djuelg/anaconda3/envs/rasa-nlu-training-1/lib/python3.6/site-packages/rasa_nlu/evaluate.py", line 176, in remove_empty_intent_examples
    r.prediction = ""
AttributeError: can't set attribute
```

Greetings,
djuelg

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon.

**Comment by Jcragons** [comment]
same issue here with 

```
language: "fr"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_count_vectors"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "ner_spacy"
- name: "ner_duckling_http"
  url: "http://localhost:50003"
  dimensions: ["time","email","url","phone-number"]
  locale: "fr_FR"
  timezone: "Europe/Paris"
- name: "intent_classifier_tensorflow_embedding"
```

and command 

`python3 -m rasa_nlu.evaluate --data dialog/nlu_data_static_validate.md --model nlu/default/dialog
`
hope it helps

**Comment by esrel** [comment]
It is the same issue as: https://github.com/RasaHQ/rasa_nlu/issues/1298

**Comment by djuelg** [comment]
Okay, then I'll close this one :)
