### ISSUE TITLE
ValueError: mmap length is greater than file size

### ISSUE THREAD

**Issue by andy51002000** [RasaHQ/rasa_nlu#1338]
**Rasa NLU version**:
{"version": "0.10.5"}

**Operating system** (windows, osx, ...):
Run in docker

**Issue**:

I was trying to train my model which contains 

intent examples: 87820 (10 distinct intents) and 
entity examples: 87772 (5 distinct entities).

I always got the error below 

2018-08-24 02:51:34+0000 [-] Traceback (most recent call last):
2018-08-24 02:51:34+0000 [-]   File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
2018-08-24 02:51:34+0000 [-]     self.run()
2018-08-24 02:51:34+0000 [-]   File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
2018-08-24 02:51:34+0000 [-]     self._target(*self._args, **self._kwargs)
2018-08-24 02:51:34+0000 [-]   File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 102, in worker
2018-08-24 02:51:34+0000 [-]     task = get()
2018-08-24 02:51:34+0000 [-]   File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/pool.py", line 362, in get
2018-08-24 02:51:34+0000 [-]     return recv()
2018-08-24 02:51:34+0000 [-]   File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 575, in load
2018-08-24 02:51:34+0000 [-]     obj = _unpickle(fobj, filename, mmap_mode)
2018-08-24 02:51:34+0000 [-]   File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 507, in _unpickle
2018-08-24 02:51:34+0000 [-]     obj = unpickler.load()
2018-08-24 02:51:34+0000 [-]   File "/usr/local/lib/python2.7/pickle.py", line 864, in load
2018-08-24 02:51:34+0000 [-]     dispatch[key](self)
2018-08-24 02:51:34+0000 [-]   File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 340, in load_build
2018-08-24 02:51:34+0000 [-]     self.stack.append(array_wrapper.read(self))
2018-08-24 02:51:34+0000 [-]   File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 181, in read
2018-08-24 02:51:34+0000 [-]     array = self.read_mmap(unpickler)
2018-08-24 02:51:34+0000 [-]   File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 159, in read_mmap
2018-08-24 02:51:34+0000 [-]     offset=offset)
2018-08-24 02:51:34+0000 [-]   File "/usr/local/lib/python2.7/site-packages/numpy/core/memmap.py", line 264, in __new__
2018-08-24 02:51:34+0000 [-]     mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
2018-08-24 02:51:34+0000 [-] ValueError: mmap length is greater than file size

But for a small model, everything works with fine.
I'm wondering how can I fix this problem.

Here is my settings in config.py
`DEFAULT_CONFIG = {
    "project": None,
    "fixed_model_name": None,
    "config": DEFAULT_CONFIG_LOCATION,
    "data": None,
    "emulate": None,
    "language": "en",
    "log_file": None,
    "log_level": 'INFO',
    "mitie_file": os.path.join("data", "total_word_feature_extractor.dat"),
    "spacy_model_name": None,
    "num_threads": 10,
    "max_training_processes": 5,
    "path": "projects",
    "port": 5000,
    "token": None,
    "cors_origins": [],
    "max_number_of_ngrams": 7,
    "pipeline": [],
    "response_log": "logs",
    "storage": None,
    "aws_endpoint_url": None,
    "duckling_dimensions": None,
    "duckling_http_url": None,
    "ner_crf": {
        "BILOU_flag": True,
        "features": [
            ["low", "title", "upper", "pos", "pos2"],
            ["bias", "low", "word3", "word2", "upper", "title", "digit", "pos", "pos2", "pattern"],
            ["low", "title", "upper", "pos", "pos2"]],
        "max_iterations": 50,
        "L1_c": 1,
        "L2_c": 1e-3
    },
    "intent_classifier_sklearn": {
        "C": [1, 2, 5, 10, 20, 100],
        "kernel": "linear"
    }
}
`

**Comment by akelad** [comment]
Do you have enough disk space available? That error is related to writing the model to file
