### ISSUE TITLE
Error while training dialogue model with actions endpoint server

### ISSUE THREAD

**Issue by Sandy26** [RasaHQ/rasa_nlu#1365]
**Issue:** I trained the nlu model first . Then I tried to train the dialogue model in the following way-
 > python3.5 -m rasa_core.train -d domain.yml --endpoints endpoints.yml -s data/stories.md -o models/current/dialogue -u models/current/nlu --epochs 10

The error stack is-
```
Traceback (most recent call last):
  File "/home/zensar/.local/lib/python3.5/site-packages/rasa_core/actions/factories.py", line 48, in _action_class
    cls = utils.class_from_module_path(action_name)
  File "/home/zensar/.local/lib/python3.5/site-packages/rasa_core/utils.py", line 79, in class_from_module_path
    return globals()[module_path]
KeyError: 'action_achievement_report'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zensar/.local/lib/python3.5/site-packages/rasa_core/train.py", line 159, in <module>
    additional_arguments)
  File "/home/zensar/.local/lib/python3.5/site-packages/rasa_core/train.py", line 110, in train_dialogue_model
    max_history=max_history))])
  File "/home/zensar/.local/lib/python3.5/site-packages/rasa_core/agent.py", line 51, in __init__
    self.domain = self._create_domain(domain)
  File "/home/zensar/.local/lib/python3.5/site-packages/rasa_core/agent.py", line 390, in _create_domain
    return TemplateDomain.load(domain)
  File "/home/zensar/.local/lib/python3.5/site-packages/rasa_core/domain.py", line 411, in load
    return cls.load_from_yaml(read_file(filename), action_factory=action_factory)
  File "/home/zensar/.local/lib/python3.5/site-packages/rasa_core/domain.py", line 431, in load_from_yaml
    **additional_arguments
  File "/home/zensar/.local/lib/python3.5/site-packages/rasa_core/domain.py", line 511, in __init__
    action_factory, action_classes, action_names, templates)
  File "/home/zensar/.local/lib/python3.5/site-packages/rasa_core/domain.py", line 518, in instantiate_actions
    custom_actions = action_factory(action_classes, action_names, templates)
  File "/home/zensar/.local/lib/python3.5/site-packages/rasa_core/actions/factories.py", line 77, in local_action_factory
    actions.append(_action_class(name))
  File "/home/zensar/.local/lib/python3.5/site-packages/rasa_core/actions/factories.py", line 69, in _action_class
    "with `utter_`. Error: {}".format(action_name, e))
ValueError: Action 'action_achievement_report' doesn't correspond to a template / action. Module doesn't contain a class with this name. Remember to prefix actions that should utter a template with `utter_`. Error: 'action_achievement_report'
```
Here are the code details-

**Rasa NLU version**: How do i check this?

**Operating system**: linux

**Content of model configuration file(domain.yml)*:
```
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy
  - achievement
  - inform

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye
- action_achievement_report

slots:
   account_type:
      type: categorical
      values:
      - premium
      - basic
   achieve_amt:
      type: float
      min_value: -1.0
      max_value: 1.0
   bucket:
      type: categorical
      values:
      - region
      - product


templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"

  utter_options:
  - text: "Would you like that grouped by regions or products or any other field?"

  utter_achievement_up:
  - text: "Revenue is up by {achieve_amt} "

  utter_achievement_down:
  - text: "Revenue is down by {achieve_amt}"

  utter_achievement_same:
  - text: "Revenue is on par with last year"
```

actions.py file
```
from rasa_core_sdk import Action
from rasa_core_sdk.events import SlotSet

class ActionAchievementReport(Action):
   def name(self):
      # type: () -> Text
      return "action_achievement_report"

   def run(self, dispatcher, tracker, domain):
      # type: (Dispatcher, DialogueStateTracker, Domain) -> List[Event]
      result=0.25

      return [SlotSet("achieve_amt", result if result is not None else [])]
``` 

I already have the endpoint server up in the adjacent terminal-
> python3.5 -m rasa_core_sdk.endpoint --actions actions

I have the standard endpoints.yml file-
```
action_endpoint:
  url: "http://localhost:5055/webhook"
```

Can someone please tell me what I am doing wrong? Please let me know if any more information is needed.

Thank you,
Sandy

**Comment by Sandy26** [comment]
Sorry, issue solved. I need to have -
actions.ActionAchievementReport  instead of action_achievement_report in my domain file. Hope this helps someone next time
