### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.keras'

### ISSUE THREAD

**Issue by fade2black** [RasaHQ/rasa_nlu#1385]
### System information
- Host: MacOS
- Docker: Ubuntu 16.04
- Python 3.6
- Tensorflow 1.8.0 (checked using `python -c "import tensorflow as tf; print(tf.__version__)"`)
- `pip3 show tensorflow`
```
Metadata-Version: 2.0
Name: tensorflow
Version: 1.8.0
Summary: TensorFlow helps the tensors flow
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
Installer: pip
License: Apache 2.0
Location: /usr/local/lib/python3.5/dist-packages
Requires: protobuf, termcolor, gast, astor, absl-py, numpy, six, grpcio, tensorboard, wheel
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  Intended Audience :: Education
  Intended Audience :: Science/Research
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
  Topic :: Scientific/Engineering
  Topic :: Scientific/Engineering :: Mathematics
  Topic :: Scientific/Engineering :: Artificial Intelligence
  Topic :: Software Development
  Topic :: Software Development :: Libraries
  Topic :: Software Development :: Libraries :: Python Modules
Entry-points:
  [console_scripts]
  freeze_graph = tensorflow.python.tools.freeze_graph:run_main
  saved_model_cli = tensorflow.python.tools.saved_model_cli:main
  tensorboard = tensorboard.main:run_main
  toco = tensorflow.contrib.lite.toco.python.toco_wrapper:main
  toco_from_protos = tensorflow.contrib.lite.toco.python.toco_from_protos:main
```

I have installed the following requirements from [here](https://github.com/RasaHQ/rasa_nlu/tree/master/alt_requirements): 

```
###bare
gevent==1.2.2
klein==17.10.0
hyperlink==17.3.1
boto3==1.5.20
typing==3.6.2
future==0.16.0
six==1.11.0
jsonschema==2.6.0
matplotlib==2.1.0
requests==2.18.4
tqdm==4.19.5
numpy==1.14.5
simplejson==3.13.2
cloudpickle==0.5.2
msgpack-python==0.5.4
packaging==17.1
pyyaml==3.12
coloredlogs==9.0

###spacy
spacy==2.0.11
scikit-learn==0.19.1
scipy==1.1.0
sklearn-crfsuite==0.3.6

###tensorflow
scikit-learn==0.19.1
tensorflow==1.8.0
sklearn-crfsuite==0.3.6

###additional
pypandoc
rasa_core
git+https://github.com/apixu/apixu-python.git
```
And my `train_online.py` file is

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging

from rasa_core.agent import Agent
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.train import online
from rasa_core.utils import EndpointConfig

logger = logging.getLogger(__name__)


def run_weather_online(interpreter,
                          domain_file="weather_domain.yml",
                          training_data_file='data/stories.md'):
    action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")						  
    agent = Agent(domain_file,
                  policies=[MemoizationPolicy(max_history=2), KerasPolicy()],
                  interpreter=interpreter,
				  action_endpoint=action_endpoint)
    				  
    data = agent.load_data(training_data_file)
    agent.train(data,
                       batch_size=50,
                       epochs=200,
                       max_training_samples=300)				   
    online.serve_agent(agent)
    return agent


if __name__ == '__main__':
    logging.basicConfig(level="INFO")
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/weathernlu')
    run_weather_online(nlu_interpreter)
```

Then I run  `$python train_online.py`  and have got the following error
```
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/usr/local/lib/python3.6/dist-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from './models/nlu/default/weathernlu/entity_synonyms.json'
  "".format(entity_synonyms_file))
/usr/local/lib/python3.6/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning:
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Processed Story Blocks: 100%|#################################################################################################################################| 10/10 [00:00<00:00, 819.82it/s, # trackers=1]
Processed Story Blocks: 100%|#################################################################################################################################| 10/10 [00:00<00:00, 402.02it/s, # trackers=3]
Processed Story Blocks: 100%|#################################################################################################################################| 10/10 [00:00<00:00, 232.59it/s, # trackers=6]
Processed Story Blocks: 100%|#################################################################################################################################| 10/10 [00:00<00:00, 279.49it/s, # trackers=6]
INFO:rasa_core.featurizers:Creating states and action examples from collected trackers (by MaxHistoryTrackerFeaturizer(SingleStateFeaturizer))...
Processed trackers: 100%|#####################################################################################################################################| 42/42 [00:00<00:00, 144.50it/s, # actions=20]
INFO:rasa_core.featurizers:Created 20 action examples.
Processed actions: 20it [00:00, 1624.09it/s, # examples=20]
INFO:rasa_core.policies.memoization:Memorized 20 unique action examples.
INFO:rasa_core.featurizers:Creating states and action examples from collected trackers (by MaxHistoryTrackerFeaturizer(BinarySingleStateFeaturizer))...
Processed trackers: 100%|#####################################################################################################################################| 42/42 [00:00<00:00, 145.70it/s, # actions=39]
INFO:rasa_core.featurizers:Created 39 action examples.
2018-09-15 00:02:17.440042: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "train_online.py", line 39, in <module>
    run_weather_online(nlu_interpreter)
  File "train_online.py", line 31, in run_weather_online
    max_training_samples=300)
  File "/usr/local/lib/python3.6/dist-packages/rasa_core/agent.py", line 510, in train
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rasa_core/policies/ensemble.py", line 61, in train
    policy.train(training_trackers, domain, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rasa_core/policies/keras_policy.py", line 146, in train
    shuffled_y.shape[1:])
  File "/usr/local/lib/python3.6/dist-packages/rasa_core/policies/keras_policy.py", line 75, in model_architecture
    from tensorflow.keras.models import Sequential
ModuleNotFoundError: No module named 'tensorflow.keras'
```

Even though I uninstalled python 2.7 and 3.5, and then installed 3.6, `pip3` installs the `tensorflow` into `/usr/local/lib/python3.5/dist-packages`.  Is Python3.6 and `tensorflow1.8.0` incompatible? 

As a solution I replaced `tensorflow==1.8.0` with `tensorflow` and reinstalled the requirements. It worked like a charm. The newer version`tensorflow` version is 1.10.0.

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
we switched to `tf.keras`, which is a part of tensorflow>=1.10.0, so you need to upgrade to 1.10

**Comment by fade2black** [comment]
@Ghostvv , yeah, I know. I fixed that in my Docker container. I opened the issue because I guess you should update [this requirements file](https://github.com/RasaHQ/rasa_nlu/blob/master/alt_requirements/requirements_tensorflow_sklearn.txt)., that is, you should update the line `tensorflow==1.8.0`. I simply removed the version and reinstalled. It worked.

**Comment by Ghostvv** [comment]
do you mind creating a PR?

**Comment by fade2black** [comment]
@Ghostvv Of course, no problem.

**Comment by akelad** [comment]
oops sorry, i closed your PR. Could you please submit a new one changing it to `tensorflow==1.10.0`? As I mentioned in the PR, we have to pin to a version. Also please reference this issue with "fixes #issuenumber" so it gets closed automatically on merge
