### ISSUE TITLE
Problems while linking Swedish language support to Rasa?

### ISSUE THREAD

**Issue by alonsopg** [RasaHQ/rasa_nlu#1469]
Rasa NLU version: 0.13.6
OS: MacOS

**Content of model configuration file**:
```
language: 'sv'
pipeline: 
  - name: "nlp_spacy"              
  - name: "tokenizer_spacy"        
  - name: "intent_entity_featurizer_regex"
  - name: "intent_featurizer_spacy"
  - name: "ner_spacy"
  - name: "ner_crf"            
  - name: "ner_synonyms"
  - name: "intent_classifier_sklearn"
  - name: "ner_duckling"
    url: "http://0.0.0.0:8000"
    locale: "en_UK"
    dimensions: ["time"]
    timezone: "UK/London"

```

**Issue**:

How can I add Swedish language support to Rasa's NLU module? I installed this Swedish model as follows:

`user:~$ pip3 install sv_model-0.0.0.tar.gz && python3 -m spacy link sv_model sv`

Then, when I train Rasa's model:
`
user:~/duckling/migration_2/rasa-assistant$ python3 -m rasa_nlu.train -c config.yml --data data/swedish_dev/ -o models --project current --verbose`

I get the following error:
```

/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-10-15 15:43:52 INFO     rasa_nlu.utils.spacy_utils  - Trying to load spacy model with name 'sv'
2018-10-15 15:43:54 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-sv'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/duckling_extractor.py", line 108, in create_duckling_wrapper
    return DucklingWrapper(language=language)
  File "/usr/local/lib/python3.6/site-packages/duckling/wrapper.py", line 30, in __init__
    self.language = Language.convert_to_duckling_language_id(language)
  File "/usr/local/lib/python3.6/site-packages/duckling/language.py", line 60, in convert_to_duckling_language_id
    lang, ", ".join(cls.SUPPORTED_LANGUAGES)))
ValueError: Unsupported language 'sv'. Supported languages: ko$core, pt$core, da$core, fr$core, et$core, en$core, ar$core, de$core, ru$core, ja$core, id$core, zh$core, vi$core, uk$core, es$core, ga$core, it$core

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/train.py", line 184, in <module>
    num_threads=cmdline_args.num_threads)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/train.py", line 148, in do_train
    trainer = Trainer(cfg, component_builder)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/model.py", line 155, in __init__
    self.pipeline = self._build_pipeline(cfg, component_builder)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/model.py", line 166, in _build_pipeline
    component_name, cfg)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/components.py", line 441, in create_component
    cfg)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/registry.py", line 143, in create_component_by_name
    return component_clz.create(config)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/duckling_extractor.py", line 128, in create
    wrapper = cls.create_duckling_wrapper(config["language"])
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/duckling_extractor.py", line 110, in create_duckling_wrapper
    raise Exception("Duckling error. {}".format(e))
Exception: Duckling error. Unsupported language 'sv'. Supported languages: ko$core, pt$core, da$core, fr$core, et$core, en$core, ar$core, de$core, ru$core, ja$core, id$core, zh$core, vi$core, uk$core, es$core, ga$core, it$core
```
I even tried to modify Language.py:

```
class Language(object):
    """Helper class containing all supported languages
    """

    ARABIC = 'ar$core'
    DANISH = 'da$core'
    GERMAN = 'de$core'
    ENGLISH = 'en$core'
    SPANISH = 'es$core'
    ESTONIAN = 'et$core'
    FRENCH = 'fr$core'
    IRISH = 'ga$core'
    INDONESIAN = 'id$core'
    ITALIAN = 'it$core'
    JAPANESE = 'ja$core'
    KOREAN = 'ko$core'
    PORTUGUESE = 'pt$core'
    RUSSIAN = 'ru$core'
    UKRAINIAN = 'uk$core'
    VIETNAMESE = 'vi$core'
    CHINESE = 'zh$core'
    sv = 'sv$core'

    SUPPORTED_LANGUAGES = {
        ARABIC,
        DANISH,
        GERMAN,
        ENGLISH,
        SPANISH,
        ESTONIAN,
        FRENCH,
        IRISH,
        INDONESIAN,
        ITALIAN,
        JAPANESE,
        KOREAN,
        PORTUGUESE,
        RUSSIAN,
        UKRAINIAN,
        VIETNAMESE,
        CHINESE,
        sv
    } 
```

But it is not working. Any idea of how to link and use spacy swedish language model with rasa?

**Comment by akelad** [comment]
It seems the pypi package for duckling hasn't been updated to support swedish yet. I just took a look and duckling does support it, just that package hasn't been updated yet. Not sure there's much we can do about that at the moment.

**Comment by akelad** [comment]
Actually sorry, that python package is no longer maintained and neither is the clojure duckling version. The recommended component to use is `ner_duckling_http` https://rasa.com/docs/nlu/components/#ner-duckling-http
