### ISSUE TITLE
Rasa NLU : TypeError: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by Antoine31** [RasaHQ/rasa_nlu#1514]
**Rasa NLU version**: 0.14.0a1

**Operating system** (windows, osx, ...): Debian GNU/Linux 9

**Content of model configuration file**:
```yml
language: fr
pipeline: tensorflow_embedding
```

**Issue**: 
I get this error when i try to POST with postman on my NLU server :

TypeError: 'str' object does not support item assignment

**Comment by akelad** [comment]
please provide some more details, like what exactly you're  POST-ing

**Comment by Antoine31** [comment]
Here is my POST to my rasa_nlu server :

$ curl -XPOST rasa_server:5000/parse -d '{"q": "hello", "project": "my_project", "model": "my_model"}'

Still getting the error...

2018-11-12T16:17:01.085732710Z 2018-11-12 16:17:01+0000 [-] Traceback (most recent call last):
2018-11-12T16:17:01.086069219Z 2018-11-12 16:17:01+0000 [-]   File "/app/rasa_nlu/server.py", line 245, in parse
2018-11-12T16:17:01.086117620Z 2018-11-12 16:17:01+0000 [-]     self.data_router.parse, data))
2018-11-12T16:17:01.086236023Z 2018-11-12 16:17:01+0000 [-]   File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
2018-11-12T16:17:01.086395027Z 2018-11-12 16:17:01+0000 [-]     result = inContext.theWork()
2018-11-12T16:17:01.086611133Z 2018-11-12 16:17:01+0000 [-]   File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
2018-11-12T16:17:01.086716935Z 2018-11-12 16:17:01+0000 [-]     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
2018-11-12T16:17:01.086856939Z 2018-11-12 16:17:01+0000 [-]   File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
2018-11-12T16:17:01.086986242Z 2018-11-12 16:17:01+0000 [-]     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2018-11-12T16:17:01.087124546Z 2018-11-12 16:17:01+0000 [-]   File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
2018-11-12T16:17:01.087259549Z 2018-11-12 16:17:01+0000 [-]     return func(*args,**kw)
2018-11-12T16:17:01.087400453Z 2018-11-12 16:17:01+0000 [-]   File "/app/rasa_nlu/data_router.py", line 271, in parse
2018-11-12T16:17:01.087539157Z 2018-11-12 16:17:01+0000 [-]     model)
2018-11-12T16:17:01.087678760Z 2018-11-12 16:17:01+0000 [-]   File "/app/rasa_nlu/project.py", line 261, in parse
2018-11-12T16:17:01.087819164Z 2018-11-12 16:17:01+0000 [-]     interpreter = self._interpreter_for_model(model_name)
2018-11-12T16:17:01.087959468Z 2018-11-12 16:17:01+0000 [-]   File "/app/rasa_nlu/project.py", line 367, in _interpreter_for_model
2018-11-12T16:17:01.091851568Z 2018-11-12 16:17:01+0000 [-]     return Interpreter.create(metadata, self._component_builder)
2018-11-12T16:17:01.091912770Z 2018-11-12 16:17:01+0000 [-]   File "/app/rasa_nlu/model.py", line 320, in create
2018-11-12T16:17:01.092092474Z 2018-11-12 16:17:01+0000 [-]     model_metadata, **context)
2018-11-12T16:17:01.092158976Z 2018-11-12 16:17:01+0000 [-]   File "/app/rasa_nlu/components.py", line 419, in load_component
2018-11-12T16:17:01.092294880Z 2018-11-12 16:17:01+0000 [-]     cached_component, **context)
2018-11-12T16:17:01.092437683Z 2018-11-12 16:17:01+0000 [-]   File "/app/rasa_nlu/registry.py", line 134, in load_component_by_name
2018-11-12T16:17:01.092669489Z 2018-11-12 16:17:01+0000 [-]     return component_clz.load(model_dir, metadata, cached_component, **kwargs)
2018-11-12T16:17:01.092757891Z 2018-11-12 16:17:01+0000 [-]   File "/app/rasa_nlu/featurizers/count_vectors_featurizer.py", line 262, in load
2018-11-12T16:17:01.092888595Z 2018-11-12 16:17:01+0000 [-]     return utils.pycloud_unpickle(featurizer_file)
2018-11-12T16:17:01.093014598Z 2018-11-12 16:17:01+0000 [-]   File "/app/rasa_nlu/utils/__init__.py", line 325, in pycloud_unpickle
2018-11-12T16:17:01.097072003Z 2018-11-12 16:17:01+0000 [-]     return cloudpickle.load(f, encoding="latin-1")
2018-11-12T16:17:01.097173006Z 2018-11-12 16:17:01+0000 [-]   File "/usr/local/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 1044, in _make_skel_func
2018-11-12T16:17:01.097270708Z 2018-11-12 16:17:01+0000 [-]     base_globals['__builtins__'] = __builtins__
2018-11-12T16:17:01.097392111Z 2018-11-12 16:17:01+0000 [-] TypeError: 'str' object does not support item assignment

**Comment by akelad** [comment]
@EPedrotti  will get back to you about it soon.

**Comment by coreytrampe** [comment]
I was seeing that also. Bumping cloudpickle to the next minor version and rebuilding the docker image seemed to work okay for me, but then I hit another snag with it, so that's why I haven't said anything yet.

**Comment by Antoine31** [comment]
This is really boring.

I tried with other Dockerfile, latest, latest-full ...
Every time the same error...

**Comment by coreytrampe** [comment]
Why is life so boring, @Antoine31 ?

Because god hates us. Duh.

https://www.youtube.com/watch?v=9FXvAgwvi1U

**Comment by Antoine31** [comment]
Thanks for the solution, i manually install with pip cloudpickle 0.6.1 in the container then save the image.

Fucking cloudpickle.

**Comment by akelad** [comment]
ok, we just merged a fix for this :) docker containers should be updated shortly

**Comment by Antoine31** [comment]
Thank you for this, great work ! :)
