### ISSUE TITLE
Unable to load trained NLU model using Interpreter.load(model_path)

### ISSUE THREAD

**Issue by sivagnanamn** [RasaHQ/rasa_nlu#1535]
Rasa NLU version: 0.13.7 (installed through pip)
Operating system : Ubuntu 16.04
Python 3.5

Issue: Unable to load trained NLU model using Interpreter.load(model_path)

```
>>> from rasa_nlu.model import Interpreter
>>> path = "./nlu_model"
>>> model_load = Interpreter.load(path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/model.py", line 293, in load
    skip_validation)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/model.py", line 320, in create
    model_metadata, **context)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/components.py", line 419, in load_component
    cached_component, **context)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/registry.py", line 134, in load_component_by_name
    return component_clz.load(model_dir, metadata, cached_component, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/extractors/entity_synonyms.py", line 78, in load
    entity_synonyms_file = os.path.join(model_dir, file_name)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi @sivagnanamn,

Did you train this model on Rasa NLU 0.13.7 as well?  Or are you importing a previously-trained one?

**Comment by sivagnanamn** [comment]
Hi @MetcalfeTom, We tried using an already trained model. After debugging, we found out that the model was trained with Python 2.7 & loaded using Python 3.5. 

We didn't face this issue after re-training with Python 3.5.

I'll close the issue for now.

**Comment by Faysal92** [comment]
Hi @sivagnanamn , 
You wronged the path, it should be like this : model_path = "path/to/.spyder-py3/models/nlu/default/current/"
In the "current" directory you should have three files,
