### ISSUE TITLE
ImportError: cannot import name 'load_data'

### ISSUE THREAD

**Issue by rmdimran** [RasaHQ/rasa_nlu#1536]
**Rasa NLU version**: 0.11.4
**My OS :** Linux Mint 
**Python :** 3.6.5 

**Issue**:
I am getting this error with the following packages installed from requirements.txt file.

> `$ python nlu_model.py
> Traceback (most recent call last):
>  File "nlu_model.py", line 1, in <module> 
>  from rasa_nlu.training_data import load_data
> ImportError: cannot import name 'load_data'

`
```
absl-py==0.6.1
alabaster==0.7.12
apixu-client==0.0.1
APScheduler==3.3.1
astor==0.7.1
attrs==18.2.0
Automat==0.7.0
Babel==2.6.0
bleach==3.0.2
boto3==1.4.4
botocore==1.5.95
certifi==2018.10.15
chardet==3.0.4
Click==7.0
cloudpickle==0.6.1
colorclass==2.2.0
coloredlogs==7.3
colorhash==1.0.2
ConfigArgParse==0.12.0
constantly==15.1.0
cycler==0.10.0
cymem==1.31.2
cytoolz==0.8.2
decorator==4.3.0
dill==0.2.8.2
docopt==0.6.2
docutils==0.14
en-core-web-sm==1.2.0
entrypoints==0.2.3
fakeredis==0.8.2
fbmessenger==4.3.1
Flask==0.12
Flask-Cors==3.0.7
Flask-JWT-Simple==0.0.3
ftfy==4.4.3
future==0.16.0
gast==0.2.0
gevent==1.2.1
graphviz==0.7.1
greenlet==0.4.15
grpcio==1.16.1
h5py==2.7.0
html5lib==1.0.1
humanfriendly==4.17
hyperlink==18.0.0
idna==2.7
imagesize==1.1.0
incremental==17.5.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
Jinja2==2.10
jmespath==0.9.3
jsonpickle==0.9.4
jsonschema==2.6.0
jupyter-core==4.4.0
Keras==2.0.8
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
klein==17.2.0
Markdown==3.0.1
MarkupSafe==1.1.0
matplotlib==1.5.3
mattermostwrapper==2.1
mistune==0.8.4
murmurhash==0.26.4
nbconvert==5.3.1
nbformat==4.4.0
nbsphinx==0.3.5
networkx==1.11
nodejs==0.1.1
npm==0.1.1
numpy==1.13.1
optional-django==0.1.0
packaging==17.1
pandoc==1.0.0b2
pandocfilters==1.4.2
pathlib==1.0.1
pika==0.11.2
plac==0.9.6
ply==3.11
preshed==1.0.1
prompt-toolkit==1.0.14
protobuf==3.6.1
pydot==1.2.4
Pygments==2.2.0
PyHamcrest==1.9.0
PyInquirer==1.0.2
PyJWT==1.6.4
pykwalify==1.6.0
pymongo==3.7.2
pypandoc==1.4
pyparsing==2.3.0
PySocks==1.6.8
python-crfsuite==0.9.6
python-dateutil==2.7.5
python-engineio==2.3.2
python-socketio==2.0.0
python-telegram-bot==10.1.0
pytz==2018.7
PyYAML==3.13
rasa-core==0.8.2
rasa-core-sdk==0.12.1
rasa-nlu==0.11.4
redis==2.10.5
regex==2017.4.5
requests==2.14.2
requests-toolbelt==0.8.0
rocketchat-API==0.6.22
ruamel.yaml==0.15.34
s3transfer==0.1.13
scikit-learn==0.19.1
scipy==1.1.0
simplejson==3.11.1
six==1.10.0
sklearn-crfsuite==0.3.5
slackclient==1.3.0
snowballstemmer==1.2.1
spacy==1.8.2
Sphinx==1.8.2
sphinxcontrib-websupport==1.1.0
tabulate==0.8.2
tensorboard==1.10.0
tensorflow==1.10.0
termcolor==1.1.0
terminaltables==3.1.0
testpath==0.4.2
thinc==6.5.2
toolz==0.9.0
tqdm==4.11.2
traitlets==4.3.2
twilio==6.19.2
Twisted==18.9.0
typing==3.5.3.0
tzlocal==1.5.1
ujson==1.35
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
webexteamssdk==1.0.3
websocket-client==0.54.0
Werkzeug==0.14.1
wrapt==1.10.11
zope.interface==4.6.0

```

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by rmdimran** [comment]
Issue resolved in conda environment. 
Thanks.

**Comment by meghnasmhs** [comment]
Rasa NLU version: 0.11.4
My OS : windows 10
Python : 3.6.6

Issue:Traceback (most recent call last):
  File "nlu_model.py", line 1, in <module>
    from rasa_nlu.training_data import load_data
ImportError: cannot import name 'load_data'



I am experiencing the same issue

**Comment by wochinge** [comment]
@meghnasmhs That's quite an old version. Please try with the latest.

**Comment by nohumandotin** [comment]
![image](https://user-images.githubusercontent.com/48850523/60763964-81ac7600-a04d-11e9-9c9d-faec5adbd2f0.png)
version: 0.15.1

**Comment by nohumandotin** [comment]
Please help me to solve this issue.

**Comment by wochinge** [comment]
Can you please ask the question in the forum? Seems like it's an issue in your custom code.

**Comment by Yattus** [comment]
The output of grep commande:
**grep --color 'load_data' ./env/lib/python3.8/site-packages/rasa/nlu/***

grep: ./env/lib/python3.8/site-packages/rasa/nlu/classifiers: est un dossier
./env/lib/python3.8/site-packages/rasa/nlu/convert.py:        td = rasa.shared.nlu.training_data.loading.load_data(data_file, language)
./env/lib/python3.8/site-packages/rasa/nlu/convert.py:        td = rasa.shared.nlu.training_data.loading.load_data(data_file, language)
grep: ./env/lib/python3.8/site-packages/rasa/nlu/emulators: est un dossier
grep: ./env/lib/python3.8/site-packages/rasa/nlu/extractors: est un dossier
grep: ./env/lib/python3.8/site-packages/rasa/nlu/featurizers: est un dossier
grep: ./env/lib/python3.8/site-packages/rasa/nlu/__pycache__: est un dossier
grep: ./env/lib/python3.8/site-packages/rasa/nlu/selectors: est un dossier
./env/lib/python3.8/site-packages/rasa/nlu/test.py:    test_data = rasa.shared.nlu.training_data.loading.load_data(
grep: ./env/lib/python3.8/site-packages/rasa/nlu/tokenizers: est un dossier
grep: ./env/lib/python3.8/site-packages/rasa/nlu/training_data: est un dossier
./env/lib/python3.8/site-packages/rasa/nlu/train.py:from rasa.shared.nlu.training_data.loading import load_data
./env/lib/python3.8/site-packages/rasa/nlu/train.py:async def load_data_from_endpoint(
./env/lib/python3.8/site-packages/rasa/nlu/train.py:        training_data = load_data(temp_data_file, language)
./env/lib/python3.8/site-packages/rasa/nlu/train.py:        training_data = await load_data_from_endpoint(
./env/lib/python3.8/site-packages/rasa/nlu/train.py:        training_data = load_data(data, nlu_config.language)
grep: ./env/lib/python3.8/site-packages/rasa/nlu/utils: est un dossier

**Solution:**
`from rasa.shared.nlu.training_data.loading import load_data`
