### ISSUE TITLE
Unknown Locale: UTF-8 Error

### ISSUE THREAD

**Issue by jahirfiquitiva** [RasaHQ/rasa_nlu#1583]
**Rasa NLU version**: `0.13.8`

**Operating system** (windows, osx, ...): MacOS Mojave

**Content of model configuration file**:
```yml
language: "en"

pipeline: spacy_sklearn
```

**Issue**:

Hello...

I am trying to run this project, but all I get is this error... Can you guide me on how to fix it, please?

Thanks in advance.

```gradle
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/train.py", line 177, in <module>
    do_train(config.load(cmdline_args.config),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/config.py", line 51, in load
    return RasaNLUModelConfig(file_config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/config.py", line 106, in __init__
    from rasa_nlu import registry
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/registry.py", line 30, in <module>
    from rasa_nlu.extractors.crf_entity_extractor import CRFEntityExtractor
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/extractors/crf_entity_extractor.py", line 20, in <module>
    import spacy
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/cli/download.py", line 11, in <module>
    from .link import link
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/cli/link.py", line 9, in <module>
    from ..util import prints
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/util.py", line 8, in <module>
    import regex as re
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/regex.py", line 683, in <module>
    _pattern_type = type(_compile("", 0, {}))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/regex.py", line 436, in _compile
    pattern_locale = _getlocale()[1]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
make: *** [train-nlu] Error 1
```

**Comment by jahirfiquitiva** [comment]
Fixed it by following [this guide](https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python)
