### ISSUE TITLE
Unable to store models in AWS

### ISSUE THREAD

**Issue by sandy130794** [RasaHQ/rasa_nlu#1613]
**Rasa NLU version**:
0.14.0a1

**Operating system** (windows, osx, ...):
Ubuntu

**Content of model configuration file**:
```
##### I am using json format for config.

{
  "pipeline": "spacy_sklearn",
  "storage": "aws",
  "AWS_SECRET_ACCESS_KEY": "secret_access_key",
  "AWS_ACCESS_KEY_ID": "access_key",
  "AWS_DEFAULT_REGION": "us-west-1",
  "BUCKET_NAME": "mybucket",
  "AWS_ENDPOINT_URL": "apigateway.us-west-1.amazonaws.com"
}

##### This is my yml config file. I Don't know how to give AWS environment variables in yml format config file.
pipeline:
 - name: "nlp_spacy"
 - name: "tokenizer_spacy"
 - name: "ner_duckling"
   dimensions: ["time", "phone-number", "url", "email"]
 - name: "ner_crf"
 - name: "ner_synonyms"
 - name: "intent_featurizer_count_vectors"
 - name: "intent_classifier_tensorflow_embedding"
   intent_tokenization_flag: true
   intent_split_symbol: ","

```
##### What I am trying to do is, storing my models into AWS s3 using this command:
python -m rasa_nlu.server -c config/sample_aws_config.json --storage aws --path /models/

##### What I am trying to achieve is when I start training my model. The model has to be created and it has to be stored directly in the AWS Bucket but not in the local. Is it possible? 

**Issue**:
2019-01-10 17:23:59 ERROR    rasa_nlu.data_router - Failed to list projects. Make sure you have correctly configured your cloudstorage settings.
Traceback (most recent call last):
  File "/rasa_nlu/data_router.py", line 205, in _list_projects_in_cloud
    p = get_persistor(self.remote_storage)
  File "/rasa_nlu/persistor.py", line 28, in get_persistor
    os.environ.get("apigateway.us-west-1.amazonaws.com"))
  File "/rasa_nlu/persistor.py", line 147, in __init__
    self._ensure_bucket_exists(bucket_name)
  File "/rasa_nlu/persistor.py", line 181, in _ensure_bucket_exists
    CreateBucketConfiguration=bucket_config)
  File "/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/lib/python3.6/site-packages/botocore/client.py", line 324, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/lib/python3.6/site-packages/botocore/client.py", line 596, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/lib/python3.6/site-packages/botocore/client.py", line 629, in _convert_to_request_dict
    api_params, operation_model, context)
  File "/lib/python3.6/site-packages/botocore/client.py", line 658, in _emit_api_params
    params=api_params, model=operation_model, context=context)
  File "/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/lib/python3.6/site-packages/botocore/handlers.py", line 222, in validate_bucket_name
    if VALID_BUCKET.search(bucket) is None:
TypeError: expected string or bytes-like object
2019-01-10 17:24:00 WARNING  rasa_nlu.project - Failed to list models of project tester. expected string or bytes-like object

Please Help me with is issue.....

**Comment by wochinge** [comment]
@sandy130794 Why can you not set the environment variables?

**Comment by sandy130794** [comment]
@wochinge  Actually I want to know, how to give environment variable to yml format config file.
 where as in json format config file I gave the AWS credentials. But it is throwing the above issue.

You asked me for more-information-needed. Can you please tell me specifically which and what kind of information do you needed.

**Comment by sandy130794** [comment]
What I am trying to achieve is when I start training my model. The model has to be created and it has to be stored directly in the AWS Bucket but not in the local. Is it possible?

**Comment by sandy130794** [comment]
@wochinge 
Did you follow the guide here? So did you start nlu with the storage flag set to aws and provide the credentials through environment variables? --> Yes

**Comment by wochinge** [comment]
These lines 

```
File "/rasa_nlu/persistor.py", line 28, in get_persistor
os.environ.get("apigateway.us-west-1.amazonaws.com"))
```

in your stack trace seem awkward. Did you change some code in `persistor.py`?

And did you set the environment variables `BUCKET_NAME` and `AWS_ENDPOINT_URL` as I posted in my previous post?

**Comment by careless25** [comment]
@sandy130794 your `AWS_ENDPOINT_URL` should be `https://s3.amazonaws.com/`
