### ISSUE TITLE
"error": "unsupported pickle protocol: 3"

### ISSUE THREAD

**Issue by goingeast** [RasaHQ/rasa_nlu#1680]
**Rasa NLU version**: 0.14.2

**Operating system**:Mac OSX

**Content of model configuration file**:
```yml
language: "en"
pipeline: spacy_sklearn
```
Python: 2.7.13

**Issue**: When post request, got error from server:
{
  "error": "unsupported pickle protocol: 3"
}

2019-01-31 17:44:23-0800 [-] 2019-01-31 17:44:23 ERROR    __main__  - unsupported pickle protocol: 3
2019-01-31 17:44:23-0800 [-] Traceback (most recent call last):
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/rasa_nlu/server.py", line 257, in parse
2019-01-31 17:44:23-0800 [-]     self.data_router.parse, data))
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
2019-01-31 17:44:23-0800 [-]     result = inContext.theWork()
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
2019-01-31 17:44:23-0800 [-]     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
2019-01-31 17:44:23-0800 [-]     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
2019-01-31 17:44:23-0800 [-]     return func(*args,**kw)
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/rasa_nlu/data_router.py", line 272, in parse
2019-01-31 17:44:23-0800 [-]     model)
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/rasa_nlu/project.py", line 265, in parse
2019-01-31 17:44:23-0800 [-]     interpreter = self._interpreter_for_model(model_name)
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/rasa_nlu/project.py", line 371, in _interpreter_for_model
2019-01-31 17:44:23-0800 [-]     return Interpreter.create(metadata, self._component_builder)
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/rasa_nlu/model.py", line 320, in create
2019-01-31 17:44:23-0800 [-]     model_metadata, **context)
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/rasa_nlu/components.py", line 419, in load_component
2019-01-31 17:44:23-0800 [-]     cached_component, **context)
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/rasa_nlu/registry.py", line 133, in load_component_by_name
2019-01-31 17:44:23-0800 [-]     return component_clz.load(model_dir, metadata, cached_component, **kwargs)
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/rasa_nlu/extractors/crf_entity_extractor.py", line 371, in load
2019-01-31 17:44:23-0800 [-]     ent_tagger = joblib.load(model_file)
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 598, in load
2019-01-31 17:44:23-0800 [-]     obj = _unpickle(fobj, filename, mmap_mode)
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 526, in _unpickle
2019-01-31 17:44:23-0800 [-]     obj = unpickler.load()
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/pickle.py", line 864, in load
2019-01-31 17:44:23-0800 [-]     dispatch[key](self)
2019-01-31 17:44:23-0800 [-]   File "/Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/pickle.py", line 892, in load_proto
2019-01-31 17:44:23-0800 [-]     raise ValueError, "unsupported pickle protocol: %d" % proto
2019-01-31 17:44:23-0800 [-] ValueError: unsupported pickle protocol: 3

**Comment by goingeast** [comment]
use the python3 trained model.
