### ISSUE TITLE
Rasa Installation issue

### ISSUE THREAD

**Issue by gargrishabh2** [RasaHQ/rasa_nlu#1725]
**Rasa NLU version**:

**Operating system** (windows, osx, ...): Windows 7

**Issue**: While installing rasa using **pip install rasa_nlu**
I got an error:
Installing collected packages: requests, packaging, scikit-learn, tqdm, cloudpic
kle, ruamel.yaml, future, jmespath, botocore, s3transfer, boto3, rasa-nlu
  Found existing installation: requests 2.18.4
    Uninstalling requests-2.18.4:
Exception:
Traceback (most recent call last):
  **File "C:\ProgramData\Anaconda3\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
PermissionError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib
\\site-packages\\requests' -> 'C:\\Users\\1256868\\AppData\\Local\\Temp\\pip-eet
2bwmd-uninstall\\programdata\\anaconda3\\lib\\site-packages\\requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\basecommand.py", line 215
, in main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\commands\install.py", lin
e 342, in run
    prefix=options.prefix_path,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 778
, in install
    requirement.uninstall(auto_confirm=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_install.py", line
 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_uninstall.py", li
ne 115, in remove
    renames(path, new_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\utils\__init__.py", line
267, in renames
    shutil.move(old, new)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 556, in move
    rmtree(src)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib
\\site-packages\\requests\\adapters.py'**

I have admin access on my PC. I am using Anaconda in admin mode. I have python version 3.6
I have Visual C++ Redistributable 2015 version.
I am trying to solve it from 10 days. Please help me in this.

**Comment by akelad** [comment]
Looks like there's some write access problems even if you have admin access. This seems to be a general Windows problem though, rather than Rasa specific. I'd suggest checking stackoverflow to see if people have experienced similar problems
