### ISSUE TITLE
Getting this error when I am trying to train the nlu_model

### ISSUE THREAD

**Issue by Nikhileshorg** [RasaHQ/rasa_nlu#1745]
from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUModelConfig
from rasa_nlu.model import Trainer
from rasa_nlu import config

def train_nlu(data, config, model_dir):
    training_data = load_data(data)
    trainer = Trainer(RasaNLUModelConfig(config))
    trainer.train(training_data)
    model_directory = trainer.persist(model_dir, fixed_model_name = 'weathernlu')

if __name__ == '__main__':
    train_nlu('./data/data.json','config_spacy.json','./models/nlu')

_____________________________________________________________________________________________________________
I am getting this error.
____________________________________________________________________________________________________________
Traceback (most recent call last):
  File "nlu_model.py", line 12, in <module>
    train_nlu('./data/data.json', 'config_spacy.json', './models/nlu')
  File "nlu_model.py", line 7, in train_nlu
    trainer = Trainer(RasaNLUModelConfig(config))
NameError: name 'config' is not defined 
_______________________________________________________________________________________________________
When I am using this way : 

from rasa_nlu.training_data import load_data
from rasa_nlu import config
from rasa_nlu.model import Trainer
from rasa_nlu.model import Metadata, Interpreter

def train_nlu(data, configs, model_dir):
	training_data = load_data(data)
	trainer = Trainer(config.load(configs))
	trainer.train(training_data)
	model_directory = trainer.persist(model_dir, fixed_model_name = 'weathernlu')
	

if __name__ == '__main__':
	train_nlu('./data/data.json', 'config_spacy.json', './models/nlu')
	________________________________________________________________________________
I am getting this error
____________________________________________________________________________________
raceback (most recent call last):
  File "nlu_model.py", line 14, in <module>
    train_nlu('./data/data.json', 'config_spacy.json', './models/nlu')
  File "nlu_model.py", line 8, in train_nlu
    trainer = Trainer(config.load(configs))
  File "C:\Users\kastu\AppData\Roaming\Python\Python36\site-packages\rasa_nlu\config.py", line 44, in load
    file_config = utils.read_yaml_file(filename)
  File "C:\Users\kastu\AppData\Roaming\Python\Python36\site-packages\rasa_nlu\utils\__init__.py", line 283, in read_yaml_file
    return read_yaml(read_file(filename, "utf-8"))
  File "C:\Users\kastu\AppData\Roaming\Python\Python36\site-packages\rasa_nlu\utils\__init__.py", line 274, in read_yaml
    return yaml_parser.load(content)
  File "C:\Users\kastu\AppData\Roaming\Python\Python36\site-packages\ruamel\yaml\main.py", line 266, in load
    return constructor.get_single_data()
  File "C:\Users\kastu\AppData\Roaming\Python\Python36\site-packages\ruamel\yaml\constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node (ext/_ruamel_yaml.c:9612)
  File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document (ext/_ruamel_yaml.c:9922)
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node (ext/_ruamel_yaml.c:10814)
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node (ext/_ruamel_yaml.c:12609)
  File "_ruamel_yaml.pyx", line 731, in _ruamel_yaml.CParser._compose_node (ext/_ruamel_yaml.c:10027)
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event (ext/_ruamel_yaml.c:12818)
ruamel.yaml.scanner.ScannerError: while scanning a quoted scalar
  in "<unicode string>", line 4, column 12
found unexpected end of stream
  in "<unicode string>", line 6, column 1

**Comment by akelad** [comment]
Thanks for raising this issue, @paulaWesselmann  will get back to you about it soon.

**Comment by paulaWesselmann** [comment]
@Nikhileshorg which NLU version are you using? The newer versions require .yml files instead of .json. Can you please report back the content of your model configuration file if this doesn't fix your issue?

**Comment by Nikhileshorg** [comment]
I have installed  rasa-nlu-0.11.5 version. I am storing the following code in .py file.
------------------------------------------------------------------------
from rasa_nlu.training_data import load_data
from rasa_nlu.converters import load_data
from rasa_nlu.config import RasaNLUConfig
from rasa_nlu.model import Trainer

def train_nlu(data, configs, model_dir):
	training_data = load_data(data)
	trainer = Trainer(RasaNLUConfig(config))
	trainer.train(training_data)
	model_directory = trainer.persist(model_dir, fixed_model_name = 'weathernlu')
	

if __name__ == '__main__':
	train_nlu('./data/data.json', 'config_spacy.json', './models/nlu')
	
I am using the following code for nlu training of my weather chatbot.

--------------------------------------------------------------------------------------
I am getting this error.

Traceback (most recent call last):
  File "nlu_model.py", line 2, in <module>
    from rasa_nlu.converters import load_data
ModuleNotFoundError: No module named 'rasa_nlu.converters'
-----------------------------------------------------------------------------

As @stacybot123 used the following code, I tried using it.
When I used 1066 as a reference for my issue and used the following :

-------------------------------------------------------------------------------
from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUModelConfig
from rasa_nlu.model import Trainer
from rasa_nlu import config

training_data = load_data('./data/data.json')
trainer = Trainer(config.load('config_spacy.json'))
trainer.train(training_data)
model_directory = trainer.persist('./models/nlu' , fixed_model_name = 'myfirstbot')
interpreter = Interpreter.load('./models/nlu/default/myfirstbot')
--------------------------------------------------------------------------------------------------
I am getting this error
--------------------------------------------------------------------------------------
Traceback (most recent call last):
File "C:\Users\kastu\AppData\Roaming\Python\Python36\site-packages\rasa_nlu\utils__init__.py", line 264, in read_yaml
return yaml_parser.load(content)
File "C:\Users\kastu\AppData\Roaming\Python\Python36\site-packages\ruamel\yaml\main.py", line 266, in load
return constructor.get_single_data()
File "C:\Users\kastu\AppData\Roaming\Python\Python36\site-packages\ruamel\yaml\constructor.py", line 102, in get_single_data
node = self.composer.get_single_node()
File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node (ext/_ruamel_yaml.c:9612)
File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document (ext/_ruamel_yaml.c:9922)
File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node (ext/_ruamel_yaml.c:10814)
File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node (ext/_ruamel_yaml.c:12609)
File "_ruamel_yaml.pyx", line 731, in _ruamel_yaml.CParser._compose_node (ext/_ruamel_yaml.c:10027)
File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event (ext/_ruamel_yaml.c:12818)
ruamel.yaml.scanner.ScannerError: while scanning a quoted scalar
in "", line 4, column 12
found unexpected end of stream
in "", line 6, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "nlu_model.py", line 7, in 
trainer = Trainer(config.load('config_spacy.json'))
File "C:\Users\kastu\AppData\Roaming\Python\Python36\site-packages\rasa_nlu\config.py", line 44, in load
file_config = utils.read_yaml_file(filename)
File "C:\Users\kastu\AppData\Roaming\Python\Python36\site-packages\rasa_nlu\utils__init__.py", line 283, in read_yaml_file
return read_yaml(read_file(filename, "utf-8"))
File "C:\Users\kastu\AppData\Roaming\Python\Python36\site-packages\rasa_nlu\utils__init__.py", line 274, in read_yaml
return yaml_parser.load(content)
File "C:\Users\kastu\AppData\Roaming\Python\Python36\site-packages\ruamel\yaml\main.py", line 266, in load
return constructor.get_single_data()
File "C:\Users\kastu\AppData\Roaming\Python\Python36\site-packages\ruamel\yaml\constructor.py", line 102, in get_single_data
node = self.composer.get_single_node()
File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node (ext/_ruamel_yaml.c:9612)
File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document (ext/_ruamel_yaml.c:9922)
File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node (ext/_ruamel_yaml.c:10814)
File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node (ext/_ruamel_yaml.c:12609)
File "_ruamel_yaml.pyx", line 731, in _ruamel_yaml.CParser._compose_node (ext/_ruamel_yaml.c:10027)
File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event (ext/_ruamel_yaml.c:12818)
ruamel.yaml.scanner.ScannerError: while scanning a quoted scalar
in "", line 4, column 12
found unexpected end of stream
in "", line 6, column 1

Please help me with this error.

**Comment by paulaWesselmann** [comment]
Your version is out of date and not supported anymore. You are probably best of updating to a new version. Have a look here: https://rasa.com/docs/nlu/migrations/

**Comment by Nikhileshorg** [comment]
As you told I have updated the rasa-nlu version. But when I am trying to train the model. I am getting the same error.  Using this version of rasa-nlu - 0.15.0a2

I have created a nlu_model.py and saved the following code which I am using to train the model. Please help me with this one. Struck at it from few days.

from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUModelConfig
from rasa_nlu.model import Trainer
from rasa_nlu import config

def train_nlu(data, config_file, model_dir):
    training_data = load_data(data)
    trainer = Trainer(config.load(config_file))
    trainer.train(training_data)
    model_directory = trainer.persist(model_dir, fixed_model_name = 'weathernlu')
	
if __name__ == '__main__':
    train_nlu('./data/data.json','config_spacy.json','./models/nlu')
	------------------------------------------------------------------------------------------------
Getting this error
---------------------------------------------------------------

Traceback (most recent call last):
  File "c:\users\kastu\chatbot\data\rasa_nlu\rasa_nlu\utils\__init__.py", line 249, in read_yaml
    return yaml_parser.load(content)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\main.py", line 331, in load
    return constructor.get_single_data()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\constructor.py", line 106, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 731, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.scanner.ScannerError: while scanning a quoted scalar
  in "<unicode string>", line 4, column 12
found unexpected end of stream
  in "<unicode string>", line 6, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nlu_model.py", line 13, in <module>
    train_nlu('./data/data.json','config_spacy.json','./models/nlu')
  File "nlu_model.py", line 8, in train_nlu
    trainer = Trainer(config.load(config_file))
  File "c:\users\kastu\chatbot\data\rasa_nlu\rasa_nlu\config.py", line 36, in load
    file_config = utils.read_yaml_file(filename)
  File "c:\users\kastu\chatbot\data\rasa_nlu\rasa_nlu\utils\__init__.py", line 268, in read_yaml_file
    return read_yaml(read_file(filename, "utf-8"))
  File "c:\users\kastu\chatbot\data\rasa_nlu\rasa_nlu\utils\__init__.py", line 259, in read_yaml
    return yaml_parser.load(content)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\main.py", line 331, in load
    return constructor.get_single_data()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\constructor.py", line 106, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 731, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.scanner.ScannerError: while scanning a quoted scalar
  in "<unicode string>", line 4, column 12
found unexpected end of stream
  in "<unicode string>", line 6, column 1

**Comment by nohumandotin** [comment]
![image](https://user-images.githubusercontent.com/48850523/60763387-781d1100-a041-11e9-9fa0-1c016d284503.png)

**Comment by nohumandotin** [comment]
Please help me to solve this
