### ISSUE TITLE
IMPORT ERROR FROM RASA

### ISSUE THREAD

**Issue by Robertjbc** [RasaHQ/rasa_nlu#1751]
hello rasa friends i have a issue , i recently update the rasa how normaly i do when i check the rasa docs web the issue is when i tried to train a bot or activate it, it send me a error what does it say:
 

`C:\Users\capitalminds\Desktop\prueba 3>py -m rasa_core.train  interactive -o models/dialogue  -d domain.yml -s stories.md
Processed Story Blocks: 100%|████████████████████████████████████████████████████| 13/13 [00:00<?, ?it/s, # trackers=1]
Processed Story Blocks: 100%|██████████████████████████████████████████| 13/13 [00:00<00:00, 416.69it/s, # trackers=13]
Processed Story Blocks: 100%|██████████████████████████████████████████| 13/13 [00:00<00:00, 138.65it/s, # trackers=38]
Processed Story Blocks: 100%|██████████████████████████████████████████| 13/13 [00:00<00:00, 138.60it/s, # trackers=30]
2019-03-01 11:46:41.510388: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\train.py", line 356, in <module>
    additional_args)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\train.py", line 328, in do_interactive_learning
    additional_arguments)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\train.py", line 190, in train_dialogue_model
    agent.train(training_data, **kwargs)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 520, in train
    **kwargs)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\policies\ensemble.py", line 63, in train
    policy.train(training_trackers, domain, **kwargs)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\policies\keras_policy.py", line 162, in train
    shuffled_y.shape[1:])
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\policies\keras_policy.py", line 93, in model_architecture
    from tensorflow.keras.models import Sequential
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\keras\__init__.py", line 20, in <module>
    from tensorflow.keras import layers
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\keras\layers\__init__.py", line 8, in <module>
    from tensorflow.python.estimator.keras import Layer
ImportError: cannot import name 'Layer'`

so i really need to fix this error

regards 😉

**Comment by akelad** [comment]
Please fill out the issue template

**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:



**Content of domain file** (if used & relevant):
```yaml

```

Also, which tensorflow version do you have installed?

**Comment by Robertjbc** [comment]
rasa core version: 0.13.2

python version: 3.6 
 
operating system windows 

the tensorflow version i don´t remember but it´s the version for default when you install rasa core for pip

**Comment by akelad** [comment]
can you please run `pip show tensorflow`? because it looks like it's not the correct version of tensorflow

**Comment by Robertjbc** [comment]
hello akelad thanks for yours answers the error it solved itself, i think how i update the rasa_core and nlu to the 0.13.3 it solve

thank for your attention 
regards 
😉

**Comment by Robertjbc** [comment]
hey there the rasa give me a error when i tried to connect to one of recomended chat plataform `
C:\Users\capitalminds\Desktop\prueba 4>py -m rasa_core.run  --core models/dialogue  --nlu models/current/nlu    --endpoints endpoints.yml --credentials credentials.yml
2019-03-07 16:39:47 INFO     root  - Rasa process starting
2019-03-07 16:39:47.344703: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
INFO:tensorflow:Restoring parameters from models/current/nlu\intent_classifier_tensorflow_embedding.ckpt
2019-03-07 16:39:47 INFO     tensorflow  - Restoring parameters from models/current/nlu\intent_classifier_tensorflow_embedding.ckpt
Traceback (most recent call last):
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\run.py", line 260, in <module>
    cmdline_args.jwt_method)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\run.py", line 190, in serve_application
    input_channels = create_http_input_channels(channel, credentials_file)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\run.py", line 103, in create_http_input_channels
    all_credentials = read_yaml_file(credentials_file)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\utils.py", line 316, in read_yaml_file
    return read_yaml_string(read_file(filename))
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\utils.py", line 327, in read_yaml_string
    return yaml_parser.load(string)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\ruamel\yaml\main.py", line 331, in load
    return constructor.get_single_data()
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\ruamel\yaml\constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 891, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.scanner.ScannerError: mapping values are not allowed in this context
  in "<unicode string>", line 6, column 24`

i uninstall rasa and reinstall and the error 
persists

**Comment by akelad** [comment]
I think this is something to do with the format of your credentials file, can you make sure it's formatted correctly?

**Comment by Robertjbc** [comment]
let me try it,

**Comment by Robertjbc** [comment]
i´ll fix it its a problem from the credentials.yml thanks for yours  ansewers 

regards 😉
