### ISSUE TITLE
Not able to train the model

### ISSUE THREAD

**Issue by Nikhileshorg** [RasaHQ/rasa_nlu#1752]
As you told in issue #1745, I have updated the rasa-nlu version. But when I am trying to train the model. I am getting the same error. Using this version of rasa-nlu - 0.15.0a2. 

I have created a nlu_model.py and saved the following code which I am using to train the model. Please help me with this one. Struck at it from few days.

from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUModelConfig
from rasa_nlu.model import Trainer
from rasa_nlu import config

def train_nlu(data, config_file, model_dir):
training_data = load_data(data)
trainer = Trainer(config.load(config_file))
trainer.train(training_data)
model_directory = trainer.persist(model_dir, fixed_model_name = 'weathernlu')

if name == 'main':
train_nlu('./data/data.json','config_spacy.json','./models/nlu')

------------------------------------------------------------------------------------------------
Getting this error
___________________________________________________________________________________________
Traceback (most recent call last):
File "c:\users\kastu\chatbot\data\rasa_nlu\rasa_nlu\utils_init_.py", line 249, in read_yaml
return yaml_parser.load(content)
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\main.py", line 331, in load
return constructor.get_single_data()
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\constructor.py", line 106, in get_single_data
node = self.composer.get_single_node()
File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document
File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
File "_ruamel_yaml.pyx", line 731, in _ruamel_yaml.CParser._compose_node
File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.scanner.ScannerError: while scanning a quoted scalar
in "", line 4, column 12
found unexpected end of stream
in "", line 6, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "nlu_model.py", line 13, in 
train_nlu('./data/data.json','config_spacy.json','./models/nlu')
File "nlu_model.py", line 8, in train_nlu
trainer = Trainer(config.load(config_file))
File "c:\users\kastu\chatbot\data\rasa_nlu\rasa_nlu\config.py", line 36, in load
file_config = utils.read_yaml_file(filename)
File "c:\users\kastu\chatbot\data\rasa_nlu\rasa_nlu\utils_init_.py", line 268, in read_yaml_file
return read_yaml(read_file(filename, "utf-8"))
File "c:\users\kastu\chatbot\data\rasa_nlu\rasa_nlu\utils_init_.py", line 259, in read_yaml
return yaml_parser.load(content)
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\main.py", line 331, in load
return constructor.get_single_data()
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\constructor.py", line 106, in get_single_data
node = self.composer.get_single_node()
File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document
File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
File "_ruamel_yaml.pyx", line 731, in _ruamel_yaml.CParser._compose_node
File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.scanner.ScannerError: while scanning a quoted scalar
in "", line 4, column 12
found unexpected end of stream
in "", line 6, column 1

**Comment by erohmensing** [comment]
Hi @Nikhileshorg, the `config_file` you're passing to `config.load()` is a .json file. You'll notice in the traceback that this loading involves `read_yaml()` -- as @paulaWesselmann mentioned in your last issue, the newer versions of Rasa NLU do not support .json formatted nlu config files, but rather require .yml files. Info on how to configure the spacy yaml can be found here: https://rasa.com/docs/nlu/components/#nlp-spacy
