### ISSUE TITLE
python -m spacy download en_core_web_md   give the below error

### ISSUE THREAD

**Issue by tiwo19** [RasaHQ/rasa_nlu#1784]
**Rasa NLU version**:

**Operating system** (windows, 10...):

**Content of model configuration file**:
```yml

```

i get this error when i run  python -m spacy download en_core_web_md  in anaconda prompt
(base) C:\Users\damipe>python -m spacy download en_core_web_md
Traceback (most recent call last):
  File "C:\Users\damipe\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\damipe\Anaconda3\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\damipe\Anaconda3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\damipe\Anaconda3\lib\site-packages\spacy\__init__.py", line 8, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "C:\Users\damipe\Anaconda3\lib\site-packages\thinc\neural\__init__.py", line 1, in <module>
    from ._classes.model import Model
  File "C:\Users\damipe\Anaconda3\lib\site-packages\thinc\neural\_classes\model.py", line 2, in <module>
    from numpy import prod
  File "C:\Users\damipe\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\damipe\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py", line 35, in <module>
    from . import _internal  # for freeze programs
  File "C:\Users\damipe\AppData\Roaming\Python\Python37\site-packages\numpy\core\_internal.py", line 13, in <module>
    from numpy.core.overrides import set_module
  File "C:\Users\damipe\AppData\Roaming\Python\Python37\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
 can anyone help quickly

**Comment by mauricedoepke** [comment]
This is not a problem of rasa but of your python environment.
[Upgrading numpy might help](https://github.com/alpacahq/pylivetrader/issues/73)

**Comment by akelad** [comment]
Yep, @mauricedoepke solution sounds right. Since you're trying to download a spacy model though, please create an issue on their repository if you're still having issues :)

**Comment by tiwo19** [comment]
ok i will then thank you for comments

**Comment by tiwo19** [comment]
I upgraded numpy and didnt work
