### ISSUE TITLE
ModuleNotFoundError: No module named 'pypandoc'

### ISSUE THREAD

**Issue by LawnboyMax** [RasaHQ/rasa_nlu#1872]
**Rasa Core version**:
Trying to install latest `rasa_core` (0.7.9) in a fresh virtualenv
**Python version**: 
Python 3.6.1
**Operating system** (windows, osx, ...):
Windows 10
**Issue**:
Trying to install latest `rasa_core` in a fresh virtualenv. Get this error when running `pip install rasa_core`:

```
(env) C:\Users\user\Desktop\projects\rasa_project>pip install rasa_core
Collecting rasa_core
  Using cached rasa_core-0.7.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Users\user\AppData\Local\Temp\pip-build-b55h3weg\rasa-core\setup.py", line 9, in <module>
        import pypandoc
    ModuleNotFoundError: No module named 'pypandoc'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-build-b55h3weg\rasa-core\setup.py", line 12, in <module>
        readme = open('README.md').read()
      File "c:\users\user\desktop\projects\rasa_project\env\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 882: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-build-b55h3weg\rasa-core\
```

**Comment by TheresaSchmidt** [comment]
The problem still exists. I tried with Python 3.8.3 and pip 20.3.3
With Python 3.7.9 an pip 19, the isntall worked.

**Comment by tttthomasssss** [comment]
Sb on Stackoverflow appears to have the same problem: https://stackoverflow.com/questions/65679912/im-trying-to-install-rasa-and-came-up-with-this-error-can-anyone-please-help-m
