### ISSUE TITLE
Rasa Core HTTP Server not working - Expecting Value

### ISSUE THREAD

**Issue by atotalnoob** [RasaHQ/rasa_nlu#1936]
**Rasa Core version**: 0.8.2, Rasa NLU 0.11.3

**Python version**: 3.6, Anaconda version 5.0.1

**Operating system** (windows, osx, ...): Windows Server 2012 R2 Standard

**Issue**:

Hi all!

I followed the instructions to the letter on the documentation, but I get an error when trying to run Rasa Core HTTP Server. I know the server is working, when I go to localhost:5005, I get a message that says "hello from Rasa Core: 0.8.2" I can also see that the requests are being recieved by the server. 

Steps I took (all using example data):
- Trained new model with Rasa NLU
- Ran server, only changed the inputs to points to my location of models. 
- Checked XPOST  with cURL on server (error below)
- Checked XPOST  with cURL on desktop (Windows 7) (Error below)
- Checked XPOST with RestSharp (error below)
- Running anaconda as admin

Whenever I try to test it I get this error. I also tried from another computer and the same issue presented itself. I ran anaconda prompt as admin. The server logs are empty or I would post them.

Server output:
`
```
(base) C:\Windows\system32>cd /

(base) C:\>cd rasa-bot

(base) C:\rasa-bot>cd rasa_core-master

(base) C:\rasa-bot\rasa_core-master>python -m rasa_core.server -d models/dialogu
e -u examples/moodbot/data/current -o out.log
:0: UserWarning: You do not have a working installation of the service_identity
module: 'No module named 'service_identity''.  Please install it from <https://p
ypi.python.org/pypi/service_identity> and make sure all of its dependencies are
satisfied.  Without the service_identity module, Twisted can perform only rudime
ntary TLS client hostname verification.  Many valid certificate/hostname mapping
s may be rejected.
Using TensorFlow backend.
2018-02-20 09:59:38.240854: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\te
nsorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions
that this TensorFlow binary was not compiled to use: AVX
2018-02-20 09:59:57-0500 [-] Log opened.
2018-02-20 09:59:57-0500 [-] Site starting on 5005
2018-02-20 09:59:57-0500 [-] Starting factory <twisted.web.server.Site object at
 0x000000A995470EF0>
2018-02-20 10:00:35-0500 [-] "IPADDRESS" - - [20/Feb/2018:15:00:35 +0000] "G
ET / HTTP/1.1" 200 27 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.3
6 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
2018-02-20 10:01:35-0500 [-] Timing out client: IPv4Address(TCP, 'IPADDRESS'
, 52554)
2018-02-20 10:01:48-0500 [_GenericHTTPChannelProtocol,1,127.0.0.1] Unhandled Err
or
        Traceback (most recent call last):
          File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\web\server.py
", line 255, in render
            body = resrc.render(self)
          File "C:\ProgramData\Anaconda3\lib\site-packages\klein\resource.py", l
ine 210, in render
            d = defer.maybeDeferred(_execute)
          File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\internet\defe
r.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "C:\ProgramData\Anaconda3\lib\site-packages\klein\resource.py", l
ine 204, in _execute
            **kwargs)
        --- <exception caught here> ---
          File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\internet\defe
r.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "C:\ProgramData\Anaconda3\lib\site-packages\klein\app.py", line 1
28, in execute_endpoint
            return endpoint_f(self._instance, *args, **kwargs)
          File "C:\ProgramData\Anaconda3\lib\site-packages\klein\app.py", line 2
27, in _f
            return _call(instance, f, request, *a, **kw)
          File "C:\ProgramData\Anaconda3\lib\site-packages\klein\app.py", line 5
0, in _call
            result = f(*args, **kwargs)
          File "C:\ProgramData\Anaconda3\lib\site-packages\rasa_nlu\server.py",
line 82, in decorated
            return f(*args, **kwargs)
          File "C:\ProgramData\Anaconda3\lib\site-packages\rasa_nlu\server.py",
line 99, in decorated
            return f(*args, **kwargs)
          File "C:\rasa-bot\rasa_core-master\rasa_core\server.py", line 199, in
parse
            request.content.read().decode('utf-8', 'strict'))
          File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 354, in loa
ds
            return _default_decoder.decode(s)
          File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 339, in deco
de
            obj, end = self.raw_decode(s, idx=_w(s, 0).end())
          File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 357, in raw_
decode
            raise JSONDecodeError("Expecting value", s, err.value) from None
        json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2018-02-20 10:01:48-0500 [-] "127.0.0.1" - - [20/Feb/2018:15:01:48 +0000] "POST
/conversations/default/parse HTTP/1.1" 500 9275 "-" "curl/7.55.1"
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source

libifcoremd.dll    00007FFDF7CE94C4  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFE2500BBBF  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFE275613D2  Unknown               Unknown  Unknown
ntdll.dll          00007FFE27AD54F4  Unknown               Unknown  Unknown

(base) C:\rasa-bot\rasa_core-master>`
````
Curl:
````

`
(base) C:\Users\username>curl -XPOST localhost:5005/conversations/default/parse -
d '{"query":"hello there"}'
<html><head><title>web.Server Traceback (most recent call last)</title></head><b
ody><b>web.Server Traceback (most recent call last):</b>

<div>
  <style type="text/css">
    div.error {
      color: red;
      font-family: Verdana, Arial, helvetica, sans-serif;
      font-weight: bold;
    }

    div {
      font-family: Verdana, Arial, helvetica, sans-serif;
    }

    div.stackTrace {
    }

    div.frame {
      padding: 1em;
      background: white;
      border-bottom: thin black dashed;
    }

    div.frame:first-child {
      padding: 1em;
      background: white;
      border-top: thin black dashed;
      border-bottom: thin black dashed;
    }

    div.location {
    }

    span.function {
      font-weight: bold;
      font-family: "Courier New", courier, monospace;
    }

    div.snippet {
      margin-bottom: 0.5em;
      margin-left: 1em;
      background: #FFFFDD;
    }

    div.snippetHighlightLine {
      color: red;
    }

    span.code {
      font-family: "Courier New", courier, monospace;
    }
  </style>

  <div class="error">
    <span>json.decoder.JSONDecodeError</span>: <span>Expecting value: line 1 col
umn 1 (char 0)</span>
  </div>
  <div class="stackTrace">
    <div class="frame">
      <div class="location">
        <span>C:\ProgramData\Anaconda3\lib\site-packages\twisted\internet\defer.
py</span>:<span>150</span> in
        <span class="function">maybeDeferred</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">149</span>
          <code class="code"> &#160; &#160;try:</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">150</span>
          <code class="code"> &#160; &#160; &#160; &#160;result = f(*args, **kw)
</code>
        </div><div class="snippetLine">
          <span class="lineno">151</span>
          <code class="code"> &#160; &#160;except:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>C:\ProgramData\Anaconda3\lib\site-packages\klein\app.py</span>:<sp
an>128</span> in
        <span class="function">execute_endpoint</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">127</span>
          <code class="code"> &#160; &#160; &#160; &#160;endpoint_f = self._endp
oints[endpoint]</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">128</span>
          <code class="code"> &#160; &#160; &#160; &#160;return endpoint_f(self.
_instance, *args, **kwargs)</code>
        </div><div class="snippetLine">
          <span class="lineno">129</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>C:\ProgramData\Anaconda3\lib\site-packages\klein\app.py</span>:<sp
an>227</span> in
        <span class="function">_f</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">226</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;def _f(in
stance, request, *a, **kw):</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">227</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &
#160;return _call(instance, f, request, *a, **kw)</code>
        </div><div class="snippetLine">
          <span class="lineno">228</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>C:\ProgramData\Anaconda3\lib\site-packages\klein\app.py</span>:<sp
an>50</span> in
        <span class="function">_call</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">49</span>
          <code class="code"> &#160; &#160; &#160; &#160;args = (instance,) + ar
gs</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">50</span>
          <code class="code"> &#160; &#160;result = f(*args, **kwargs)</code>
        </div><div class="snippetLine">
          <span class="lineno">51</span>
          <code class="code"> &#160; &#160;if iscoroutine(result):</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>C:\ProgramData\Anaconda3\lib\site-packages\rasa_nlu\server.py</spa
n>:<span>82</span> in
        <span class="function">decorated</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">81</span>
          <code class="code"> &#160; &#160; &#160; &#160;else:</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">82</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;return f(
*args, **kwargs)</code>
        </div><div class="snippetLine">
          <span class="lineno">83</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>C:\ProgramData\Anaconda3\lib\site-packages\rasa_nlu\server.py</spa
n>:<span>99</span> in
        <span class="function">decorated</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">98</span>
          <code class="code"> &#160; &#160; &#160; &#160;if self.config['token']
 is None or token == self.config['token']:</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">99</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;return f(
*args, **kwargs)</code>
        </div><div class="snippetLine">
          <span class="lineno">100</span>
          <code class="code"> &#160; &#160; &#160; &#160;request.setResponseCode
(401)</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>C:\rasa-bot\rasa_core-master\rasa_core\server.py</span>:<span>199<
/span> in
        <span class="function">parse</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">198</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;request_p
arams = json.loads(</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">199</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &
#160; &#160; &#160;request.content.read().decode('utf-8', 'strict'))</code>
        </div><div class="snippetLine">
          <span class="lineno">200</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>C:\ProgramData\Anaconda3\lib\json\__init__.py</span>:<span>354</sp
an> in
        <span class="function">loads</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">353</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;parse_con
stant is None and object_pairs_hook is None and not kw):</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">354</span>
          <code class="code"> &#160; &#160; &#160; &#160;return _default_decoder
.decode(s)</code>
        </div><div class="snippetLine">
          <span class="lineno">355</span>
          <code class="code"> &#160; &#160;if cls is None:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>C:\ProgramData\Anaconda3\lib\json\decoder.py</span>:<span>339</spa
n> in
        <span class="function">decode</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">338</span>
          <code class="code"> &#160; &#160; &#160; &#160;"""</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">339</span>
          <code class="code"> &#160; &#160; &#160; &#160;obj, end = self.raw_dec
ode(s, idx=_w(s, 0).end())</code>
        </div><div class="snippetLine">
          <span class="lineno">340</span>
          <code class="code"> &#160; &#160; &#160; &#160;end = _w(s, end).end()<
/code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>C:\ProgramData\Anaconda3\lib\json\decoder.py</span>:<span>357</spa
n> in
        <span class="function">raw_decode</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">356</span>
          <code class="code"> &#160; &#160; &#160; &#160;except StopIteration as
 err:</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">357</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;raise JSO
NDecodeError("Expecting value", s, err.value) from None</code>
        </div><div class="snippetLine">
          <span class="lineno">358</span>
          <code class="code"> &#160; &#160; &#160; &#160;return obj, end</code>
        </div>
      </div>
    </div>
  </div>
  <div class="error">
    <span>json.decoder.JSONDecodeError</span>: <span>Expecting value: line 1 col
umn 1 (char 0)</span>
  </div>
</div>

</body></html>

(base) C:\Users\Username>`
```


**Content of domain file** (if used & relevant):
```yaml

```

**Comment by Mormukut11** [comment]
Hi, how can we integrate Cortana and Siri with RASA?
