### ISSUE TITLE
Exception: Failed to load domain specification from 

### ISSUE THREAD

**Issue by anuranjit** [RasaHQ/rasa_nlu#2110]
**Rasa Core version**:
`rasa-core==0.8.6`
`rasa-nlu==0.11.5` 
**Python version**: 
2.7
**Operating system** (windows, osx, ...):
MacOS X
**Issue**:

`Exception: Failed to load domain specification from '/Users/anuranjit/MySpace/LM/restraunt_bot/<rasa_core.domain.TemplateDomain object at 0x10f6486d0>'. File not found!`

Traceback 
```
 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/run.py", line 151, in <module>
    cmdline_args.credentials)
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/run.py", line 130, in main
    agent = Agent.load(model_directory, nlu_model)
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/agent.py", line 66, in load
    return cls(domain, ensemble, featurizer, _interpreter, _tracker_store)
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/agent.py", line 44, in __init__
    self.domain = self._create_domain(domain)
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/agent.py", line 243, in _create_domain
    return TemplateDomain.load(domain)
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/domain.py", line 426, in load
    if not os.path.isfile(filename):
```
In the Supervised Learning [Link](https://core.rasa.com/tutorial_supervised.html) tutorial

Also to add , in `/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/domain.py` i returned the filename (which was a `TemplateDomain` object)
Now i got , 
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/run.py", line 151, in <module>
    cmdline_args.credentials)
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/run.py", line 135, in main
    agent.handle_channel(input_channel)
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/agent.py", line 126, in handle_channel
    processor.handle_channel(input_channel)
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/processor.py", line 60, in handle_channel
    input_channel.start_sync_listening(self.handle_message)
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/channels/console.py", line 52, in start_sync_listening
    self._record_messages(message_handler)
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/channels/console.py", line 45, in _record_messages
    self.sender_id))
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/processor.py", line 82, in handle_message
    self._handle_message_with_tracker(message, tracker)
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/rasa_core/processor.py", line 230, in _handle_message_with_tracker
    for e in self.domain.slots_for_entities(parse_data["entities"]):
  File "/Users/anuranjit/.virtualenvs/ml/lib/python2.7/site-packages/future/types/newstr.py", line 331, in __getattribute__
    return super(newstr, self).__getattribute__(name)
AttributeError: 'newstr' object has no attribute 'slots_for_entities'
```
 
**Content of domain file** (if used & relevant):
```yaml

```

**Comment by garchaaman19** [comment]
did you got the solution to this, i am facing the same issue.
