### ISSUE TITLE
Need help to run/train restaurantbot

### ISSUE THREAD

**Issue by dishank-shah** [RasaHQ/rasa_nlu#2123]
**Rasa Core version**:0.9.0a3

**Rasa NLU**:0.12.3

**Python version**: 2.7.6

**Operating system** (windows, osx, ...):ubuntu 16.0.4

**Issue**:
I have download the source code of rasa and try to run the restaurant-bot.
for run, I found make file in rastaurnatbot folder which have 2 command for train and run.

first i run 
```yaml
python -m rasa_nlu.train -c nlu_model_config.yml --fixed_model_name current \
 --data ./data/franken_data.json --path ./models/nlu
```
and then i got below output
```yaml
/home/dishank/local/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Fitting 2 folds for each of 6 candidates, totalling 12 fits
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    4.0s finished
```
and then i run 
```yaml
python -m rasa_core.run -d models/policy/current -u models/nlu/current
```
this command give below output

**Content of domain file** (if used & relevant):
```yaml
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/rasa_core/run.py", line 169, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_core/run.py", line 148, in main
  File "build/bdist.linux-x86_64/egg/rasa_core/agent.py", line 57, in load
  File "build/bdist.linux-x86_64/egg/rasa_core/domain.py", line 427, in load
Exception: Failed to load domain specification from '/home/user/Downloads/rasa_core-master/examples/restaurantbot/models/policy/current/domain.yml'. File not found!
```
I think we have to train our dialogue. if yes then please help me with same or help me to run this bot.

Please help me to solve this problem.

**Comment by dthaberlm** [comment]
Hi @rsreeni 
did you figure out how to solve that error? I have the same issue now.
