### ISSUE TITLE
Can not access action as that name is not a registered action for this domain

### ISSUE THREAD

**Issue by antoinecomp** [RasaHQ/rasa_nlu#2180]
**Rasa Core version**:

rasa-core           0.9.0      

**Python version**: 

Python              3.5.2

**Operating system** :

OS  Linux 16.04

**Issue**:

I tried to add more action to my `yml` file buti It seems that I can not create new actions in the domain.md: the action 'utter_sadness' can not be accessed, since that name is not an action registered for this domain:

`Can not access action 'utter_sadness', as that name is not a registered action for this domain :`

Hence my question is how to register more actions ?

Here is the error, more or less: 

```
(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ python train_init.py 
...
ERROR:rasa_core.trackers:Tried to set non existent slot 'mood'. Make sure you added all your slots to your domain file.
WARNING:rasa_core.domain:Failed to use action 'utter_sadness' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
Processed actions: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "train_init.py", line 25, in <module>
    validation_split = 0.2)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/agent.py", line 224, in train
    **kwargs)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/policies/ensemble.py", line 72, in train
    policy.train(training_trackers, domain, **kwargs)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/policies/memoization.py", line 153, in train
    self._add(trackers_as_states, trackers_as_actions, domain)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/policies/memoization.py", line 109, in _add
    feature_item = domain.index_for_action(action)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/domain.py", line 153, in index_for_action
    self._raise_action_not_found_exception(action_name)
  File "/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_core/domain.py", line 161, in _raise_action_not_found_exception
    "Available actions are: \n{}".format(action_name, actions))
Exception: Can not access action 'utter_sadness', as that name is not a registered action for this domain. Available actions are: 
     - action_listen
     - action_restart
     - action_weather
     - utter_ask_location
     - utter_goodbye
     - utter_greet
```

**Content of domain file** (if used & relevant):
```yaml
slots:
  location:
    type: text
  mood:
    type: text
  information:
    type: text
  adjective:
    type: text


intents:
 - greet
 - goodbye
 - inform

entities:
 - location
 - mood
 - information
 - adjective

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_location:
    - 'In what location?'
  utter_joy:
    - 'Am so happy for you'
  utter_fear:
    - 'you shouldn be afraid'
  utter_anger:
    - 'Calm down, everything gonna be alright'
  utter_sadness:
    - 'be a tough guy'
  utter_disgust:
    - 'I understand, this is disgusting, we should get over it'
  utter_shame:
    - 'Ridicule does not kill'
  utter_guilt:
    - 'You must not feel guilty, feel proud'

actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_location
 - actions.ActionWeather
 - utter_joy
 - utter_fear
 - utter_anger
 - utter_sadness
 - utter_disgust
 - utter_shame
 - utter_guilt
```

**Comment by quest4next** [comment]
Just in case if any one still faces this issue, make sure there are no other files in your data folder except the ones which you're used for training. This should fix your issue.

**Comment by Afrinjahan** [comment]
pip install rasa_nlu[spacy] 
worked for me

**Comment by shdw2x** [comment]
I got a similar error `Cannot access action 'affirm', as that name is not a registered action for this domain.` and then noticed that, while I was editing the stories.md file, I put a dash before `affirm`.

```
## survey happy path
- affirm
    - health_form
    ...
```

However, it should have been a star. So, changing from the dash to star worked for me. So, be aware of spaces, dashes, etc. The correct one is below.

```
## survey happy path
* affirm
    - health_form
    ...
```

**Comment by mglall** [comment]
I got a similar error Cannot access action 'affirm', as that name is not a registered action for this domain. the issue was in the stories file i use the affirm intent as an action while it should be an intent only so i changed to be an intent and it works:
- action: affirm 
it should be 👍 
- intent: affirm

**Comment by gokul427** [comment]
i faced the same, and in my case there was typo in form name in domain.yml and action in rules.yml
