### ISSUE TITLE
Custom output and the new name() property/function

### ISSUE THREAD

**Issue by PierrePaul** [RasaHQ/rasa_nlu#2371]
**Rasa Core version**: 0.10.2

**Python version**: 3.5

**Operating system** (windows, osx, ...): linux - ubuntu 18.04

**Issue**: The migration doc to > 0.10.x says we need to implement a new `name()` **property**.
https://github.com/RasaHQ/rasa_core/blob/0.10.2/docs/migrations.rst
The dispatcher though, calls a `name()` **function**.
https://github.com/RasaHQ/rasa_core/blob/0.10.2/rasa_core/dispatcher.py#L172

Also important, doc mention the CollectingOutputChannel as a template to use. It uses a **property**.
https://github.com/RasaHQ/rasa_core/blob/0.10.2/rasa_core/channels/direct.py#L10

And the full error with python3.5 when using a property : 
```
ERROR:rasa_core.processor:'str' object is not callable                                                                                       │                                                                                                                                            
Traceback (most recent call last):                                                                                                           │                                                                                                                                            
  File "<redacted>/lib/python3.5/site-packages/rasa_core/processor.py", line 311, in _run_action               │                                                                                                                                            
    events = action.run(dispatcher, tracker, self.domain)                                                                                    │                                                                                                                                            
  File "<redacted>/lib/python3.5/site-packages/rasa_core/actions/action.py", line 72, in run                   │                                                                                                                                            
    tracker)                                                                                                                                 │                                                                                                                                            
  File "<redacted>/lib/python3.5/site-packages/rasa_core/dispatcher.py", line 154, in utter_template           │                                                                                                                                            
    **kwargs)                                                                                                                                │                                                                                                                                            
  File "<redacted>/lib/python3.5/site-packages/rasa_core/dispatcher.py", line 172, in _generate_response       │                                                                                                                                            
    self.output_channel.name(),                                                                                                              │                                                                                                                                            
TypeError: 'str' object is not callable 
```

**Comment by ngoctnq-1957** [comment]
I stumbled onto this link having the same problem, and assuming you were on the same boat as I am, the culprit is PyCharm -- it suggests that decorator change.
