### ISSUE TITLE
ruamel.yaml.scanner.ScannerError: mapping values are not allowed in this context   in "<unicode string>", line 2, column 8

### ISSUE THREAD

**Issue by loveJasmine** [RasaHQ/rasa_nlu#2440]
(.venv) mldl@ub1604:/ub16_prj/rasa_core$ python3 -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue
/home/mldl/ub16_prj/rasa_core/.venv/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/train.py", line 191, in <module>
    additional_arguments)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/train.py", line 152, in train_dialogue_model
    policies=policies)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/agent.py", line 200, in __init__
    self.domain = self._create_domain(domain)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/agent.py", line 618, in _create_domain
    return Domain.load(domain)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/domain.py", line 89, in load
    return cls.from_yaml(read_file(filename))
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/domain.py", line 93, in from_yaml
    cls.validate_domain_yaml(yaml)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/domain.py", line 123, in validate_domain_yaml
    source_data = utils.read_yaml_string(yaml)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/utils.py", line 338, in read_yaml_string
    return yaml_parser.load(string)
  File "/home/mldl/ub16_prj/rasa_core/.venv/lib/python3.5/site-packages/ruamel/yaml/main.py", line 266, in load
    return constructor.get_single_data()
  File "/home/mldl/ub16_prj/rasa_core/.venv/lib/python3.5/site-packages/ruamel/yaml/constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 725, in _ruamel_yaml.CParser._compose_document
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.scanner.ScannerError: mapping values are not allowed in this context
  in "<unicode string>", line 2, column 8
(.venv) mldl@ub1604:~/ub16_prj/rasa_core$

**Comment by selphe** [comment]
@loveJasmine 
You could also check `config.yml`, mine was not valid:

```
  - name: TwoStageFallbackPolicy
        nlu_threshold: 0.8
        core_threshold: 0.3
```

Changed to this:
```
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.8
    core_threshold: 0.3
```
