### ISSUE TITLE
ImportError: ('requires pygraphviz ', 'http://pygraphviz.github.io/')

### ISSUE THREAD

**Issue by Aarbor1** [RasaHQ/rasa_nlu#2505]
**Rasa Core version**:0.11.3

**Python version**: 3.6.4

**Operating system** (windows, osx, ...):Windows 10 64xbit OS

**Issue**:I'm already installed pygraphviz1.5 but when i try to run sample rasa_core concert-bot visualize.py file I'm facing following error

C:\Users\Aarbor 01\rasa_core\examples\concertbot>python visualize.py
C:\ProgramData\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning:
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Processed Story Blocks: 100%|███████| 7/7 [00:00<00:00, 7265.56it/s, # trackers=1]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\networkx\drawing\nx_agraph.py", line 132, in to_agraph
    import pygraphviz
  File "C:\Users\Aarbor 01\AppData\Roaming\Python\Python36\site-packages\pygraphviz\__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "C:\Users\Aarbor 01\AppData\Roaming\Python\Python36\site-packages\pygraphviz\agraph.py", line 22, in <module>
    from . import graphviz as gv
  File "C:\Users\Aarbor 01\AppData\Roaming\Python\Python36\site-packages\pygraphviz\graphviz.py", line 28, in <module>
    _graphviz = swig_import_helper()
  File "C:\Users\Aarbor 01\AppData\Roaming\Python\Python36\site-packages\pygraphviz\graphviz.py", line 24, in swig_import_helper
    _mod = imp.load_module('_graphviz', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "visualize.py", line 15, in <module>
    output_file="graph.png", max_history=2)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rasa_core\agent.py", line 602, in visualize
    should_merge_nodes, fontsize)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rasa_core\training\visualization.py", line 323, in visualize_stories
    persist_graph(graph, output_file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rasa_core\training\visualization.py", line 228, in persist_graph
    expg = nx.nx_agraph.to_agraph(graph)  # convert to a graphviz graph
  File "C:\ProgramData\Anaconda3\lib\site-packages\networkx\drawing\nx_agraph.py", line 135, in to_agraph
    'http://pygraphviz.github.io/')
ImportError: ('requires pygraphviz ', 'http://pygraphviz.github.io/')

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by karpagaganesh** [comment]
pos = graphviz_layout(G)
  File "/lib/python2.7/site-packages/networkx/drawing/nx_agraph.py", line 243, in graphviz_layout
    return pygraphviz_layout(G, prog=prog, root=root, args=args)
  File "/lib/python2.7/site-packages/networkx/drawing/nx_agraph.py", line 286, in pygraphviz_layout
    'http://pygraphviz.github.io/')
ImportError: ('requires pygraphviz ', 'http://pygraphviz.github.io/')
