### ISSUE TITLE
Intents not updating in interactive learning

### ISSUE THREAD

**Issue by samarth12** [RasaHQ/rasa_nlu#2636]
**Rasa Core version**:
Version: 0.11.12
**Python version**: 
Python 3.6.5 :: Anaconda, Inc.
**Operating system** (windows, osx, ...):
MacOS
**Issue**:
I am using the basic getting started bot to test interactive learning. The stories part seems to run great. I am also using a trained NLU model for the intents. 

When the user input is classified as a "None" intent. We have two options, to either correct and choose an intent from the existing list or choose the "other" option which allows us to define a new intent and then mark entities in the input sentence. 

If I choose an existing intent to correct an input that has been classified as "None" and then retrian the interactive learning model the model doesn't seem to capture the intent correction. Am I missing something? How does this work? I also checked if I need to train the NLU model to update it but I don't see any changes to the NLU file so that doesn't make sense. 

Secondly, if I choose the "other" option in case none of the intents match my input it asks me to name the intent followed by marking entities in that. That doesn't seem to work, it throws an error. 

Here is the error in the second case:

? **Next user input:  I need chinese food**
127.0.0.1 - - [2018-10-19 01:31:29] "POST /conversations/default/messages HTTP/1.1" 200 668 0.050945
127.0.0.1 - - [2018-10-19 01:31:29] "GET /conversations/default/tracker?include_events=AFTER_RESTART HTTP/1.1" 200 668 0.000868
**? Is the NLU classification for 'I need chinese food' with intent 'None' correct
? What intent is it?       <other>
? Please type the intent name  food
? Please mark the entities using [value](type) notation  I need [chinese](cuisin
e) food**
127.0.0.1 - - [2018-10-19 01:31:54] "PUT /conversations/default/tracker/events HTTP/1.1" 200 388 0.001075
127.0.0.1 - - [2018-10-19 01:31:54] "POST /conversations/default/messages HTTP/1.1" 200 692 0.001299
2018-10-19 01:31:54 ERROR    rasa_core.server  - Caught an exception during prediction.
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/server.py", line 340, in predict
    responses = agent.predict_next(sender_id)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/agent.py", line 317, in predict_next
    return processor.predict_next(sender_id)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 102, in predict_next
    self._get_next_action_probabilities(tracker)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 457, in _get_next_action_probabilities
    tracker, self.domain)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/policies/ensemble.py", line 216, in probabilities_using_best_policy
    probabilities = p.predict_action_probabilities(tracker, domain)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/policies/fallback.py", line 101, in predict_action_probabilities
    nlu_confidence = nlu_data["intent"].get("confidence", 1.0)
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/gevent/pywsgi.py", line 963, in handle_one_response
    self.run_application()
  File "/anaconda3/lib/python3.6/site-packages/gevent/pywsgi.py", line 911, in run_application
    self.process_result()
  File "/anaconda3/lib/python3.6/site-packages/gevent/pywsgi.py", line 895, in process_result
    for data in self.result:
  File "/anaconda3/lib/python3.6/site-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/anaconda3/lib/python3.6/site-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
TypeError: 'Response' object is not iterable
2018-10-19T08:31:54Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '53538', 'HTTP_HOST': 'localhost:5005', (hidden keys: 23)} failed with TypeError

127.0.0.1 - - [2018-10-19 01:31:54] "POST /conversations/default/predict HTTP/1.1" 500 161 0.003504
2018-10-19 01:31:54 ERROR    rasa_core.training.online  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/online.py", line 860, in record_messages
    finetune=finetune)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/online.py", line 589, in _predict_till_next_listen
    response = request_prediction(endpoint, sender_id)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/online.py", line 98, in request_prediction
    return _response_as_json(r)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/online.py", line 62, in _response_as_json
    response.raise_for_status()
  File "/anaconda3/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:5005/conversations/default/predict

**Content of domain file** (if used & relevant):
```yaml
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"
```

```
md
## intent:greet
- hey
- hello
- hi
- good morning
- good evening
- hey there

## intent:goodbye
- bye
- goodbye
- see you around
- see you later

## intent:mood_affirm
- yes
- indeed
- of course
- that sounds good
- correct

## intent:mood_deny
- no
- never
- I don't think so
- don't like that
- no way
- not really

## intent:mood_great
- perfect
- very good
- great
- amazing
- wonderful
- I am feeling very good
- I am great
- I'm good

## intent:mood_unhappy
- sad
- very sad
- unhappy
- bad
- very bad
- awful
- terrible
- not very good
- extremly sad
- so sad
```

Let me know if you need any additional information, thank you!

**Comment by garchaaman19** [comment]
i have same issue in rasa core 13.7, what should i do ? Will it work on slack if i try to run there?
