### ISSUE TITLE
config is not passed to visualize, visualize report no FormPolicy for version 0.12.0

### ISSUE THREAD

**Issue by cookie314** [RasaHQ/rasa_nlu#2728]
**Rasa Core version**: 0.12.0

**Python version**: 3.6

**Operating system** (windows, osx, ...):osx

**Issue**:
now policy is stored in config file while visualize.py doesn't use the -c argument. And default there is no form policy in visualize.py. When run visualize using domain with forms section. Error as below
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/visualize.py", line 60, in <module>
    agent = Agent(args.domain, policies=[MemoizationPolicy(), KerasPolicy()])
  File "/usr/local/lib/python3.6/site-packages/rasa_core/agent.py", line 208, in __init__
    "You have defined a form action, but haven't added the "
rasa_core.domain.InvalidDomain: You have defined a form action, but haven't added the FormPolicy to your policy ensemble.
```

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by rmiaouh** [comment]
> ## Specify in your dialogue_model.py file:
> from rasa_core.policies import Policy, FormPolicy
> ```
>   agent = Agent(domain_file, policies=[MemoizationPolicy(), KerasPolicy(), FormPolicy()])
> ```
> 
> It will help you to reslove your error.

--> from rasa_core.policies.form_policy import FormPolicy
--> agent = Agent(domain_file, policies=[MemoizationPolicy(), KerasPolicy(), FormPolicy()])
