### ISSUE TITLE
Interactive Training: Can not access action 'None'

### ISSUE THREAD

**Issue by tahamr83** [RasaHQ/rasa_nlu#2743]
**Rasa Core version**:
0.12.0

**Python version**: 
3.6.6

**Operating system** (windows, osx, ...):
MacOs Mojave

**Issue**:
When training interactively the action does not execute. 

------
```
 The bot wants to run 'action_set_preferences', correct?  Yes
2018-11-14 18:46:07 ERROR    rasa_core.server  - Can not access action 'None', as that name is not a registered action for this domain. Available actions are:
	 - action_listen
	 - action_restart
	 - action_default_fallback
	 - action_set_preferences

Traceback (most recent call last):
  File "/Users/muhammadtahazaidi/MyFiles/WorkVocinity/venvs/env_vocinity-mcdonalds/lib/python3.6/site-packages/rasa_core/server.py", line 220, in execute_action
    confidence)
  File "/Users/muhammadtahazaidi/MyFiles/WorkVocinity/venvs/env_vocinity-mcdonalds/lib/python3.6/site-packages/rasa_core/agent.py", line 359, in execute_action
    confidence)
  File "/Users/muhammadtahazaidi/MyFiles/WorkVocinity/venvs/env_vocinity-mcdonalds/lib/python3.6/site-packages/rasa_core/processor.py", line 150, in execute_action
    action = self._get_action(action_name)
  File "/Users/muhammadtahazaidi/MyFiles/WorkVocinity/venvs/env_vocinity-mcdonalds/lib/python3.6/site-packages/rasa_core/processor.py", line 239, in _get_action
    return self.domain.action_for_name(action_name, self.action_endpoint)
  File "/Users/muhammadtahazaidi/MyFiles/WorkVocinity/venvs/env_vocinity-mcdonalds/lib/python3.6/site-packages/rasa_core/domain.py", line 284, in action_for_name
    self._raise_action_not_found_exception(action_name)
  File "/Users/muhammadtahazaidi/MyFiles/WorkVocinity/venvs/env_vocinity-mcdonalds/lib/python3.6/site-packages/rasa_core/domain.py", line 323, in _raise_action_not_found_exception
    "".format(action_name, action_names))
NameError: Can not access action 'None', as that name is not a registered action for this domain. Available actions are:
	 - action_listen
	 - action_restart
	 - action_default_fallback
	 - action_set_preferences
```
I have peeked at the rasa_core code. The `payload = ActionExecuted(action_name, policy, confidence).as_dict()`(interactive.py) has the actions name as 'name' key while server.py expects the name of the action as `request_params.get("action", None)` (server.py line 209). For the purposes of interactive learning it works by changing it to `request_params.get("name", None)`

**Comment by rohangore1999** [comment]
@tmbo add '- action_test' in domain.yml in action section that may be work
