### ISSUE TITLE
Docker run EROR

### ISSUE THREAD

**Issue by algteam** [RasaHQ/rasa_nlu#2852]
docker run \
  -v $(pwd):/app/project \
  -v $(pwd)/models/rasa_core:/app/models \
  rasa/rasa_core:latest \
  train \
    --domain project/domain.yml \
    --stories project/data/stories.md \
    --out models

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/rasa_core/train.py", line 351, in <module>
    additional_args)
  File "/app/rasa_core/train.py", line 266, in do_default_training
    kwargs=additional_arguments)
  File "/app/rasa_core/train.py", line 178, in train_dialogue_model
    policies=policies)
  File "/app/rasa_core/agent.py", line 190, in __init__
    self.domain = self._create_domain(domain)
  File "/app/rasa_core/agent.py", line 639, in _create_domain
    return Domain.load(domain)
  File "/app/rasa_core/domain.py", line 88, in load
    return cls.from_yaml(read_file(filename))
  File "/app/rasa_core/domain.py", line 92, in from_yaml
    cls.validate_domain_yaml(yaml)
  File "/app/rasa_core/domain.py", line 170, in validate_domain_yaml
    source_data = utils.read_yaml_string(yaml)
  File "/app/rasa_core/utils.py", line 327, in read_yaml_string
    return yaml_parser.load(string)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/main.py", line 325, in load
    return constructor.get_single_data()
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 108, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 118, in construct_document
    for _dummy in generator:
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 671, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 398, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 243, in construct_mapping
    self.check_mapping_key(node, key_node, mapping, key, value)
  File "/usr/local/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 278, in check_mapping_key
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "<unicode string>", line 1, column 1
found duplicate key "intents" with value "[]" (original value: "[]")
  in "<unicode string>", line 22, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.

**Comment by RajkamalMishra** [comment]
Please check your config.yml file. You might have forgot to comment/remove "pipeline: supervised_embeddings" while addig other components there. If you are using default/customized components of supervised_embeddings, it is advisable to remove supervised_embeddings line. or you can use this command only and remove others.
