### ISSUE TITLE
Error while running Interactive Training On Docker 

### ISSUE THREAD

**Issue by stacybot123** [RasaHQ/rasa_nlu#2864]
**Rasa Core version**: 0.13.0a5

**Operating system** (windows, osx, ...):  Ubuntu 18.04.1 

I have deployed bot on docker. To generate stories , I want to run the interactive learning . Used command as 
```
docker run -v $(pwd):/app/project -v $(pwd)/models/rasa_core:/app/models rasa/rasa_core:latest run python -m rasa_core.train interactive -o models -d /app/project/domain.yml -s /app/project/data/stories.md --nlu /app/models --endpoints /app/project/config/endpoints.yml

```

this worked but after Epoch , I got this error
```

2019-01-02 08:57:30 INFO     rasa_core.policies.keras_policy  - Done fitting keras policy model
Processed actions: 39it [00:00, 3432.11it/s, # examples=39]
2019-01-02 08:57:30 INFO     rasa_core.agent  - Persisted model to '/app/models'
2019-01-02 08:57:30 INFO     rasa_core.training.interactive  - Rasa Core server is up and running on http://localhost:5005
Processed Story Blocks: 100%|███████Bot loaded. Visualisation at http://localhost:5005/visualization.html.Ctr-c to abort):
Type a message and press enter (press 'Ctr-c' to exit).
? Next user input (Ctr-c to abort):

Warning: Output is not to a terminal (fd=1).
Warning: Input is not to a terminal (fd=0).
2019-01-02 08:57:30 ERROR    rasa_core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/app/rasa_core/training/interactive.py", line 1213, in record_messages
    _enter_user_message(sender_id, endpoint)
  File "/app/rasa_core/training/interactive.py", line 1063, in _enter_user_message
    lambda a: not a)
  File "/app/rasa_core/training/interactive.py", line 313, in _ask_or_abort
    answers = questions.ask()
  File "/usr/local/lib/python3.6/site-packages/questionary/question.py", line 17, in ask
    return self.unsafe_ask(patch_stdout)
  File "/usr/local/lib/python3.6/site-packages/questionary/question.py", line 27, in unsafe_ask
    return self.application.run()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 699, in run
    return run()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 673, in run
    return f.result()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 652, in _run_async2
    result = yield f
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 604, in _run_async
    result = yield From(f)
EOFError
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/app/rasa_core/training/interactive.py", line 1213, in record_messages
    _enter_user_message(sender_id, endpoint)
  File "/app/rasa_core/training/interactive.py", line 1063, in _enter_user_message
    lambda a: not a)
  File "/app/rasa_core/training/interactive.py", line 313, in _ask_or_abort
    answers = questions.ask()
  File "/usr/local/lib/python3.6/site-packages/questionary/question.py", line 17, in ask
    return self.unsafe_ask(patch_stdout)
  File "/usr/local/lib/python3.6/site-packages/questionary/question.py", line 27, in unsafe_ask
    return self.application.run()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 699, in run
    return run()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 673, in run
    return f.result()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 652, in _run_async2
    result = yield f
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 604, in _run_async
    result = yield From(f)
EOFError
```

**Comment by madanmeena** [comment]
> @stacybot123
> 
> Just a thought, does this work for your _endpoints.yml_:
> 
> ```
> action_endpoint:
>     url: 'http://action_server:5055/webhook'
> nlu:
>     url: 'http://rasa_nlu:5000'
> ```
> 
> ??

Yes this works
