### ISSUE TITLE
rasa_core.exceptions.UnsupportedDialogueModelError: Either retrain the model, or run withan older version. Model version: 0.0.0 Instance version: 0.12.3 Minimal compatible version: 0.12.0

### ISSUE THREAD

**Issue by dummybot123** [RasaHQ/rasa_nlu#2917]
I wrote the following command for running Rasa Core.
`>python -m rasa_core.run -d framework/models/dialogue -u framework/models/nlu/default/model_20190121-131223 --endpoints framework/endpoints.yml`

Running this command is generating the following error.

rasa_core.exceptions.UnsupportedDialogueModelError: The model version is to old to be loaded by this Rasa Core instance. Either retrain the model, or run withan older version. Model version: 0.0.0 Instance version: 0.12.3 Minimal compatible version: 0.12.0

**Content of endpoints.yml file**
```
action_endpoint:
    url: "http://localhost:5055/webhook/"
```

Rasa Core Version: 0.12.3

Rasa NLU Version: 0.13.8

Python 3.6.5

Since my model version is being showed 0.0.0, do I need to retrain it? If so, then how to retrain it with a higher version?

**Comment by anilpankaj** [comment]
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    interpreter = NaturalLanguageInterpreter.create('/home/anil/Documents/slackbot/models/dialogue')
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 34, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 234, in __init__
    self._load_interpreter()
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 257, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 301, in load
    Interpreter.ensure_model_compatibility(model_metadata)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 280, in ensure_model_compatibility
    "".format(model_version, rasa_nlu.__version__))
rasa_nlu.model.UnsupportedModelError: The model version is to old to be loaded by this Rasa NLU instance. Either retrain the model, or run withan older version. Model version: 0.0.0 Instance version: 0.15.1

**Comment by kiratkaur** [comment]
I'm having the same issue too!
