### ISSUE TITLE
Action error library training dialog

### ISSUE THREAD

**Issue by valdu02100** [RasaHQ/rasa_nlu#2948]
**Rasa Core version**: 
rasa-core-sdk       0.12.1                
rasa-nlu                0.14.1   
**Python version**: 3.5

**Operating system** : Linux Ubuntu 16.04

**Problem**: 
I'm nw user from RASA core. 
I train my NLU  without problems but not my dialog.  I have an error from python : 

> python3 train_dialog.py 
```
Traceback (most recent call last):
  File "train_dialog.py", line 6, in <module>
    from rasa_core.actions import Action
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/__init__.py", line 1, in <module>
    from rasa_core.actions.action import Action
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 9, in <module>
    from rasa_core import events
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/events/__init__.py", line 72, in <module>
    class Event(object):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/events/__init__.py", line 93, in Event
    default: Optional[Type['Event']] = None
  File "/usr/lib/python3.5/typing.py", line 649, in __getitem__
    return Union[arg, type(None)]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

> train_dialog.py
```
# Imports
#-----------
# rasa core
import logging
from rasa_core import training
from rasa_core.actions import Action
from rasa_core.agent import Agent
from rasa_core.domain import Domain
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.featurizers import MaxHistoryTrackerFeaturizer, BinarySingleStateFeaturizer
from rasa_core.channels.console import ConsoleInputChannel
from rasa_core.interpreter import RegexInterpreter
from rasa_core.interpreter import RasaNLUInterpreter

# Function
#------------
def train_dialog(dialog_training_data_file, domain_file, path_to_model = './models/dialogue'):
    logging.basicConfig(level='INFO')
    agent = Agent(domain_file,
              policies=[MemoizationPolicy(max_history=1)])
    training_data = agent.load_data(dialog_training_data_file)
    agent.train(
        training_data,
        augmentation_factor=50,
        epochs=200,
        batch_size=10,
        validation_split=0.2)
    agent.persist(path_to_model)

# Train
#--------
train_dialog('./data/stories.md', 'domain.yml')
```

>  domain.yml
```
intents:
  - greet
  - query_days_in_month
  - bye

entities: 
  - month

templates: 
  utter_greet:
    - "Hey, Comment puis-je t'aider?"
  utter_answer_31_days:
    - "Il y a 31 jours ce mois là"
  utter_answer_30_days:
    - "Il y a 30 jours ce mois là"
  utter_answer_28_days:
    - "Il y a 28 jours  ce mois là"
  utter_bye:
    - "Au plaisir de te revoir"

actions:
  - utter_greet
  - utter_answer_31_days
  - utter_answer_30_days
  - utter_answer_28_days
  - utter_bye
```

Someone know the issue ? 

Thanks for your help

**Comment by red-frog** [comment]
if i can't upgrade the python, have other sulotion? @Ghostvv

**Comment by Ghostvv** [comment]
what is you python version?

**Comment by red-frog** [comment]
> what is you python version?

3.5.2

**Comment by Ghostvv** [comment]
if you cannot install python `3.5.3`, I'm afraid the other solution is to remove type annotation that cause the problem

**Comment by akelad** [comment]
i'm going to close this issue then as there's nothing we can do
