### ISSUE TITLE
MongoDB Tracker Store Authentication Issue

### ISSUE THREAD

**Issue by krishna-kimo** [RasaHQ/rasa_nlu#2968]
**Rasa Core version**: 0.13.1

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): OSX

**Issue**: Tried connecting to MongoDB tracker-store using the format given in the docs but getting an Authentication Error. I am using MLab. There is no problem with the credentials as I am able to connect to the remote db using both MongoDB and Pymongo. I am not sure how to approach this problem. 

**Content of domain file** (if used & relevant):
endpoints.yaml
```
action_endpoint:
  url: "http://localhost:5055/webhook"

tracker_store:
  store_type: mongod
  url: mongodb://ds######.mlab.com:######
  #db: <dbname>
  username: <##username with no quotes>
  password: < ##password with no quotes>
```
And here is the error (Traceback) I am getting
```
Traceback (most recent call last):
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/run.py", line 247, in <module>
    None, _endpoints.tracker_store, _broker)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/tracker_store.py", line 40, in find_tracker_store
    **store.kwargs)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/tracker_store.py", line 202, in __init__
    self._ensure_indices()
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/tracker_store.py", line 209, in _ensure_indices
    self.conversations.create_index("sender_id")
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/collection.py", line 1958, in create_index
    self.__create_index(keys, kwargs, session, **cmd_options)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/collection.py", line 1847, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1058, in _get_socket
    with server.get_socket(self.__all_credentials) as sock_info:
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/pool.py", line 1006, in get_socket
    sock_info.check_auth(all_credentials)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/pool.py", line 677, in check_auth
    auth.authenticate(credentials, self)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/auth.py", line 563, in authenticate
    auth_func(credentials, sock_info)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/auth.py", line 540, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/auth.py", line 262, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.

```

**Comment by ortsaCniveK** [comment]
Just wanted to leave a comment here for those that might run into similar issues (mine personally were messages about needing to have `dnspython` installed; while mLab might work since they don't provide the protocol, I built my own custom docker image to install `pymongo[srv]` to be able to use the Atlas  `mongo+srv://` URIs.  

This might be worth an additional PR but it was pretty simple with a dockerfile that looks like below:

```dockerfile
FROM rasa/rasa_core:0.14.5

# need pymongo dependency for mongo+srv:// URIs
RUN pip install --no-cache-dir pymongo[srv]
```

**Comment by argideritzalpea** [comment]
@ortsaCniveK Thanks for the tip, however, I can't seem to figure out how to get rasa to build installing the pymongo dependency upon starting the container. I tried add a few lines in my docker-compose.yml that refer to the Dockerfile that you mention above, but I still get the error.
Additionally, I can't seem to start rasa in a detached state in order to install it and tag it as a new image. The rasa/rasa:latest-full image won't persist in a container with the command "docker run -dit [imageID]" to allow me to exec inside and install it.

Here's what I added to my docker-compose.yml:
```services:
  rasa:
    image: rasa/rasa:latest
    networks: ['rasa-network']
    build:
      context: .
      dockerfile: Dockerfile-rasa
    ports:
    - "5005:5005"
    volumes:
    - ./:/app
            #- "./models:/app/models"
            #- "./data:/app/data"
      #- "./rasa:/usr/local/lib/python3.6/site-packages/rasa"
    command: run --enable-api --model models --p 5200 --connector twilio --credentials credentials.yml --endpoints endpoints-twilio.yml
```
How do you recommend I modify my Dockerfile-rasa to comport with this docker-compose.yml?

**Comment by ortsaCniveK** [comment]
You would need to run `docker build Dockerfile-rasa -t <image name>:<tag>` in the same directory as your `Dockerfile-rasa`.  Then, once you have the name for your image, you include that in your `docker-compose.yml`, you're still using the base rasa image without the Pymongo[srv] dependency installed.  It's best to have the complete image to work with then just run the default start command as opposed to trying to insert the command to download a dependency for you at run time.

So for example:
**Dockerfile-rasa**
```yml
FROM rasa/rasa:latest

# need pymongo dependency for mongo+srv:// URIs
RUN pip install --no-cache-dir pymongo[srv]
```
> now we have the definition of the image ready

**image build command with image and tag name**

```sh
docker build Dockerfile-rasa -t custom_rasa:latest
```
> now we have a new custom image called `custom_rasa:latest`

**Docker-compose.yml**
```yml
rasa:
    image: custom_rasa:latest # note the change in image name here
    networks: ['rasa-network']
    build:
      context: .
      dockerfile: Dockerfile-rasa
    ports:
    - "5005:5005"
    volumes:
    - ./:/app
    command: run --enable-api --model models --p 5200 --connector twilio --credentials credentials.yml --endpoints endpoints-twilio.yml
```

> using the custom built image, we run the same rasa commands, but now have a container with the Pymongo[srv] optional dependency, which allows us to use `mongodb+srv://` URIs
