### ISSUE TITLE
Rasa core training error

### ISSUE THREAD

**Issue by Rajskc** [RasaHQ/rasa_nlu#2989]
**Rasa Core version**: 0.11.3

**Python version**: 3.6.4

**Operating system** (windows, osx, ...): windows

**Issue**:  I am getting the following error when I am trying to train. It says the parser is not able to get the key, what does the parser do?:
```
UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Traceback (most recent call last):
  File "C:\Users\M Phanidhar\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\M Phanidhar\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\M Phanidhar\Anaconda3\lib\site-packages\rasa_core\train.py", line 351, in <module>
    additional_args)
  File "C:\Users\M Phanidhar\Anaconda3\lib\site-packages\rasa_core\train.py", line 265, in do_default_training
    kwargs=additional_arguments)
  File "C:\Users\M Phanidhar\Anaconda3\lib\site-packages\rasa_core\train.py", line 178, in train_dialogue_model
    policies=policies)
  File "C:\Users\M Phanidhar\Anaconda3\lib\site-packages\rasa_core\agent.py", line 193, in __init__
    self.domain = self._create_domain(domain)
  File "C:\Users\M Phanidhar\Anaconda3\lib\site-packages\rasa_core\agent.py", line 648, in _create_domain
    return Domain.load(domain)
  File "C:\Users\M Phanidhar\Anaconda3\lib\site-packages\rasa_core\domain.py", line 88, in load
    return cls.from_yaml(read_file(filename))
  File "C:\Users\M Phanidhar\Anaconda3\lib\site-packages\rasa_core\domain.py", line 92, in from_yaml
    cls.validate_domain_yaml(yaml)
  File "C:\Users\M Phanidhar\Anaconda3\lib\site-packages\rasa_core\domain.py", line 170, in validate_domain_yaml
    source_data = utils.read_yaml_string(yaml)
  File "C:\Users\M Phanidhar\Anaconda3\lib\site-packages\rasa_core\utils.py", line 332, in read_yaml_string
    return yaml_parser.load(string)
  File "C:\Users\M Phanidhar\Anaconda3\lib\site-packages\ruamel\yaml\main.py", line 331, in load
    return constructor.get_single_data()
  File "C:\Users\M Phanidhar\Anaconda3\lib\site-packages\ruamel\yaml\constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 891, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 122, column 3
did not find expected key
  in "<unicode string>", line 291, column 4
```

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by zhoulijing01** [comment]
@Rajskc  can you tell me about you domain text specific error , i meet  same error,thanks !
