### ISSUE TITLE
ImportError: cannot import name 'Layer'

### ISSUE THREAD

**Issue by GavinMoreYoung** [RasaHQ/rasa_nlu#2994]
**Rasa Core version**:0.13.2

**Python version**: python3.6.8

**Operating system** (windows, osx, ...):win10

**Issue**:
Traceback (most recent call last):
  File "C:/Users/Admin/Desktop/building-chatbots-with-python-master/Chapter IV/Chapter IV Code horoscope_bot/horoscope_bot/train_initialize.py", line 27, in <module>
    validation_split=0.2
  File "D:\Python\lib\site-packages\rasa_core\agent.py", line 520, in train
    **kwargs)
  File "D:\Python\lib\site-packages\rasa_core\policies\ensemble.py", line 63, in train
    policy.train(training_trackers, domain, **kwargs)
  File "D:\Python\lib\site-packages\rasa_core\policies\keras_policy.py", line 162, in train
    shuffled_y.shape[1:])
  File "D:\Python\lib\site-packages\rasa_core\policies\keras_policy.py", line 93, in model_architecture
    from tensorflow.keras.models import Sequential
  File "D:\Python\lib\site-packages\tensorflow\keras\__init__.py", line 20, in <module>
    from . import layers
  File "D:\Python\lib\site-packages\tensorflow\keras\layers\__init__.py", line 8, in <module>
    from tensorflow.python.estimator.keras import Layer
ImportError: cannot import name 'Layer'

I am a beginner,this problem gets me,i do not know how to do ,i hope you can help me,thanks. 

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by mlpypiter** [comment]
I have a same issue using jupyter notebook.
During:         import rasa
Help me.
