### ISSUE TITLE
Test or evaluate commands fail due to Docker image's python installation

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa_nlu#3045]
**Rasa Core version**: 0.13.2 (from rasa/rasa_core:stable)

**Python version**: 3.6

**Operating system** (windows, osx, ...): macOS

**Issue**:  There is an issue in which running the below command does not complete successfully (tested on both personal project and starter pack with retrained model using 0.13.3):

```sh
docker run --rm \
    -it \
    -v `pwd`/data/stories:/app/stories \
    -v `pwd`/models/current/dialogue:/app/core \
    -v `pwd`/evaluations:/app/out \
  rasa/rasa_core:stable \
  run \
    python -m rasa_core.evaluate \
    --core core \
    --stories stories \
    -o out
```

Which ends with the below output:

```sh
INFO:matplotlib.font_manager:font search path ['/usr/local/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf', '/usr/local/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/afm', '/usr/local/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts']
INFO:matplotlib.font_manager:generated new fontManager
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/rasa_core/evaluate.py", line 655, in <module>
    cmdline_arguments.e2e)
  File "/app/rasa_core/evaluate.py", line 496, in run_story_evaluation
    out_directory)
  File "/app/rasa_core/evaluate.py", line 537, in plot_story_evaluation
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
```
Looking around for the import issue, I found:

> If it fails with "No module named _tkinter", your Python configuration needs to be modified to include this module (which is an extension module implemented in C). Do **not** edit Modules/Setup (it is out of date). You may have to install Tcl and Tk (when using RPM, install the -devel RPMs as well) and/or edit the setup.py script to point to the right locations where Tcl/Tk is installed. If you install Tcl/Tk in the default locations, simply rerunning "make" should build the _tkinter extension.

I have also tested this same command with `rasa/rasa_core:latest` built models and `rasa_core.test` instead of `rasa_core.evaluate` as per the docs, but I'm getting the same error.  To allow for this to work, we likely need to add to list of requirements in order to assure that the script runs successfully.

**Comment by akelad** [comment]
@wochinge should we close this issue then?
