### ISSUE TITLE
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("masking_1_input:0", shape=(?, 3, 24), dtype=float32) is not an element of this graph.

### ISSUE THREAD

**Issue by ray-man** [RasaHQ/rasa_nlu#3102]
**Rasa Core version** : 0.7.0

**Operating system**: OSX 10.11.6

**Issue**:
Using rasa_core as part of Django app while requesting for training to be done with provided data everything goes smooth but if i try to re train without changing anything from data or any any other related file am getting **TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("masking_1_input:0", shape=(?, 3, 24), dtype=float32) is not an element of this graph.**

**Traceback**:
```
Internal Server Error: /3/process_training/
Traceback (most recent call last):
File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 930, in _run
    allow_operation=False)
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2414, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2493, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("masking_1_input:0", shape=(?, 3, 24), dtype=float32) is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rayman/Sites/rasa_trainer/thumbcrowdai/webapps/version_3.0/core/rasa_trainer/views.py", line 407, in process_training
    train_dm.train()
  File "/Users/rayman/Sites/rasa_trainer/thumbcrowdai/webapps/version_3.0/modules/rasa_dm/bots/weather/train_dm.py", line 28, in train
    validation_split=0.2
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/rasa_dm-0.7.0a1-py3.6.egg/rasa_dm/agent.py", line 101, in train
    trainer.train(filename, **kwargs)
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/rasa_dm-0.7.0a1-py3.6.egg/rasa_dm/policies/trainer.py", line 44, in train
    self.ensemble.train(X, y, self.domain, self.featurizer, **kwargs)
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/rasa_dm-0.7.0a1-py3.6.egg/rasa_dm/policies/ensemble.py", line 29, in train
    policy.train(X, y, domain, **kwargs)
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/rasa_dm-0.7.0a1-py3.6.egg/rasa_dm/policies/keras_policy.py", line 92, in train
    self.model.fit(shuffled_X, shuffled_y, **kwargs)
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/keras/models.py", line 856, in fit
    initial_epoch=initial_epoch)
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/keras/engine/training.py", line 1498, in fit
    initial_epoch=initial_epoch)
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/keras/engine/training.py", line 1152, in _fit_loop
    outs = f(ins_batch)
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2229, in __call__
    feed_dict=feed_dict)
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/Users/rayman/virtualenvs/RT/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 933, in _run
    + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("masking_1_input:0", shape=(?, 3, 24), dtype=float32) is not an element of this graph.
[08/Nov/2017 09:03:30] "GET /3/process_training/ HTTP/1.1" 500 175964
```

P.S : Raising issue in rasa_core after closing in rasa_nlu because it felt more relevant to core.

**Comment by afghani-iitkgp** [comment]
> I'm having the same issue with Keras and Tensorflow. Although I'm using Flask instead of Django. I expose a training model service: the first request goes smoothly, but if I send another request I get the "Cannot interpret feed_dict key as Tensor" error.
> 
> EDIT: seems that the problem is related to threading mechanism. If I run the app single-threaded (threaded=False in flask), subsequent requestes work as expected

It occurred same with me too. May I know the reasons?
what `threaded=False` does here?

**Comment by umohangopikrishna** [comment]
The above issue can be sort out by following the below steps

 step 1 :- write the logic of the model
 step 2 :- save the model using the method modelobj.save('model.h5')
 step3 :-  import tensorflow as tf  , graph = tf.get_default_graph()
step4 :-   
       with graph.as_default():    
            modelloadedObj = load_model('model.h5')
            img = Image.load("image url")
            
            predict = modelloadedObj .predict_classes(img)
 

it working ... :-)
