### ISSUE TITLE
Rasa Core throwing error

### ISSUE THREAD

**Issue by bikashkumars** [RasaHQ/rasa_nlu#3115]
While running Rasa Core, i am getting this Error

rasa_core.exceptions.UnsupportedDialogueModelError: The model version is to old to be loaded by this Rasa Core instance. Either retrain the model, or run withan older version. Model version: 0.11.3 Instance version: 0.12.2 Minimal compatible version: 0.12.0

Before running rasa core, i have done NLU run and Core Run
python -m rasa_nlu.train -c nlu_config.yml --data nlu.md -o models --fixed_model_name nlu --project current --verbose

Then
python -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue

pip show rasa_core
Rasa Core - Version: 0.12.2

pip show rasa_nlu
0.13.8

pip show tensorflow
Version: 1.10.0

Do i need to down-grade rasa_core to 0.11 ?

**Comment by anilpankaj** [comment]
> The solution to this is just retrain your model with 0.12

how to retrain model 
i am stuck on that problem that's i mention below

Traceback (most recent call last):
  File "testing.py", line 5, in <module>
    agent = Agent.load('models/dialogue', interpreter='/home/anil/Documents/slackbot/models/dialogue')
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_core/agent.py", line 291, in load
    action_endpoint=action_endpoint)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_core/agent.py", line 228, in __init__
    self.interpreter = NaturalLanguageInterpreter.create(interpreter)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 34, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 234, in __init__
    self._load_interpreter()
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 257, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 290, in load
    Interpreter.ensure_model_compatibility(model_metadata)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 273, in ensure_model_compatibility
    "".format(model_version, rasa_nlu.__version__))
rasa_nlu.model.UnsupportedModelError: The model version is to old to be loaded by this Rasa NLU instance. Either retrain the model, or run withan older version. Model version: 0.0.0 Instance version: 0.14.6
