### ISSUE TITLE
run custom action

### ISSUE THREAD

**Issue by soundaraj** [RasaHQ/rasa_nlu#3132]
**rasa_core** = 0.13.4
**rasa_nlu** = 0.14.6
**python** = 3.6
**os** = ubuntu 18.4

> rasa_core.processor

  - Encountered an exception while running action 'action_question'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2019-03-23 12:29:16 DEBUG    rasa_core.processor  - 'coroutine' object has no attribute 'status_code'
Traceback (most recent call last):
  File "/home/aarbor03/.local/lib/python3.6/site-packages/rasa_core/processor.py", line 346, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/aarbor03/.local/lib/python3.6/site-packages/rasa_core/actions/action.py", line 333, in run
    if response.status_code == 400:
AttributeError: 'coroutine' object has no attribute 'status_code'
2019-03-23 12:29:16 WARNING  py.warnings  - /home/aarbor03/.local/lib/python3.6/site-packages/rasa_core/processor.py:358: RuntimeWarning: coroutine 'EndpointConfig.request' was never awaited
  events = []

2019-03-23 12:29:16 DEBUG    rasa_core.processor  - Action 'action_question' ended with events '[]'
2019-03-23 12:29:16 DEBUG    rasa_core.policies.memoization  - Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'slot_qval_0': 1.0, 'intent_question': 1.0, 'entity_qval': 1.0, 'prev_action_listen': 1.0}, {'prev_action_question': 1.0, 'slot_qval_0': 1.0, 'intent_question': 1.0, 'entity_qval': 1.0}]
2019-03-23 12:29:16 DEBUG    rasa_core.policies.memoization  - There is a memorised next action '0'
2019-03-23 12:29:16 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_0_MemoizationPolicy
2019-03-23 12:29:16 DEBUG    rasa_core.processor  - Predicted next action 'action_listen' with prob 1.00.
2019-03-23 12:29:16 DEBUG    rasa_core.processor  - Action 'action_listen' ended with events '[]'

**Comment by akelad** [comment]
Thanks for raising this issue, @amn41  will get back to you about it soon.

**Comment by amn41** [comment]
thanks for raising this @soundaraj  
1. could you please also share a minimal action which reproduces this error? 
2. which version of rasa_core_sdk do you have installed?

**Comment by soundaraj** [comment]
I am using current new version,but Facebook channel not connected,so i downgrade the rasa version,i am changed many changes in rasa broker and utils code,so i am getting this error,now i am fixed, thanks guys

**Comment by soundaraj** [comment]
You can help to connect bot to twitter channel,pls help

**Comment by amn41** [comment]
there is currently no connector for twitter messages, but you could create one! (there may be others in the community who want to do so). Please create a separate issue with this suggestion, and I'll close this issue.
