### ISSUE TITLE
[Bug] Typo: 'Namespace' object has no attribute 'cors'

### ISSUE THREAD

**Issue by Spenhouet** [RasaHQ/rasa_nlu#3143]
**Rasa version**: Current master, 0.15.0a5
**Python version**: 3.6
**Operating system** (windows, osx, ...): Windows 10

**Issue**:

```
Traceback (most recent call last):
  File "C:\Users\spe\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\spe\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\dev\ppm-chatbot\rasa_nlu\rasa\core\train.py", line 246, in <module>
    main()
  File "C:\dev\ppm-chatbot\rasa_nlu\rasa\core\train.py", line 237, in main
    additional_args)
  File "C:\dev\ppm-chatbot\rasa_nlu\rasa\core\train.py", line 199, in do_interactive_learning
    if cmdline_args.cors and cmdline_args.finetune:
AttributeError: 'Namespace' object has no attribute 'cors'
```

Looks like a simple typo in `rasa\core\train.py` line `199`:

`if cmdline_args.cors and cmdline_args.finetune:`

Should be:

`if cmdline_args.core and cmdline_args.finetune:`

**Comment by saideepchandg** [comment]
using latest docker image `rasa/rasa_core:latest` but facing similar issue when training:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/rasa/core/train.py", line 246, in <module>
    main()
  File "/app/rasa/core/train.py", line 237, in main
    additional_args)
  File "/app/rasa/core/train.py", line 199, in do_interactive_learning
    if cmdline_args.cors and cmdline_args.finetune:
AttributeError: 'Namespace' object has no attribute 'cors'
```
