### ISSUE TITLE
ModuleNotFoundError: No module named 'action'

### ISSUE THREAD

**Issue by tiwo19** [RasaHQ/rasa_nlu#3156]
**Rasa version**:

**Python version 3.6 

**Operating system** (windows, 10 ...):

(env) C:\Users\damipe\Desktop\College_bot>python -m rasa_core_sdk.endpoint --action action
INFO:__main__:Starting action endpoint server...
ERROR:rasa_core_sdk.executor:Failed to register package 'action'.
Traceback (most recent call last):
  File "C:\Users\damipe\Desktop\env\lib\site-packages\rasa_core_sdk\executor.py", line 144, in register_package
    self._import_submodules(package)
  File "C:\Users\damipe\Desktop\env\lib\site-packages\rasa_core_sdk\executor.py", line 131, in _import_submodules
    package = importlib.import_module(package)
  File "C:\Users\damipe\Desktop\env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'action'
INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)

Am confused please can anyone help me quick please

**Comment by sreeramkeerthan27** [comment]
anyone found the solution
