### ISSUE TITLE
Exception: Failed to execute custom action.

### ISSUE THREAD

**Issue by tiwo19** [RasaHQ/rasa_nlu#3157]
Rasa Core version:0.13.2

Python version: python3.6.8

Operating system (windows, osx, ...):win10

Issue:
 -----------
2019-03-26 21:21:44 DEBUG    urllib3.connectionpool  - Starting new HTTP connection (1): localhost
2019-03-26 21:21:46 DEBUG    rasa_core.tracker_store  - Recreating tracker for id 'default'
2019-03-26 21:21:46 DEBUG    rasa_core.actions.action  - Calling action endpoint to run action 'actions.GetJabuinfo'.
2019-03-26 21:21:46 DEBUG    urllib3.connectionpool  - Starting new HTTP connection (1): localhost
2019-03-26 21:21:47 DEBUG    urllib3.connectionpool  - http://localhost:5055 "POST /webhook HTTP/1.1" 500 290
2019-03-26 21:21:47 ERROR    rasa_core.actions.action  - Failed to run custom action 'actions.GetJabuinfo'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
2019-03-26 21:21:47 ERROR    rasa_core.processor  - Encountered an exception while running action 'actions.GetJabuinfo'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2019-03-26 21:21:47 ERROR    rasa_core.processor  - Failed to execute custom action.
Traceback (most recent call last):
  File "C:\Users\damipe\Desktop\env\lib\site-packages\rasa_core\actions\action.py", line 313, in run
    response.raise_for_status()
  File "C:\Users\damipe\Desktop\env\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\damipe\Desktop\env\lib\site-packages\rasa_core\processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "C:\Users\damipe\Desktop\env\lib\site-packages\rasa_core\actions\action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.

**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline: "tensorflow_embedding"
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
slots:
  group:
    type: text

intents:
 - greeting
 - get_jabu
 


entities:
 - product
 - jabuinfo

templates:
  utter_greet:
    - "Hello! What can I do for you?"

actions:
 - utter_greet
 - actions.GetJabuinfo


```

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by tiwo19** [comment]
@erohmensing i fixed issue by creating new file by naming it action.py

**Comment by tiwo19** [comment]
i can close the issue now .

**Comment by tiwo19** [comment]
I have not fixed this issue please can please help me i have mistaken it for issue i previously had

**Comment by tiwo19** [comment]
can any one help

**Comment by tiwo19** [comment]
hey is my endpiont.yml file
 action_endpoint:
  url: http://localhost:5055/webhook

# nlg:
#   url: http://localhost:5056/nlg

core_endpoint:
  url: http://localhost:5005

**Comment by erohmensing** [comment]
Hi @tiwo19, when you start your action server, are you passing the `--actions` flag to it? What does your`GetJabuinfo` action do?

**Comment by tiwo19** [comment]
i will paste the for you @erohmensing i wanted GetJabuinfo to paste information on the screen. please am new to this and am working on  school project .
This is the code.
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from rasa_core.actions.action import Action
from rasa_core.events import SlotSet
import requests
from rasa_core_sdk import Action
from rasa_core_sdk.events import SlotSet



class GetJabuinfo(Action):
    def name(self):
        return "get_jabu_info"
    def run(self, dispatcher, tracker, domain):
        jabuinfo = tracker.get_slot('jabuinfo')
        response = """The Joseph Ayo Babalola University (JABU) is a private Nigerian university located in Ikeji-Arakeji in Osun State, established by the Christ Apostolic Church (CAC) Worldwide. The university is named after the first Spiritual leader of Christ Apostolic Church, Joseph Ayo Babalola (1904–1959); it is located at the place where he was called by God to slay the Ogobungo ogre in 1928. Joseph Ayo Babalola University is a fully residential institution. The university offers courses in the following colleges; Agricultural Sciences, Environmental Sciences, Humanities, Law, Management Sciences, Natural Sciences and Social Sciences. Due to its Christian foundations, male and female in the school are enjoined to adopt an extremely modest mode of dressing while on campus."""
        dispatcher.utter_message(response)
        return [SlotSet('jabuinfo',jabuinfo)]

**Comment by tiwo19** [comment]
First of all am trying to create a action.py that draws in information from my local DB which am confused about .so i just pasted the information i wanted on action.py  and dispatcher.utter to display information.
Thank you.

**Comment by erohmensing** [comment]
Ah I see, so although this action is just an utterance, it's eventually going to pull from a db, which is why its an action. That makes sense :) the first issue that I'm seeing is that you're calling `jabuinfo = tracker.get_slot('jabuinfo')` but you don't have a `jabuinfo` slot in your domain file. The same with `SlotSet('jabuinfo', jabuinfo)`. If you take these out, does the action run?

**Comment by tiwo19** [comment]
ok i will do just that

**Comment by erohmensing** [comment]
Let me know if it works -- this isn't a long term solution because you won't have an input to tell your action what to look up in the database. But good to check if the bot will actually utter the info 😃

**Comment by tiwo19** [comment]
i still get this error
 -----------
2019-03-27 17:59:25 DEBUG    urllib3.connectionpool  - Starting new HTTP connection (1): localhost
2019-03-27 17:59:26 DEBUG    rasa_core.tracker_store  - Recreating tracker for id 'default'
2019-03-27 17:59:26 DEBUG    rasa_core.actions.action  - Calling action endpoint to run action 'actions.GetJabuinfo'.
2019-03-27 17:59:26 DEBUG    urllib3.connectionpool  - Starting new HTTP connection (1): localhost
2019-03-27 17:59:27 DEBUG    urllib3.connectionpool  - http://localhost:5055 "POST /webhook HTTP/1.1" 500 290
2019-03-27 17:59:27 ERROR    rasa_core.actions.action  - Failed to run custom action 'actions.GetJabuinfo'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
2019-03-27 17:59:27 ERROR    rasa_core.processor  - Encountered an exception while running action 'actions.GetJabuinfo'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2019-03-27 17:59:27 ERROR    rasa_core.processor  - Failed to execute custom action.
thak you

**Comment by erohmensing** [comment]
what command are you using to set up your action server?

**Comment by tiwo19** [comment]
python -m rasa_core_sdk.endpoint --actions actions

**Comment by erohmensing** [comment]
Hm. Are you getting errors in the action server window?

**Comment by tiwo19** [comment]
[College_bot.zip](https://github.com/RasaHQ/rasa_nlu/files/3014539/College_bot.zip)
This is my project folder you can review it i dont what could be wrong i think action.py  domian.yml , data.json and story.md

**Comment by tiwo19** [comment]
no am not as per now

**Comment by tiwo19** [comment]
> Hm. Are you getting errors in the action server window?

No

**Comment by erohmensing** [comment]
From your zip, it looks like your action is returning the class, it should return `[]`. [Here](https://github.com/RasaHQ/rasa-demo/blob/master/demo/actions.py#L339-L355) is an example of an action that only utters something. But there are other problems that will likely stop it from working: your `"get_jabu_info"` action is also not listed in your domain file, nor in your stories. Your domain file has syntax errors (you can use [YAMLlint](http://www.yamllint.com/) to check for these). 

Overall, these are all usage errors, which don't belong on GitHub -- please get help with usage on our [Community Forum](https://forum.rasa.com/). In your case, I would start from scratch and implement things (new intents, new actions, etc.) one by one with the help of our docs, as it seems that there are a lot of issues in your code stopping this from working. If you have issues then, ask for help on the forum. :)

**Comment by shreemanraja** [comment]
please anyone help me with this error 
ERROR    rasa.core.processor  - Encountered an exception while running action 'action_hello_world'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "c:\users\drago\appdata\local\programs\python\python37\lib\site-packages\rasa\core\processor.py", line 773, in _run_action
    output_channel, nlg, temporary_tracker, self.domain
  File "c:\users\drago\appdata\local\programs\python\python37\lib\site-packages\rasa\core\actions\action.py", line 671, in run
    f"Failed to execute custom action '{self.name()}' "
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_hello_world' because no endpoint is configured to run this custom action. Please take a look at the docs and set an endpoint configuration via the --endpoints flag. https://rasa.com/docs/rasa/custom-actions
