### ISSUE TITLE
spacy_sklearn don´t train

### ISSUE THREAD

**Issue by Robertjbc** [RasaHQ/rasa_nlu#3171]
**Rasa core version:      0.13.5**: nlu version:  rasa-nlu            0.14.6

**3.6**: 

windows 10:

my issue is y try to train my nlu model with spacy_sklearn but the cmd show me this error 

`py -m rasa_nlu.train -c nlu_config.yml --data nlu.md -o models --fixed_model_name nlu --project current --verbose
2019-03-28 16:15:36 INFO     rasa_nlu.utils.spacy_utils  - Trying to load spacy model with name 'en'
Traceback (most recent call last):
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\train.py", line 184, in <module>
    num_threads=cmdline_args.num_threads)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\train.py", line 148, in do_train
    trainer = Trainer(cfg, component_builder)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\model.py", line 155, in __init__
    self.pipeline = self._build_pipeline(cfg, component_builder)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\model.py", line 166, in _build_pipeline
    component_name, cfg)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\components.py", line 441, in create_component
    cfg)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\registry.py", line 142, in create_component_by_name
    return component_clz.create(config)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\utils\spacy_utils.py", line 73, in create
    nlp = spacy.load(spacy_model_name, parser=False)
AttributeError: module 'spacy' has no attribute 'load'
`

if any have a solution i´ll appreciate it 

regards 😉

**Comment by akelad** [comment]
could it be that you have an old spacy version installed? can you paste the output of `pip show spacy`?

**Comment by Robertjbc** [comment]
i can solve it, only upgrade the spacy but it´s strange because i upgrade before
well thank for the answers 

regards 
😉
