### ISSUE TITLE
issue while train rasa_core, I am getting this issue while running train_init.py

### ISSUE THREAD

**Issue by garchaaman19** [RasaHQ/rasa_nlu#3219]
**Rasa version**:0.13.7
rasa sdk 0.12.2

**Python version**: 3.6.0

**Operating system** (windows, osx, ...):kali linux 2019

**Issue**:
Traceback (most recent call last):
  File "train_init.py", line 37, in <module>
    run_chatbot_online(nlu_interpreter)
  File "train_init.py", line 25, in run_chatbot_online
    action_endpoint=action_endpoint)
  File "/root/anaconda3/lib/python3.6/site-packages/rasa_core/agent.py", line 193, in __init__
    self.domain = self._create_domain(domain)
  File "/root/anaconda3/lib/python3.6/site-packages/rasa_core/agent.py", line 648, in _create_domain
    return Domain.load(domain)
  File "/root/anaconda3/lib/python3.6/site-packages/rasa_core/domain.py", line 88, in load
    return cls.from_yaml(read_file(filename))
  File "/root/anaconda3/lib/python3.6/site-packages/rasa_core/domain.py", line 92, in from_yaml
    cls.validate_domain_yaml(yaml)
  File "/root/anaconda3/lib/python3.6/site-packages/rasa_core/domain.py", line 170, in validate_domain_yaml
    source_data = utils.read_yaml_string(yaml)
  File "/root/anaconda3/lib/python3.6/site-packages/rasa_core/utils.py", line 327, in read_yaml_string
    return yaml_parser.load(string)
  File "/root/anaconda3/lib/python3.6/site-packages/ruamel/yaml/main.py", line 331, in load
    return constructor.get_single_data()
  File "/root/anaconda3/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 731, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 2, column 1
could not find expected ':'
  in "<unicode string>", line 3, column 1

**Content of configuration file (config.yml)**:
```yml

{
"pipeline":"spacy_sklearn",
"path":"./models/nlu",
"data":"./data/data.json"
}
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
intents:
-new_admission
-greet
-goodbye
-affirm
-intro
-inform_fees
-inform_placements
-events
-health
-entrance_exam
-question_paper_entrance
-college_timings
-calculate_distance
entites:
-stream
-location
templates:
utter_greet:
-'Hello how can i help you'
-'Hey there'
-'Hi how can i help you'
-'Hi buddy'
-'hello'
-'hey buddy'
utter_goodbye:
-'ok bye :('
-'bye have a nice day'
-'bye talk to you later'
-'bye have a nice day'
-'have a good day ahead'
utter_affirm:
-'okayy'
-'cool'
-'chill'
-'i got that'
utter_intro:
-'I am a chatbot to answer your queries related to college admission,placements,fees,etc'
-'I am a chatbot created by HARVINDAR SINGH GARCHA to answer queries related to college'
utter_inform_fees:
-'for fees related enquiries please visit www.moderncollege.edu.in'
utter_events:
-'We have a good record of conducting co-curricular activities'
-'We have big events as well as separated department events'
-'Co-curricular activities in our college help students to reduce study load which are organized properly every year'
utter_health:
-'I am good Buddy,you say'
-'I am doing well today'
-'Life is always good'
-'I am fine'
-'I am cool'
utter_ask_stream:
-'Please specify me the stream'
-'Please tell me the stream such as mba,bcs,mcs,msc etc.'
actions: 
- utter_greet
- utter_goodbye
- utter_affirm


```

**Comment by akelad** [comment]
@garchaaman19 json config for NLU is no longer supported. Can you change it to the yaml format (you can find info in our docs) and let me know if that fixes your error?

**Comment by garchaaman19** [comment]
thank you for reply,
Actually i had not given spaces in domain.yml file so it was throwing me that error, now its throwing me some warnings in action files which i am checking.
so should i change from .json to yml?

**Comment by garchaaman19** [comment]
thank you for reply,
Actually i had not given spaces in domain.yml file so it was throwing me that error, now its throwing me some warnings in action files which i am checking.
so should i change from .json to yml?

**Comment by garchaaman19** [comment]
the error is solved as i had not given proper spaces, my action part is not working properly after the bot is loaded i.e not proper response. I will raise a new issue for this if required.
Thank you.
