### ISSUE TITLE
French using new Spacy's language model

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_nlu#376]
Spacy has a French model since 1.8.2 (https://spacy.io/docs/usage/models).
How hard would it be to support French in Rasa?

**Comment by tmbo** [comment]
it should be as easy as setting `"language": "fr", "spacy_model_name": "fr_depvec_web_lg"` in your configuration. any issue with that?

**Comment by znat** [comment]
That's good news! There is still a dependency on #284, right?

**Comment by tmbo** [comment]
Since we removed entity training using spacy all together (one should use the `ner_crf` component instead), I don't think this should be an issue anymore. Didn't try it yet though.

**Comment by znat** [comment]
I will this afternoon and I'll let you know here how it goes. Thanks

**Comment by tmbo** [comment]
@znat that would be awesome, thanks.

**Comment by znat** [comment]
@tmbo , when training (from python directly), I have the following error:
```
Traceback (most recent call last):
  File "/Users/nzylber1/git/ww_training/prepare.py", line 197, in <module>
    model_dir = train(train_set)
  File "/Users/nzylber1/git/ww_training/prepare.py", line 134, in train
    trainer.train(training_data)
  File "/Users/nzylber1/anaconda/envs/rasa/lib/python2.7/site-packages/rasa_nlu/model.py", line 157, in train
    updates = component.train(*args)
  File "/Users/nzylber1/anaconda/envs/rasa/lib/python2.7/site-packages/rasa_nlu/extractors/crf_entity_extractor.py", line 78, in train
    dataset = [self._from_json_to_crf(q, spacy_nlp) for q in train_data]
  File "/Users/nzylber1/anaconda/envs/rasa/lib/python2.7/site-packages/rasa_nlu/extractors/crf_entity_extractor.py", line 262, in _from_json_to_crf
    doc = spacy_nlp(json_eg[0])
  File "/Users/nzylber1/anaconda/envs/rasa/lib/python2.7/site-packages/spacy/language.py", line 350, in __call__
    proc(doc)
  File "spacy/tagger.pyx", line 205, in spacy.tagger.Tagger.__call__ (spacy/tagger.cpp:6251)
  File "spacy/morphology.pyx", line 78, in spacy.morphology.Morphology.assign_tag_id (spacy/morphology.cpp:4693)
KeyError: 139255

```

**Comment by tmbo** [comment]
@znat is that using the french model?

**Comment by znat** [comment]
@tmbo Tes!

Le jeu. 18 mai 2017 5:03 p.m., Tom Bocklisch <notifications@github.com> a
écrit :

**Comment by tmbo** [comment]
But you didn't modify that model right? So this seems to be more of an issue on the spacy end but it would be interesting to know which sentence it fails on.

**Comment by znat** [comment]
After further investigation, it's related to the diverted way I use synonyms. Let me explain. I'm parsing search queries into `what` and `where` ("looking for a *plumber* in *Montreal*").  `where` could be a city, or a neighborhood. Many exists in several provinces (there are 7 "Westmount" in Canada). So the synonym value is a stringified array of all possible results. So to boot synonyms, I start the training with utterances like (those break Spacy in FR only, but are fine in EN):
```
 {
        "text": "I'm looking for a vehicle towing in [\"Westmount, Vaughan, ON\", \"Westmount, Edmonton, AB\", \"Westmount, West Vancouver, BC\", \"Westmount, NS\", \"Westmount, Toronto, ON\", \"Westmount, Montréal, QC\", \"Westmount, Saskatoon, SK\"]", 
        "entities": [
            {
                "start": 18, 
                "end": 32, 
                "value": "vehicle towing", 
                "entity": "what"
            }, 
            {
                "start": 36, 
                "end": 220, 
                "value": "[\"Westmount, Vaughan, ON\", \"Westmount, Edmonton, AB\", \"Westmount, West Vancouver, BC\", \"Westmount, NS\", \"Westmount, Toronto, ON\", \"Westmount, Montréal, QC\", \"Westmount, Saskatoon, SK\"]", 
                "entity": "where"
            }
        ]
    }, 
```

Then I feed normal examples and map them to synonym values (which Spacy is happy about):

```
 {
        "text": "I'm looking for a vehicle towing in Westmount", 
        "entities": [
            {
                "start": 18, 
                "end": 32, 
                "value": "vehicle towing", 
                "entity": "what"
            }, 
            {
                "start": 36, 
                "end": 220, 
                "value": "[\"Westmount, Vaughan, ON\", \"Westmount, Edmonton, AB\", \"Westmount, West Vancouver, BC\", \"Westmount, NS\", \"Westmount, Toronto, ON\", \"Westmount, Montréal, QC\", \"Westmount, Saskatoon, SK\"]", 
                "entity": "where"
            }
        ]
    }, 
```

I can't really say it's a bug then.

In the process of debugging this I realized I don't need to *boot* synonyms as shown above. Feeding normal examples is enough as long as I make sure every `where` value is trained at least once.  
Accuracy looks similar but I can't measure it precisely yet because of #355 
So I'm closing.

**Comment by tmbo** [comment]
right - that makes sense - thanks for adding that to the issue for future reference. there is actually a PR open that will allow to specify all the synonyms at once - without adding examples for each of them (isn't ready to merge yet though).

**Comment by znat** [comment]
Reopening because I still have the error in French. Thousands of examples work fine and then one of those fails (those are the last ones, not sure if the last printed is the one causing the error)

```
{'text': u'je cherche une boutiques \xe0 place longueuil', 'entities': [{'start': 15, 'end': 24, 'value': u'boutiques', 'entity': 'what'}, {'start': 27, 'end': 42, 'value': u'["Place Longueuil, Longueuil, QC"]', 'entity': 'where'}]}
{'text': u'Y a-t-il un boutiques \xe9rotiques pres de Opasquia', 'entities': [{'start': 12, 'end': 31, 'value': u'boutiques \xe9rotiques', 'entity': 'what'}, {'start': 40, 'end': 48, 'value': u'["Opasquia, ON"]', 'entity': 'where'}]}
{'text': u'je cherche un boutiques \xe9rotiques vers opasquia', 'entities': [{'start': 14, 'end': 33, 'value': u'boutiques \xe9rotiques', 'entity': 'what'}, {'start': 39, 'end': 47, 'value': u'["Opasquia, ON"]', 'entity': 'where'}]}
{'text': u'envie de magasins de gros appareils \xe9lectrom\xe9nagers a Ajax Southwest', 'entities': [{'start': 9, 'end': 51, 'value': u'magasins de gros appareils \xe9lectrom\xe9nagers', 'entity': 'what'}, {'start': 54, 'end': 68, 'value': u'["Southwest Ajax, Ajax, ON"]', 'entity': 'where'}]}
{'text': u'cherche magasins de gros appareils \xe9lectrom\xe9nagers pres de ajax southwest', 'entities': [{'start': 8, 'end': 50, 'value': u'magasins de gros appareils \xe9lectrom\xe9nagers', 'entity': 'what'}, {'start': 59, 'end': 73, 'value': u'["Southwest Ajax, Ajax, ON"]', 'entity': 'where'}]}
{'text': u'travailleurs sociaux autour de Les Basques', 'entities': [{'start': 0, 'end': 20, 'value': u'travailleurs sociaux', 'entity': 'what'}, {'start': 31, 'end': 42, 'value': u'["Les Basques, QC"]', 'entity': 'where'}]}
{'text': u'cherche des travailleurs sociaux pres de les basques', 'entities': [{'start': 12, 'end': 32, 'value': u'travailleurs sociaux', 'entity': 'what'}, {'start': 41, 'end': 52, 'value': u'["Les Basques, QC"]', 'entity': 'where'}]}
{'text': u'je cherche une massoth\xe9rapeutes vers Randolph', 'entities': [{'start': 15, 'end': 31, 'value': u'massoth\xe9rapeutes', 'entity': 'what'}, {'start': 37, 'end': 45, 'value': u'["Randolph, MB"]', 'entity': 'where'}]}
{'text': u'massoth\xe9rapeutes randolph', 'entities': [{'start': 0, 'end': 16, 'value': u'massoth\xe9rapeutes', 'entity': 'what'}, {'start': 17, 'end': 25, 'value': u'["Randolph, MB"]', 'entity': 'where'}]}
{'text': u"besoin d'une toilettage & tonte d'animaux domestiques a Lenore", 'entities': [{'start': 13, 'end': 53, 'value': u"toilettage & tonte d'animaux domestiques", 'entity': 'what'}, {'start': 56, 'end': 62, 'value': u'["Lenore, MB"]', 'entity': 'where'}]}
{'text': u"cherche une toilettage & tonte d'animaux domestiques vers lenore", 'entities': [{'start': 12, 'end': 52, 'value': u"toilettage & tonte d'animaux domestiques", 'entity': 'what'}, {'start': 58, 'end': 64, 'value': u'["Lenore, MB"]', 'entity': 'where'}]}
{'text': u'Y a-t-il un entrepreneurs en b\xe9ton pres de Saint  James Town', 'entities': [{'start': 12, 'end': 34, 'value': u'entrepreneurs en b\xe9ton', 'entity': 'what'}, {'start': 43, 'end': 60, 'value': u'["Saint  James Town, Toronto, ON"]', 'entity': 'where'}]}

```

Any idea what the cause could be?

**Comment by tmbo** [comment]
What is the error?

**Comment by znat** [comment]
Same as above.
```
Traceback (most recent call last):
  File "/Users/nzylber1/git/ww_training/trainer.py", line 214, in <module>
    model_dir = train(train_set)
  File "/Users/nzylber1/git/ww_training/trainer.py", line 143, in train
    "common_examples": [example]
  File "/Users/nzylber1/anaconda/envs/rasa/lib/python2.7/site-packages/rasa_nlu/model.py", line 159, in train
    updates = component.train(*args)
  File "/Users/nzylber1/anaconda/envs/rasa/lib/python2.7/site-packages/rasa_nlu/extractors/crf_entity_extractor.py", line 78, in train
    dataset = [self._from_json_to_crf(q, spacy_nlp) for q in train_data]
  File "/Users/nzylber1/anaconda/envs/rasa/lib/python2.7/site-packages/rasa_nlu/extractors/crf_entity_extractor.py", line 262, in _from_json_to_crf
    doc = spacy_nlp(json_eg[0])
  File "/Users/nzylber1/anaconda/envs/rasa/lib/python2.7/site-packages/spacy/language.py", line 350, in __call__
    proc(doc)
  File "spacy/tagger.pyx", line 205, in spacy.tagger.Tagger.__call__ (spacy/tagger.cpp:6251)
  File "spacy/morphology.pyx", line 78, in spacy.morphology.Morphology.assign_tag_id (spacy/morphology.cpp:4693)
KeyError: 139255

```

Not sure how this could related (event if it's a fixed issue) https://github.com/explosion/spaCy/issues/665

**Comment by tmbo** [comment]
Ok, I'd suggest the following (this doesn't seem to be an issue with rasa but rather this looks like an issue with the pretrained spacy model):
- wrap the line `doc = spacy_nlp(json_eg[0])` in `crf_entity_extractor.py`, line 262 with a try & except block and log the input `json_eg[0]` that is causing the error. 
- open the python console, load the french spacy model and pass in the phrase that resulted in the exception

Can you do that, or do you need help with that?

**Comment by znat** [comment]
Sure, I'll do that when I'm back to work on Tuesday. Thanks!

Le sam. 20 mai 2017 6:59 a.m., Tom Bocklisch <notifications@github.com> a
écrit :

**Comment by znat** [comment]
Hi @tmbo, so here is the error:

Sentence:**"Y a-t-il une poissonerie proche de North East  Airdrie"**
Note the 2 spaces between East and Airdrie.
It happens to any sentence where an entity has 2 spaces. Preprocessing data to remove double spaces fixes the issue, however I don't think 2 spaces should break so I'll let you decide what to do with this issue. Thanks again 

```
    model_dir = train(train_set)
  File "/Users/nzylber1/git/ww_training/trainer.py", line 142, in train
    "common_examples": [example]
  File "/Users/nzylber1/anaconda/envs/rasa/lib/python2.7/site-packages/rasa_nlu/model.py", line 159, in train
    updates = component.train(*args)
  File "/Users/nzylber1/anaconda/envs/rasa/lib/python2.7/site-packages/rasa_nlu/extractors/crf_entity_extractor.py", line 78, in train
    dataset = [self._from_json_to_crf(q, spacy_nlp) for q in train_data]
  File "/Users/nzylber1/anaconda/envs/rasa/lib/python2.7/site-packages/rasa_nlu/extractors/crf_entity_extractor.py", line 266, in _from_json_to_crf
    print("Error:" + e)
TypeError: coercing to Unicode: need string or buffer, exceptions.KeyError found
```

**Comment by tmbo** [comment]
Alright, I had a look at the spacing issue and there is a spacy issue that is responsible for the behaviour. https://github.com/explosion/spaCy/issues/1052

I will close this issue, as there is nothing we can do about it.

**Comment by nicolaspernoud** [comment]
Hello,

Would it be possible to add to documentation how to change langage (to french) with the docker container ?

Thanks,
