### ISSUE TITLE
"Not all required packages are installed" (sklearn-crfsuite missing)

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_nlu#389]
**rasa NLU version** (e.g. `0.7.3`): latest master May 23rd

`sklearn-crfsuite` seem to be missing in dependencies
```
ERROR:root:Failed to load model 'current'. Error: Not all required packages are installed. To use this pipeline, run
	> pip install sklearn-crfsuite==0.3.5 scikit-learn==0.18.1 scipy==0.19.0
Traceback (most recent call last):
  File "/app/rasa_nlu/data_router.py", line 87, in __create_model_store
    model_store[alias] = self.__interpreter_for_model(model_path)
  File "/app/rasa_nlu/data_router.py", line 71, in __interpreter_for_model
    return Interpreter.load(metadata, self.config, self.component_builder)
  File "/app/rasa_nlu/model.py", line 226, in load
    components.validate_requirements(meta.pipeline)
  File "/app/rasa_nlu/components.py", line 110, in validate_requirements
    "> pip install {}".format(" ".join(missing_requirements)))
Exception: Not all required packages are installed. To use this pipeline, run
	> pip install sklearn-crfsuite==0.3.5 scikit-learn==0.18.1 scipy==0.19.0

```

**Comment by tmbo** [comment]
No this is expected. The pip and local install cover only dependencies that we need all the time - some of the components in the processing pipelines do have additional dependencies though. If you really want to install everything, you can run `pip install -r dev_requirements.txt`.

**Comment by wrathagom** [comment]
Beat me to it :(

Since the RASA folks don't know which back end you will use they don't assume to install any libraries that aren't required. You can either install them selectively based on the pipeline you are using or blanket install everything with the dev-requirements file.

See the note on this page https://rasa-nlu.readthedocs.io/en/latest/installation.html#setting-up-rasa-nlu

**Comment by tmbo** [comment]
😉

**Comment by znat** [comment]
Makes sense. 
I know it can be pip installed or added to the `requirements.txt`, but since I got this error after pulling from master without changing anything else,  I thought it might be worth reporting. 
I suppose `ner_crf` has a new depency on `sklearn-crfsuite`, so since my pipeline is only `["nlp_spacy","ner_crf","ner_synonyms"]`

**Comment by tmbo** [comment]
Yes, we replaced `python-crfsuite` with `sklearn-crfsuite`.

**Comment by asmaier** [comment]
I'm following the tutorial at https://rasa.com/docs/core/quickstart/#quickstart and when running

    python -m rasa_nlu.train -c nlu_config.yml --data nlu.md -o models --fixed_model_name nlu --project current --verbose

I do get the following error

    Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install sklearn_crfsuite

Do I need to install dev-requirements to follow the quickstart tutorial?

**Comment by abhishek24007** [comment]
(venv) (base) C:\Users\achatur4\Downloads\DataScience\Rasa_basic_folder>rasa train nlu
Training NLU model...
c:\windows\system32\venv\lib\site-packages\rasa\nlu\config.py:50: FutureWarning: You are using a pipeline template. All pipelines templates are deprecated and will be removed in version 2.0. Please add the components you want to use directly to your configuration file.
  return RasaNLUModelConfig(config)
Traceback (most recent call last):
  File "C:\Users\achatur4\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\achatur4\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\WINDOWS\system32\venv\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\windows\system32\venv\lib\site-packages\rasa\__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\windows\system32\venv\lib\site-packages\rasa\cli\train.py", line 140, in train_nlu
    persist_nlu_training_data=args.persist_nlu_data,
  File "c:\windows\system32\venv\lib\site-packages\rasa\train.py", line 414, in train_nlu
    persist_nlu_training_data,
  File "C:\Users\achatur4\AppData\Local\Continuum\anaconda3\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\windows\system32\venv\lib\site-packages\rasa\train.py", line 445, in _train_nlu_async
    persist_nlu_training_data=persist_nlu_training_data,
  File "c:\windows\system32\venv\lib\site-packages\rasa\train.py", line 474, in _train_nlu_with_validated_data
    persist_nlu_training_data=persist_nlu_training_data,
  File "c:\windows\system32\venv\lib\site-packages\rasa\nlu\train.py", line 74, in train
    trainer = Trainer(nlu_config, component_builder)
  File "c:\windows\system32\venv\lib\site-packages\rasa\nlu\model.py", line 142, in __init__
    components.validate_requirements(cfg.component_names)
  File "c:\windows\system32\venv\lib\site-packages\rasa\nlu\components.py", line 59, in validate_requirements
    f"Not all required importable packages are installed. "
Exception: Not all required importable packages are installed. To use this pipeline, you need to install the missing dependencies. Please install the package(s) that contain the module(s): sklearn_crfsuite

I tried installing sklearn-crfsuite again but the issue persists.
In the venv I can see sklearn-crfsuite, scipy, scikit-learn installed .

scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.4.1
seaborn==0.10.1
Send2Trash==1.5.0
simplegeneric==0.8.1
simplejson==3.17.0
singledispatch==3.4.0.3
six==1.15.0
sklearn-crfsuite==0.3.6
slackclient==2.7.2
smmap==3.0.4
sniffio==1.1.0
snowballstemmer==2.0.0
sortedcollections==1.2.1
sortedcontainers==2.2.2
soupsieve==2.0.1
spacy==2.1.9

Any assistance will be really appreciated
