### ISSUE TITLE
[OSError]:/tmp/_MEI7VexWq/mitie/libmitie.so- cannot open shared file-no such file directory

### ISSUE THREAD

**Issue by AP8050** [RasaHQ/rasa_nlu#408]
**rasa NLU version 0.8**

**Used Backend-** mitie

**Operating system-** ubuntu

**Issue:**
I have generated executable file for rasa_nlu train.py using pyinstaller and I run the exe then I keep getting a error:

Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 144, in __init__
  File "ctypes/__init__.py", line 347, in __init__
OSError: /tmp/_MEI7VexWq/mitie/libmitie.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rasa_nlu/train.py", line 83, in <module>
  File "rasa_nlu/train.py", line 70, in do_train
  File "rasa_nlu/model.py", line 125, in __init__
  File "rasa_nlu/components.py", line 91, in validate_requirements
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/PyInstaller-3.3.dev0+5fd013bfe-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/mitie/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/PyInstaller-3.3.dev0+5fd013bfe-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/mitie/mitie.py", line 45, in <module>
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 146, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll '/tmp/_MEI7VexWq/mitie/libmitie.so'. Most probably this dynlib/dll was not found when the application was frozen.
Failed to execute script train

**Content of configuration file:**
{
  "pipeline": "mitie",
  "mitie_file": "./data/total_word_feature_extractor.dat",
  "path" : "./models",
  "data" : "./data/examples/rasa/demo-rasa.json"
}

Plz anyone help me...

**Comment by tmbo** [comment]
This seems to be an installation issue with mitie. Did you properly install mitie?

**Comment by AP8050** [comment]
yes, mitie was installed properly.The rasa_nlu trained properly by using the command "python -m rasa_nlu.train -c config_mitie.json". I generated executable file for rasa_nlu/train.py after when I try to run the executable file for training, I am getting the error which was mentioned above.

**Comment by tmbo** [comment]
I am not quite sure if this is an issue with the pyinstaller or where the root cause is yet. Have you tried running the same without the pyintaller?

**Comment by tmbo** [comment]
Let me know if this is still an issue.

**Comment by AP8050** [comment]
yes, still I am getting this error.

**Comment by AP8050** [comment]
I fixed this issue by adding libmitie.so file in directory /usr/local/lib/.

**Comment by py-ranoid** [comment]
Run `make` inside `/MITIE/`.
This generates `mitielib/libmitie.so`
