### ISSUE TITLE
Error after posting to /train

### ISSUE THREAD

**Issue by ramimanna** [RasaHQ/rasa_nlu#543]
**rasa NLU version**:
 Bleeding edge / github clone
**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
nlp_spacy, tokenizer_spacy, intent_featurizer_spacy, intent_entity_featurizer_regex, ner_crf, ner_synonyms, intent_classifier_sklearn

**Operating system**:
Linux Ubuntu 16.04
**Issue**:
When I post to /train, the model is created and saved but I get the following error.
And when i post to /parse, it's still using an old model.
```
INFO:rasa_nlu.model:Successfully saved model into '/home/rami/Desktop/chatbot/models/model_20170823-130138'
2017-08-23 13:01:38+0300 [-] "127.0.0.1" - - [23/Aug/2017:10:01:38 +0000] "POST /train HTTP/1.1" 200 52 "-" "-"
2017-08-23 13:01:38+0300 [-] Unhandled Error writing response
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1442, in gotResult
	    _inlineCallbacks(r, g, deferred)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1429, in _inlineCallbacks
	    deferred.callback(e.value)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 459, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/klein/resource.py", line 278, in write_response
	    request.finish()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 225, in finish
	    return http.Request.finish(self)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 987, in finish
	    self._cleanup()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 730, in _cleanup
	    self.channel.requestDone(self)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 2157, in requestDone
	    self.loseConnection()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 2286, in loseConnection
	    return self.transport.loseConnection()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/abstract.py", line 407, in loseConnection
	    self.stopReading()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/abstract.py", line 421, in stopReading
	    self.reactor.removeReader(self)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 172, in removeReader
	    EPOLLIN, EPOLLOUT)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 160, in _remove
	    self._poller.unregister(fd)
	exceptions.IOError: [Errno 2] No such file or directory
```

**Content of configuration file** (if used & relevant):
```json

```

**Comment by PHLF** [comment]
This is not an easy one... Could you please also post the content of your configuration file?

**Comment by ramimanna** [comment]
hey, so I'm not getting this error anymore, I believe it was to do with not having the right formatting somewhere.
I have a different problem now but I'll open another issue for it :)

**Comment by PHLF** [comment]
No this looks like a lower level issue directly related to the epoll event loop that makes me afraid of a threading issue somewhere. Could you just please post the content of your configuration file here for reference?

**Comment by ramimanna** [comment]
Okay, gotchu. As I mentioned, I'm not getting the error any more, but I'll try to reproduce it and get back to you. I believe it may have to do with changes in my configuration file.

**Comment by wrathagom** [comment]
@PHLF leave this one open? Have you been able to re-produce?

**Comment by PHLF** [comment]
Don't have access to Rasa stuff right now. I'll maybe try in a few weeks.

**Comment by tmbo** [comment]
thanks a lot @PHLF. I updated the code and created a PR - needs to be tested though. @ramimanna do you mind trying to run your example with the code from the `run-from-thread` branch (you can simply install that in the same way the installation works for the github master branch)?
