### ISSUE TITLE
Problem with n-gram featurizer

### ISSUE THREAD

**Issue by vkrgowtham** [RasaHQ/rasa_nlu#551]
**rasa NLU version** (e.g. `0.7.3`): 0.10.0a2

**Issue**: 
The model is getting trained if i remove ngram featurizer from the pipeline. With n-gram featurizer I'm getting the following problem. I have attached config and data files.

ValueError: Found array with 0 feature(s) (shape=(1028, 0)) while a minimum of 1 is required.

DEBUG:rasa_nlu.featurizers.ngram_featurizer:Started ngram cross-validation to find best number of ngrams to use...
Traceback (most recent call last):
  File "/home/gowthamv/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/gowthamv/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 96, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 86, in do_train
  File "build/bdist.linux-x86_64/egg/rasa_nlu/model.py", line 149, in train
  File "build/bdist.linux-x86_64/egg/rasa_nlu/featurizers/ngram_featurizer.py", line 66, in train
  File "build/bdist.linux-x86_64/egg/rasa_nlu/featurizers/ngram_featurizer.py", line 121, in train_on_sentences
  File "build/bdist.linux-x86_64/egg/rasa_nlu/featurizers/ngram_featurizer.py", line 308, in _cross_validation
  File "/home/gowthamv/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_validation.py", line 140, in cross_val_score
    for train, test in cv_iter)
  File "/home/gowthamv/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/gowthamv/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/gowthamv/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/gowthamv/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "/home/gowthamv/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 326, in __init__
    self.results = batch()
  File "/home/gowthamv/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/gowthamv/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_validation.py", line 238, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/gowthamv/anaconda2/lib/python2.7/site-packages/sklearn/linear_model/logistic.py", line 1173, in fit
    order="C")
  File "/home/gowthamv/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py", line 521, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "/home/gowthamv/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py", line 424, in check_array
    context))
ValueError: Found array with 0 feature(s) (shape=(1028, 0)) while a minimum of 1 is required.

[small-talk.zip](https://github.com/RasaHQ/rasa_nlu/files/1256514/small-talk.zip)
[config.zip](https://github.com/RasaHQ/rasa_nlu/files/1256516/config.zip)

**Comment by PHLF** [comment]
What is your `numpy` version?

**Comment by vkrgowtham** [comment]
numpy version is 1.12.1

**Comment by PHLF** [comment]
What is the value of the [`max_number_of_ngrams`](http://rasa-nlu.readthedocs.io/en/latest/config.html#max-number-of-ngrams) in your config file?

**Comment by vkrgowtham** [comment]
{
  "pipeline": ["nlp_mitie","nlp_spacy","tokenizer_mitie", "intent_entity_featurizer_regex","intent_featurizer_ngrams","tokenizer_spacy","ner_crf","ner_duckling","ner_spacy","ner_synonyms", "intent_featurizer_mitie", "intent_classifier_sklearn"],
  "max_number_of_ngrams":7,
  "num_threads": 1,
  "mitie_file": "total_word_feature_extractor.dat",
  "path" : "./models",
  "data" : "./data/small-talk.md",
  "response_log": "logs/",
  "duckling_dimensions": ["time","amount-of-money"],
  "log_level": "DEBUG",
  "cors_origins": ["*"]
}

**Comment by PHLF** [comment]
Got it. I think you need [to have another intent featurizer defined before the `intent_featurizer_ngrams` in your pipeline](http://rasa-nlu.readthedocs.io/en/latest/pipeline.html#intent-featurizer-ngrams)

**Comment by vkrgowtham** [comment]
Yes, thank you.
