### ISSUE TITLE
Training Model Error

### ISSUE THREAD

**Issue by joaodotneto** [RasaHQ/rasa_nlu#603]
When i try to train a model (using the tutorial at [here](http://rasa-nlu.readthedocs.io/en/stable/tutorial.html#training-your-model)) I have this error:
```
INFO:rasa_nlu.components:Couldn't read dev-requirements.txt. Error: [Errno 2] No such file or directory: 'E:\\Python\\WinPython-32bit-3.6.1.0Zero\\python-3.6.1\\lib\\site-packages\\rasa_nlu\\..\\dev-requirements.txt'
INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en'
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Traceback (most recent call last):
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\rasa_nlu\train.py", line 88, in <module>
    do_train(config)
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\rasa_nlu\train.py", line 75, in do_train
    trainer = Trainer(config, component_builder)
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\rasa_nlu\model.py", line 123, in __init__
    component = component_builder.create_component(component_name, config)
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\rasa_nlu\components.py", line 293, in create_component
    component = registry.create_component_by_name(component_name, config)
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\rasa_nlu\registry.py", line 136, in create_component_by_name
    return component_clz.create(config)
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\rasa_nlu\components.py", line 186, in create
    return cls()
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 49, in __init__
    from sklearn.preprocessing import LabelEncoder
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\sklearn\__init__.py", line 134, in <module>
    from .base import clone
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\sklearn\base.py", line 12, in <module>
    from .utils.fixes import signature
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\sklearn\utils\__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\sklearn\utils\validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\sklearn\utils\fixes.py", line 144, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .isolve import *
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py", line 6, in <module>
    from .iterative import *
  File "E:\Python\WinPython-32bit-3.6.1.0Zero\python-3.6.1\lib\site-packages\scipy\sparse\linalg\isolve\iterative.py", line 7, in <module>
    from . import _iterative
ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.
```

I've followed all steps of the tutorial. Files used are attached.
The problem occurs in raw installation of python and in WinPython (same installation sequence, same problem).

Thanks in advance and sorry my bad english
[restaurant.zip](https://github.com/RasaHQ/rasa_nlu/files/1326822/restaurant.zip)
.

**Comment by tmbo** [comment]
This looks like an installation issue with either sklearn or numpy. Did you have a look at the proposed solutions on SO (e.g. https://stackoverflow.com/questions/30766274/error-importing-scikit-learn-modules)?

**Comment by joaodotneto** [comment]
Thanks for the answer. 
I make a Linux VM to test, and works perfectly. Now i'll try your answer to see if works.

Thanks again.

**Comment by joaodotneto** [comment]
In Windows i don't find how to solve, but run in linux like a charm.
Thanks.

**Comment by PreranaPolekar** [comment]
@joaodotneto  were you able to solve this in Windows?

**Comment by joaodotneto** [comment]
@PreranaPolekar no, in windows not working. I'm using in Linux.

**Comment by PreranaPolekar** [comment]
Ok, I had to downgrade to Python 3.5 to get all the dependencies work together.
