### ISSUE TITLE
Trainer doesn't identify which file of a dialogflow import is causing trouble

### ISSUE THREAD

**Issue by mhjb** [RasaHQ/rasa_nlu#675]
**Rasa NLU version**: 0.10.4

**Used backend / pipeline**: spacy_sklearn

**Operating system**: osx 10.12.6

**Issue**:
I'm attempting to train on some data exported from dialogflow.

`$ python -m rasa_nlu.train -c ./config_spacy.json` 
has failed with the message:
`ValueError: Expecting ',' delimiter: line 15 column 830 (char 1130)`

The trouble is, with this multi-file (in this case ~1000 json files) dialogflow export, rasa_nlu.train is not telling me which of the json file is causing the problem.  

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": "spacy_sklearn",
  "path" : "./projects",
  "data" : "./Wagbot-data/"
}
```

**Comment by wrathagom** [comment]
is there a full stack trace (bigger error message) that shows up or just that error message?

**Comment by mhjb** [comment]
```
➜  Learn Rasa python -m rasa_nlu.train -c ./config_spacy.json
INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en'
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
INFO:rasa_nlu.converters:Training data format at ./Wagbot-data/ is dialogflow
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mhjb/Library/Python/2.7/lib/python/site-packages/rasa_nlu/train.py", line 125, in <module>
    do_train(config)
  File "/Users/mhjb/Library/Python/2.7/lib/python/site-packages/rasa_nlu/train.py", line 113, in do_train
    training_data = load_data(config['data'], config['language'])
  File "/Users/mhjb/Library/Python/2.7/lib/python/site-packages/rasa_nlu/converters.py", line 326, in load_data
    return load_dialogflow_data(files, language)
  File "/Users/mhjb/Library/Python/2.7/lib/python/site-packages/rasa_nlu/converters.py", line 47, in load_dialogflow_data
    root_f_data = json.loads(root_synonyms_f.read())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 15 column 827 (char 1127)
```

**Comment by wrathagom** [comment]
thanks!

**Comment by tmbo** [comment]
should be fixed in the latest master version.
