### ISSUE TITLE
Problem with german Umlauts

### ISSUE THREAD

**Issue by m0rth1um** [RasaHQ/rasa_nlu#719]
**Rasa NLU version** (e.g. `0.7.3`): 0.10.4

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): spacy_sklearn

**Operating system** (windows, osx, ...): macOSX Sierra

**Issue**:

```
2017-12-06 17:13:27+0100 [_GenericHTTPChannelProtocol,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/morth/src/enaptfix-bot/venv/lib/python3.6/site-packages/klein/app.py", line 50, in _call
	    result = f(*args, **kwargs)
	  File "/Users/morth/src/enaptfix-bot/venv/lib/python3.6/site-packages/rasa_nlu/server.py", line 92, in decorated
	    return f(*args, **kwargs)
	  File "/Users/morth/src/enaptfix-bot/venv/lib/python3.6/site-packages/rasa_nlu/server.py", line 77, in decorated
	    return f(*args, **kwargs)
	  File "/Users/morth/src/enaptfix-bot/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
	    return _inlineCallbacks(None, gen, Deferred())
	--- <exception caught here> ---
	  File "/Users/morth/src/enaptfix-bot/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
	    result = g.send(result)
	  File "/Users/morth/src/enaptfix-bot/venv/lib/python3.6/site-packages/rasa_nlu/server.py", line 133, in parse_get
	    for key, value in request.args.items()}
	  File "/Users/morth/src/enaptfix-bot/venv/lib/python3.6/site-packages/rasa_nlu/server.py", line 133, in <dictcomp>
	    for key, value in request.args.items()}
	builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 5: invalid start byte
2017-12-06 17:13:27+0100 [-] "127.0.0.1" - - [06/Dec/2017:16:13:27 +0000] "GET /parse?q=Das%20T\xfcrschloss%20an%20meiner%20Eingangst\xfcr%20ist%20defekt&project=default HTTP/1.1
```

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": "spacy_sklearn",
  "path" : "./projects",
  "data" : "./data/examples/dialogflow",
  "language": "de"
}
```

**Comment by tmbo** [comment]
So this happens if you use a trained model and send a `GET` request to it? can you please add a curl request that leads to the failure?

**Comment by m0rth1um** [comment]
I already made some hacky Fix, but it's probably not ready to merge
```
diff --git a/rasa_nlu/server.py b/rasa_nlu/server.py
index 260518ee..7d9eb1bd 100644
--- a/rasa_nlu/server.py
+++ b/rasa_nlu/server.py
@@ -135,8 +135,12 @@ class RasaNLU(object):
     def parse_get(self, request):
         request.setHeader('Content-Type', 'application/json')
         if request.method.decode('utf-8', 'strict') == 'GET':
-            request_params = {key.decode('utf-8', 'strict'): value[0].decode('utf-8', 'strict')
-                              for key, value in request.args.items()}
+            try:`
+                request_params = {key.decode('utf-8', 'strict'): value[0].decode('utf-8', 'strict')
+                                  for key, value in request.args.items()}
+            except UnicodeDecodeError:
+                request_params = {key.decode('cp1252', 'strict'): value[0].decode('cp1252', 'strict')
+                                  for key, value in request.args.items()}
         else:
             request_params = simplejson.loads(
                     equest.content.read().decode('utf-8', 'strict'))

**Comment by tmbo** [comment]
Intersting, isn't `cp1252` an encoding usually only found on windows machines? what do you use to send the request to the servers? how do the headers look like?

**Comment by m0rth1um** [comment]
I use rasa with https://github.com/botpress/botpress-rasa and I am working on macOS Sierra. i am also confused about the windows encoding

**Comment by eng-renanmoura** [comment]
I had the same problem with characters in Brazilian portuguese.
@m0rth1um hacky fix did the trick
FYI, my environment is running on a ubuntu VM and I'm testing in a mac
