### ISSUE TITLE
according the tutor of rasa_core, while running rasa.train, reports the following error

### ISSUE THREAD

**Issue by learnerzhang** [RasaHQ/rasa_nlu#722]
python -m rasa_nlu.train -c nlu_model_config.json --fixed_model_name current
INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en'
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/zhangzhen/TestEnv3/lib/python3.6/site-packages/rasa_nlu/train.py", line 125, in <module>
    do_train(config)
  File "/Users/zz/TestEnv3/lib/python3.6/site-packages/rasa_nlu/train.py", line 111, in do_train
    trainer = Trainer(config, component_builder)
  File "/Users/zz/TestEnv3/lib/python3.6/site-packages/rasa_nlu/model.py", line 131, in __init__
    component_name, config)
  File "/Users/zz/TestEnv3/lib/python3.6/site-packages/rasa_nlu/components.py", line 327, in create_component
    component = registry.create_component_by_name(component_name, config)
  File "/Users/zz/TestEnv3/lib/python3.6/site-packages/rasa_nlu/registry.py", line 160, in create_component_by_name
    return component_clz.create(config)
  File "/Users/zz/TestEnv3/lib/python3.6/site-packages/rasa_nlu/utils/spacy_utils.py", line 52, in create
    nlp = spacy.load(spacy_model_name, parser=False)
  File "/Users/zz/TestEnv3/lib/python3.6/site-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/Users/zz/TestEnv3/lib/python3.6/site-packages/spacy/util.py", line 119, in load_model
    raise IOError("Can't find model '%s'" % name)
OSError: Can't find model 'en'

how to solve it

**Comment by learnerzhang** [comment]
https://core.rasa.ai/tutorial_basics.html

**Comment by learnerzhang** [comment]
maybe i got the approach. ->$  python -m spacy download en

**Comment by tmbo** [comment]
Yes, you need to install the spacy language model.

**Comment by SibaprasadM** [comment]
I had similar issues while trying in anaconda.
I ran anaconda command prompt in admin privilege and executed python -m spacy download en
This ensured successful symbolic link creation to spacy language model.

Ensure you have created directory models/nlu/default/current in your project folder.
then execute: python -m rasa_nlu.train -c nlu_model_config.json --fixed_model_name current

This successfully trains the model and model is saved to models/nlu/default/current location.
