### ISSUE TITLE
Bug in MarkDown to JSON conversion

### ISSUE THREAD

**Issue by parthsharma1996** [RasaHQ/rasa_nlu#724]
**Rasa NLU version** (e.g. `0.10.5`):

**Used backend / pipeline** (`spacy_sklearn`):

**Operating system** (Arch Linux):

**Issue**: I was using a `.md` file as training data. However, I got the following error:-
```
INFO:rasa_nlu.converters:Training data format at data/training_data.md is md
Traceback (most recent call last):
  File "train_nlu.py", line 42, in <module>
    nlu_model_directory = train_nlu()
  File "train_nlu.py", line 25, in train_nlu
    training_data = load_data('data/training_data.md')
  File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu/converters.py", line 354, in load_data
    return load_markdown_data(files[0])
  File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu/converters.py", line 167, in load_markdown_data
    data = MarkdownToJson(filename)
  File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu/utils/md_to_json.py", line 32, in __init__
    self.load()
  File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu/utils/md_to_json.py", line 51, in load
    self._parse_intent_or_synonym_example(row)
  File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu/utils/md_to_json.py", line 67, in _parse_intent_or_synonym_example
    self.entity_synonyms[-1]['synonyms'].append(example_line)
IndexError: list index out of range
```

After, some experimentation I realized that this is because of the comments in my MarkDown file. This error didn't occur when I removed the comments. Inspecting the source code confirmed my belief. The conversion script doesn't handle comments.

I've figured out and fixed the bug ( there needs to be a third state, e.g.`DEFAULT` to handle comments in the `md_to_json.py` file in the `rasa_nlu/utils/` folder ). I would be more than happy to create a pull request.  Though I'm new to development so my fix might be sub-optimal.

**Comment by tmbo** [comment]
@parthsharma1996 thanks for that issue report. I'd be happy to take a look at your PR - don't worry about the quality, I'll do a review of the change and if there is something that needs changing I'll let you know. It is a great way to improve your coding skills 🙂

**Comment by kumarvgit** [comment]
when given an input "end" or "stop" it gives the error

__________________ Stack trace: BEGIN __________________
2018-05-07 14:13:02+0530 [-] "x.x.x.x" - - [07/May/2018:08:43:01 +0000] "POST /parse?q=end HTTP/1.1" 500 40 "-" "PostmanRuntime/7.1.1"
ERROR:__main__:list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/server.py", line 155, in parse_get
    else threads.deferToThread(self.data_router.parse, data))
  File "<USER_HOME_FOLDER>/.local/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "<USER_HOME_FOLDER>/.local/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "<USER_HOME_FOLDER>/.local/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "<USER_HOME_FOLDER>/.local/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/data_router.py", line 201, in parse
    model)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/project.py", line 116, in parse
    response = self._models[model_name].parse(text, time)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/model.py", line 291, in parse
    component.process(message, **self.context)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/extractors/crf_entity_extractor.py", line 126, in process
    extracted = self.add_extractor_name(self.extract_entities(message))
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/extractors/crf_entity_extractor.py", line 146, in extract_entities
    return self._from_crf_to_json(message, ents)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/extractors/crf_entity_extractor.py", line 199, in _from_crf_to_json
    ent_word_idx, entities)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/extractors/crf_entity_extractor.py", line 151, in most_likely_entity
    entity_probs = entities[idx]
IndexError: list index out of range
__________________ Stack trace: END __________________

Additional info:
OS: Ubuntu x86_x64

**Comment by tmbo** [comment]
This is a different issue. Please create a new issue appending the markdown file that lead to the error.
