### ISSUE TITLE
Error when running 2 models of different languages (en, es) in same web server

### ISSUE THREAD

**Issue by gregfitz23** [RasaHQ/rasa_nlu#839]
**Rasa NLU version** (e.g. `0.7.3`): `0.11.2`

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): `["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf", "ner_synonyms", "ner_duckling", "ner_spacy", "intent_classifier_sklearn"]`

**Operating system** (windows, osx, ...): osx

**Issue**:
I've been using Rasa in a production app for about a year now. Excellent project. I've recently attempted to add support for a Spanish-language model, and am running into an issue. I have trained two separate models and am hosting them in the same web server via `python -m rasa_nlu.server -c /app/config.json`.

When I query the `/parse` endpoint for the Spanish language model (`http://localhost:5000/parse?project=amber-es&q=Encuentra%20un%20proveedor%20de%20PCP%20llamado%20Doctor%20Jones%20cerca%20de%20Spokane,%20WA`) it works fine and I get the expected result ( a well-formed intent). If I then query the English-language model (`http://localhost:5000/parse?project=amber&q=Find%20a%20pcp%20named%20jones%20in%20clayton,%20mo`), this also works fine (after a delay while it loads up the components).

If I then return to the same Spanish-language model (same query as above) I receive the following error in the browser:
```json
{
  error: "shapes (13,300) and (50,128) not aligned: 300 (dim 1) != 50 (dim 0)"
}
```
and stacktrace:
```
rasa_1                                 | ERROR:__main__:shapes (13,300) and (50,128) not aligned: 300 (dim 1) != 50 (dim 0)
rasa_1                                 | Traceback (most recent call last):
rasa_1                                 |   File "/app/rasa_nlu/server.py", line 157, in parse_get
rasa_1                                 |     else threads.deferToThread(self.data_router.parse, data))
rasa_1                                 |   File "/usr/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
rasa_1                                 |     result = inContext.theWork()
rasa_1                                 |   File "/usr/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
rasa_1                                 |     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
rasa_1                                 |   File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
rasa_1                                 |     return self.currentContext().callWithContext(ctx, func, *args, **kw)
rasa_1                                 |   File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
rasa_1                                 |     return func(*args,**kw)
rasa_1                                 |   File "rasa_nlu/data_router.py", line 164, in parse
rasa_1                                 |     response, used_model = self.project_store[project].parse(data['text'], data.get('time', None), model)
rasa_1                                 |   File "rasa_nlu/project.py", line 77, in parse
rasa_1                                 |     response = self._models[model_name].parse(text, time)
rasa_1                                 |   File "rasa_nlu/model.py", line 295, in parse
rasa_1                                 |     component.process(message, **self.context)
rasa_1                                 |   File "rasa_nlu/utils/spacy_utils.py", line 82, in process
rasa_1                                 |     message.set("spacy_doc", self.nlp(message.text.lower()))
rasa_1                                 |   File "/usr/local/lib/python2.7/site-packages/spacy/language.py", line 333, in __call__
rasa_1                                 |     doc = proc(doc)
rasa_1                                 |   File "pipeline.pyx", line 390, in spacy.pipeline.Tagger.__call__
rasa_1                                 |   File "pipeline.pyx", line 402, in spacy.pipeline.Tagger.predict
rasa_1                                 |   File "/usr/local/lib/python2.7/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
rasa_1                                 |     return self.predict(x)
rasa_1                                 |   File "/usr/local/lib/python2.7/site-packages/thinc/api.py", line 55, in predict
...
```

It's as if loading the English-language model is overwriting a shared Spacy component which is then being used for the Spanish model as well.

This seems like it should be a supported use case (according to the docs), and I can confirm this works in `0.10.6`.

**Content of configuration file** (if used & relevant):
*config.en.json*
```json
{
  "project": "amber",
  "spacy_model_name": "en",
  "fixed_model_name": "en",
  "pipeline": ["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf", "ner_synonyms", "ner_duckling", "ner_spacy", "intent_classifier_sklearn"],
  "path" : "./models",
  "language": "en",
  "data" : "./data/amber/training_data.json"
}
```
*config.es.json*
```json
{
  "project": "amber",
  "spacy_model_name": "es",
  "fixed_model_name": "es",
  "pipeline": ["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf", "ner_synonyms", "ner_duckling", "ner_spacy", "intent_classifier_sklearn"],
  "path" : "./models",
  "language": "es",
  "data" : "./data/amber/training_data_es.json"
}
```

**Comment by tmbo** [comment]
Thanks a lot, let me try to reproduce this locally. Which models did you use, the default models for `en` and `es`?

**Comment by tmbo** [comment]
Can you post the output for both, `python -m spacy info es` and `python -m spacy info en`

**Comment by gregfitz23** [comment]
I used the default `en` model.  For `es` I used `python -m spacy download es_core_news_md && python -m spacy link es_core_news_md es`.

Results of `spacy info` below:

```
/app # python -m spacy info en

    Info about model en

    lang               en             
    pipeline           [u'tagger', u'parser', u'ner']
    name               core_web_md    
    license            CC BY-SA 3.0   
    author             Explosion AI   
    url                https://explosion.ai
    description        English multi-task CNN trained on OntoNotes, with GloVe vectors trained on Common Crawl. Assigns word vectors, context-specific token vectors, POS tags, dependency parse and named entities.
    vectors            {u'keys': 684830, u'width': 300, u'vectors': 20000}
    sources            [u'OntoNotes 5', u'Common Crawl']
    version            2.0.0          
    link               /usr/local/lib/python2.7/site-packages/spacy/data/en
    source             /usr/local/lib/python2.7/site-packages/en_core_web_md
    spacy_version      >=2.0.0        
    parent_package     spacy          
    speed              {u'gpu': None, u'nwords': 291344, u'cpu': 4532.930431222}
    email              contact@explosion.ai
    accuracy           {u'token_acc': 99.8609203297, u'ents_p': 85.6222222222, u'ents_r': 86.1342424412, u'uas': 91.7226238412, u'tags_acc': 97.1103903351, u'ents_f': 85.8774691444, u'las': 89.838878402}

/app # python -m spacy info es

    Info about model es

    lang               es             
    pipeline           [u'tagger', u'parser', u'ner']
    accuracy           {u'token_acc': 100.0, u'ents_p': 89.2946381027, u'ents_r': 88.7348882647, u'uas': 90.2078828119, u'tags_acc': 97.0814925316, u'ents_f': 89.0138832176, u'las': 87.2390598003}
    name               core_news_md   
    license            GPL            
    author             Explosion AI   
    url                https://explosion.ai
    notes              Because the model is trained on Wikipedia, it may perform inconsistently on many genres, such as social media text. The NER accuracy refers to the "silver standard" annotations in the WikiNER corpus. Accuracy on these annotations tends to be higher than correct human annotations.
    vectors            {u'keys': 533736, u'width': 50, u'vectors': 20000}
    sources            [u'AnCora', u'Wikipedia']
    version            2.0.0          
    link               /usr/local/lib/python2.7/site-packages/spacy/data/es
    source             /usr/local/lib/python2.7/site-packages/es_core_news_md
    spacy_version      >=2.0.0a18     
    parent_package     spacy          
    email              contact@explosion.ai
    description        Spanish multi-task CNN trained on the AnCora and WikiNER corpus. Assigns context-specific token vectors, POS tags, dependency parse and named entities. Supports identification of PER, LOC, ORG and MISC entities.
```

**Comment by tmbo** [comment]
This is a known bug in spacy 2.0 - they are on it fixing it. https://github.com/explosion/spaCy/issues/1660

**Comment by tmbo** [comment]
There is nothing to do here but to wait for the above mentioned issue on the spacy project to be fixed.

**Comment by gregfitz23** [comment]
@tmbo - there has been little movement on the the spaCy ticket that's the underlying cause of this issue.  Do you know if `spaCy 2.0` a hard requirement for `Rasa NLU > 0.11`, or is there an opportunity to continue to use `spaCy 1.8`?

**Comment by tmbo** [comment]
@gregfitz23 I think you should be fine using an older spacy version

**Comment by gregfitz23** [comment]
Thanks @tmbo, I'll try it out.
