### ISSUE TITLE
AttributeError: 'module' object has no attribute 'unpack'

### ISSUE THREAD

**Issue by mtbikerj** [RasaHQ/rasa_nlu#864]
it appears that perhaps tensorflow has renamed tf.unpack() to tf.unstack()??

using Docker image rasa/rasa_nlu:latest-bare

Secondary docker container built using:
RUN pip install rasa_nlu[spacy]
RUN python -m spacy download en_core_web_md
RUN python -m spacy link en_core_web_md en

OS: CentOs 7

INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/app/rasa_nlu/train.py", line 125, in <module>
    do_train(config)
  File "/app/rasa_nlu/train.py", line 111, in do_train
    trainer = Trainer(config, component_builder)
  File "rasa_nlu/model.py", line 127, in __init__
    component_name, config)
  File "rasa_nlu/components.py", line 356, in create_component
    config)
  File "rasa_nlu/registry.py", line 160, in create_component_by_name
    return component_clz.create(config)
  File "rasa_nlu/utils/spacy_utils.py", line 53, in create
    nlp = spacy.load(spacy_model_name, parser=False)
  File "/usr/local/lib/python2.7/site-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python2.7/site-packages/spacy/util.py", line 113, in load_model
    return load_model_from_link(name, **overrides)
  File "/usr/local/lib/python2.7/site-packages/spacy/util.py", line 132, in load_model_from_link
    return cls.load(**overrides)
  File "/usr/local/lib/python2.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/usr/local/lib/python2.7/site-packages/spacy/util.py", line 177, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/usr/local/lib/python2.7/site-packages/spacy/util.py", line 159, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/usr/local/lib/python2.7/site-packages/spacy/language.py", line 638, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/usr/local/lib/python2.7/site-packages/spacy/util.py", line 522, in from_disk
    reader(path / key)
  File "/usr/local/lib/python2.7/site-packages/spacy/language.py", line 625, in <lambda>
    ('vocab', lambda p: self.vocab.from_disk(p)),
  File "vocab.pyx", line 383, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 372, in spacy.vectors.Vectors.from_disk
  File "/usr/local/lib/python2.7/site-packages/spacy/util.py", line 522, in from_disk
    reader(path / key)
  File "vectors.pyx", line 350, in spacy.vectors.Vectors.from_disk.load_key2row
  File "vectors.pyx", line 351, in spacy.vectors.Vectors.from_disk.load_key2row
  File "/usr/local/lib/python2.7/site-packages/msgpack_numpy.py", line 179, in unpack
    return _unpacker.unpack(stream, encoding=encoding, **kwargs)
AttributeError: 'module' object has no attribute 'unpack'

**Comment by mtbikerj** [comment]
Seems to be an issue with the newest spacy library https://github.com/explosion/spaCy/issues/2015

**Comment by ines** [comment]
We just published spaCy v2.0.9 which uses an explicit version pin of `msgpack-python==0.5.4` (and prevents spaCy from installing the latest update of it that was released today and was causing this problem). So you should be able to simply upgrade spaCy:

```python
pip install -U spacy
```

**Comment by mtbikerj** [comment]
@ines - worked like a charm.  Thanks
