### ISSUE TITLE
AttributeError: 'English' object has no attribute 'path'

### ISSUE THREAD

**Issue by jamesthatcher** [RasaHQ/rasa_nlu#878]
**Rasa NLU version** 0.11.3
**Spacy version** 0.101.0

**Used backend / pipeline** spacy_sklearn

**Operating system** osx:

**Issue**: Issue with Spacy attribute. Please could you provide solution if known? Thanks

trainer.train(training_data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/anaconda3/lib/python3.6/site-packages/rasa_nlu/model.py", line 131, in __init__
    component_name, config)
  File "/Users/anaconda3/lib/python3.6/site-packages/rasa_nlu/components.py", line 301, in create_component
    component = registry.create_component_by_name(component_name, config)
  File "/Users/anaconda3/lib/python3.6/site-packages/rasa_nlu/registry.py", line 160, in create_component_by_name
    return component_clz.create(config)
  File "/Users/anaconda3/lib/python3.6/site-packages/rasa_nlu/utils/spacy_utils.py", line 54, in create
    cls.ensure_proper_language_model(nlp)
  File "/Users/anaconda3/lib/python3.6/site-packages/rasa_nlu/utils/spacy_utils.py", line 115, in ensure_proper_language_model
    if nlp.path is None:
AttributeError: 'English' object has no attribute 'path'

**Content of configuration file** (if used & relevant):
```
{
    "pipeline": "spacy_sklearn",
    "data": "data/training.json"
}

```

**Comment by wrathagom** [comment]
@jamesthatcher that doesn't look like a valid Spacy version. The requirements file shows `spacy==2.0.5` as the dependncy. Also did you download/link the spacy models?
