### ISSUE TITLE
What is the test data format to be used for evaluation?

### ISSUE THREAD

**Issue by pawan9489** [RasaHQ/rasa_nlu#894]
**Rasa NLU version** :  0.11.3
**Used backend / pipeline** : spacy_sklearn
**Operating system** : windows

**Issue**:
What is the test data format to be used for evaluation?
```json
python -m rasa_nlu.evaluate -d data/test_data.json -c configs/config_spacy.json --mode crossvalidation
INFO:rasa_nlu.converters:Training data format at data/test.json is rasa_nlu
INFO:rasa_nlu.training_data:Training data stats:
        - intent examples: 2 (1 distinct intents)
        - found intents: 'navigate_page'
        - entity examples: 2 (1 distinct entities)
        - found entities: 'page'

INFO:__main__:Raw data intent examples: 2
INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en_core_web_lg'
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en_core_web_lg'.
INFO:__main__:Evaluation started
Traceback (most recent call last):
  File "Program Files/Python36/lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "Program Files/Python36/lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Program Files/Python36/lib/site-packages/rasa_nlu/evaluate.py", line 481, in <module>
    results = run_cv_evaluation(data, int(args.folds), nlu_config)
  File "Program Files/Python36/lib/site-packages/rasa_nlu/evaluate.py", line 433, in run_cv_evaluation
    for train_index, test_index in skf.split(data, y_true):
  File "Program Files/Python36/lib/site-packages/sklearn/model_selection/_split.py", line 672, in split
    y = check_array(y, ensure_2d=False, dtype=None)
  File "Program Files/Python36/lib/site-packages/sklearn/utils/validation.py", line 462, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.
```
test_data.json
```
{
  "rasa_nlu_data": {
    "regex_features": [],
    "entity_synonyms": [],
    "common_examples": [
      {
        "text": "where is sickness Page",
        "intent": "navigate_page",
        "entities": [
          {
            "start": 9,
            "end": 17,
            "value": "sickness",
            "entity": "page"
          }
        ]
      },
      {
        "text": "where can I find leave types page",
        "intent": "navigate_page",
        "entities": [
          {
            "start": 17,
            "end": 28,
            "value": "leave types",
            "entity": "page"
          }
        ]
      }
    ]
  }
}
```
After getting cross-validated it will create a new model.
If I train again then we will get a model that is same as before cross-validations. Right?
Then how will the RASA-NLU system retains the cross-validation results for the next training?

**Comment by tmbo** [comment]
Cross-validation can be used to evaluate a data set with a given pipeline and configuration. It allows you to more accurately estimate if the classification and extraction pipeline is working properly and how well it is doing. 

To do the cross-validation you need a bit more than two examples, as the CV is done with  I think 3 or 5 splits by default.
