### ISSUE TITLE
Getting error for evaluating the model

### ISSUE THREAD

**Issue by ayyappa428** [RasaHQ/rasa_nlu#905]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):

**Issue**:

**Content of configuration file** (if used & relevant):
```json

```
Rasa NLU version : 0.11.3

Used backend / pipeline (`mitie`, `spacy_sklearn`, ...): spacy_sklearn

**Operating system** (windows, osx, ...): Linux

*Content of configuration file** (if used & relevant): Json

**Issue**:
while I am working with evaluation of the model and i want to check accuracy I am getting the error below

ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

Mycommand: python -m rasa_nlu.evaluate -d data/demo-rasa.json -c config_spacy.json --mode crossvalidation

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/rasa_nlu/evaluate.py", line 481, in <module>
    results = run_cv_evaluation(data, int(args.folds), nlu_config)
  File "/usr/local/lib/python2.7/dist-packages/rasa_nlu/evaluate.py", line 433, in run_cv_evaluation
    for train_index, test_index in skf.split(data, y_true):
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_split.py", line 672, in split
    y = check_array(y, ensure_2d=False, dtype=None)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 462, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

**Comment by tmbo** [comment]
You need to pass in more training data. It seems like your `demo-rasa.json` doesn't contain enough intent training examples.
