### ISSUE TITLE
Mixed json yml training data 

### ISSUE THREAD

**Issue by Johnz86** [RasaHQ/rasa_nlu#982]
**Rasa Core version**:
0.8.5
**Rasa NLU version** (e.g. `0.7.3`):
0.11.4
**Used backend / pipeline** 
spacy_sklearn
**Python version**: 
3.6.4
**Operating system** (windows, osx, ...):
Docker linux
**Issue**:
According the docs http://rasa-nlu.readthedocs.io/en/latest/config.html#data
The data keyword can specify:
Location  of the training data. For JSON and markdown data, this can either be a  single file or a directory containing multiple training data files.
**Content of configuration file**
```json
{
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "language": "en",
  "project": "sara",
  "data" : "./data/training"
}
```
If your folder contains mixed yml and json training data, I get following error during training:

```
INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en'
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
INFO:rasa_nlu.converters:Training data format at ./data/training is rasa_nlu
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/converters.py", line 34, in _read_json_from_file
    return json.loads(f.read())
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/train.py", line 125, in <module>
    do_train(config)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/train.py", line 113, in do_train
    training_data = load_data(config['data'], config['language'])
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/converters.py", line 365, in load_data
    return load_rasa_data(files)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/converters.py", line 266, in load_rasa_data
    data = _read_json_from_file(filename)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/converters.py", line 37, in _read_json_from_file
    "{}".format(os.path.abspath(filename), e))
Exception: Failed to read json from '/app/data/training/nlu.md'. Error: Expecting value: line 1 column 1 (char 0)
```
Please improve the doc, that only one type of training data is supported or fix the behaviour.

Thanks

**Comment by akelad** [comment]
yes good point, would you be able to create a PR to fix the docs?

**Comment by wrathagom** [comment]
@tmbo I thought I saw in one of your PRs that mixed formats were supposed to work?

**Comment by akelad** [comment]
yes, it is possible now with version 0.12 of NLU 🙂 @Johnz86 so the solution would be upgrading to 0.12, i'll close this issue - let me know if you're still having problems though
